### ISSUE TITLE
enhancement: rename workspace and assignments

### ISSUE THREAD

**Issue by acrisci** [i3/i3#1473]
When a workspace is renamed to the name of a workspace is assigned to a particular monitor, the workspace should be moved to that monitor.

**Comment by stapelberg** [comment]
Yes. I think the fact that it doesn’t is a bug.

**Comment by Airblader** [comment]
I've created a draft for this. I wrote a test that works now, but I'll test this a bit tomorrow when I have access to an external screen. 

The fix is crude right now and requires some refactoring. The entire logic for moving a workspace currently is in the commands handler, but should probably be moved to `src/workspace.c` so that it can be reused nicely.
