### ISSUE TITLE
Matching by title does not work for some windows

### ISSUE THREAD

**Issue by taerath** [i3/i3#1526]
(Seems that I can't reopen #1525 after upgrading i3. Bummer).

i3wm does not seem to swallow some windows correctly. For example, the window opened by `ipython3 qtconsole` (debian package *ipython3-qtconsole*) comes up with a title of *IPython*, `xprop` reports `WM_NAME(STRING) = "IPython"`, but i3wm does not match it to a `"swallows": [ { "title": "^IPython" }]` directive.

```
[0] nelarikon:~$ cat test.json 
{
    "border": "normal",
    "floating": "auto_off",
    "geometry": {
       "height": 510,
       "width": 761,
       "x": 0,
       "y": 0
    },
    "name": "IPython",
    "percent": 0.391100702576112,
    "swallows": [
       {
	"title": "^IPython"
       }
    ],
    "type": "con"
}
[0] nelarikon:~$ i3-msg 'debuglog on; shmlog on; reload'[{"success":true},{"success":true},{"success":true}]
[0] nelarikon:~$ i3-msg "workspace 3; append_layout test.json"; ipython3 qtconsole &[{"success":true},{"success":true}]
[1] 8607
# Two windows open up on workspace 3, the ipython window and the empty placeholder
[0] nelarikon:~$ i3-dump-log | bzip2 -c | curl --data-binary @- http://logs.i3wm.org
[0] nelarikon:~$ i3-dump-log > i3.log
[0] nelarikon:~$ i3 --version
i3 version 4.9 (2015-02-28, branch "tags/4.9") © 2009-2014 Michael Stapelberg and contributors
```

For now, I've put the log on https://trialphaenergy.box.com/shared/static/txy7tyn5qcl0g0gz4r6wfn2dem95ikpc.log

(First reported at  https://faq.i3wm.org/question/5447/how-to-match-ipython-window/)

**Comment by Airblader** [comment]
Is that really `WM_NAME`? Because there only are `_NET_WM_NAME` and `WM_CLASS`. If it's the latter, you should match on class, not title. 

Can you maybe just post the entire xprop output?

**Comment by taerath** [comment]
Here's the full `xprop` output: https://trialphaenergy.box.com/shared/static/j6333crvnufxu9u4rad616ghtj0tjvxg.txt

**Comment by Airblader** [comment]
Mh. Interesting. Out of curiosity, does it work if you either leave out the circumflex or add a dollar in the end? 

Maybe the application doesn't set the property on startup right away. Not that I understand much of the protocol, but I'd guess that's possible. I don't think i3 reacts to changing window titles for swallowing.

**Comment by taerath** [comment]
Using just `"IPython"` or `^IPython$"` does not work either.

**Comment by Airblader** [comment]
Despite oddly seeing `IPython` being rendered before `append_layout` is called, this excerpt looks interesting:

````
03/06/2015 09:13:13 AM - Checking window 0x0120002e (class (null))
03/06/2015 09:13:13 AM - Regular expression "^IPython" matches "IPython"
03/06/2015 09:13:13 AM - title matches (IPython)
03/06/2015 09:13:13 AM - manage.c:manage_window:304 - Removing match 0x160a6c0 from container 0x1628030
03/06/2015 09:13:13 AM - manage.c:manage_window:309 - new container = 0x1628030
03/06/2015 09:13:13 AM - x.c:x_reinit:174 - resetting state 0x1628a30 to initial
03/06/2015 09:13:13 AM - manage.c:manage_window:342 - Not in fullscreen mode, focusing
03/06/2015 09:13:13 AM - workspace visible? fs = 0x1626910, ws = 0x1626910
```

It looks like it does get matched.

**Comment by taerath** [comment]
Hmm. I guess that's good news? But I can assure you that it most definitely does not get swallowed on the screen.

**Comment by Airblader** [comment]
Oh, yeah, I didn't mean to say I don't believe you :) I'm trying to look into it a bit. But Michael or Tony know this a million times better than me.

**Comment by Airblader** [comment]
For all I can see it gets properly matched. I can reproduce this, though – it doesn't get swallowed for me either.

It seems that we never enter this in `src/manage.c`:

````
    if (nc->window != NULL && nc->window != cwindow) {
        if (!restore_kill_placeholder(nc->window->id)) {
            DLOG("Uh?! Container without a placeholder, but with a window, has swallowed this to-be-managed window?!\n");
        }   
    }
```

Which means we never kill the placeholder window. The reason is that `nc->window` is `NULL`. But why (or whether this really is the issue), I don't know. Michael can probably answer this.

**Comment by Airblader** [comment]
Actually, if you read more of the log, you will see that the window is unmapped and remapped again and since the match has then been removed from the placeholder already, it will not be swallowed again and instead be opened in its own container.

This should only leave the question on why it is unmapped a little bit after having been mapped.

**Comment by taerath** [comment]
What does "mapping" mean? Is that something that i3 does, that the application does, or that X11 does?

**Comment by Airblader** [comment]
Mapping is something the window manager will do. Either on its own or when the client (window) requests it. A mapped window basically means it's visible on the screen. For some reason, this window gets mapped, unmapped and mapped again.

**Comment by Airblader** [comment]
Could it be that ipython3 somehow unmaps any window with that name? That sounds really odd and wrong, but here's what I just found out: if you choose a different name for the container in your layout file (the name is pretty irrelevant there anyway), it will get swallowed correctly.

**Comment by taerath** [comment]
I thought the mapping is  done by the window manager (aka i3)? Then how can ipython3 unmap something? Or do you mean ipython3 would *close* existing windows that have "IPython" in its name? I don't think that's the case, you can have multiple Ipython windows (from multiple, separate processes) open at the same time.

**Comment by taerath** [comment]
...but I'll try it with a different name on Monday to see if that works for me to. Very odd. Thanks for investigating!

**Comment by Airblader** [comment]
i3 can either unmap a window on its own terms or it will do it if the window requests to be unmapped. And I'm pretty sure i3 closes windows when they are unmapped (but I stand to be corrected) since the point of a tiling window manager is to always have all windows visible.

In fact when I noticed this, my first reaction was to see what ipython will do if I open it several times. Since it just opens multiple times I really don't know why it would request to unmap the other window (if it can even do that). Either way, *someone* unmaps it, I'm guessing my way through this at best.

My knowledge on the X11 protocol is really rough and bad and I'm sure @stapelberg can shed a lot more light on this and correct me on all the wrong things I might have said. At least we have a workaround which really shouldn't be a problem. I'd love to understand what's going on here, though.

**Comment by taerath** [comment]
Ok, I can confirm that it works if I use something else for `name` in the json file. Very odd, but quite an acceptable workaround. Thanks Airblader!

**Comment by stapelberg** [comment]
Thanks for the detailed report and analysis. See the commit message for details on what the problem was.

**Comment by Airblader** [comment]
Thank you for the commit message. Makes a lot of sense now.
