### ISSUE TITLE
[enhancement] Assign windows to outputs

### ISSUE THREAD

**Issue by Airblader** [i3/i3#1530]
Given that there already is a `A_TO_OUTPUT` mode, my guess is that this is a feature worth implementing, right? Any idea on the syntax? I have a draft for this using

````
# new
assign […] output LVDS-0
# for consistency
assign […] workspace www
# and for at least almost perfect backwards compatibility
assign […] www
```

This breaks backwards compatibility if someone named a workspace `output`. Would this be acceptable?

The draft is currently applied to my fork. I will port it to i3 once I know it's worth to keep working on this and tests are written etc.

**Comment by Airblader** [comment]
Some thoughts and questions if a patch for this were to be accepted:

* Do we require any special logic when the same window is matched to a workspace *and* an output? I'd prefer not touching this case as it requires not stopping after having found one match, but also because I don't see a benefit in handling this (the user should assign to a workspace and assign the workspace to an output).
* If the specified output currently doesn't exist (including being inactive), should we reject the command or keep looking for another assignment in this case?

**Comment by Airblader** [comment]
Just for reference, my draft (rough, not fully done, no tests yet): https://github.com/Airblader/i3/commit/303ca50619c822dce752775723d943b572d78c7b

**Comment by acrisci** [comment]
I would say this feature would be too redundant with `for_window` to justify another command.

People can just do this:

    for_window [class="Xfce4-notifyd"] move to output DVI-D-0

**Comment by Airblader** [comment]
That's actually a really good point. I'll opt for removing the `A_TO_OUTPUT` thing then.

**Comment by Airblader** [comment]
Out of curiosity, why is `assign` needed for workspaces? Couldn't I use `for_window` there, too?

**Comment by acrisci** [comment]
The functional difference is that `assign` will set the window to urgent when it is not focused, but I suspect that it is a legacy command that can't be removed because of the projects strong stance for backwards compatibility.

**Comment by Airblader** [comment]
Ah, alright. Thank you. Maybe @stapelberg can say something about whether the urgency flag would justify this feature or even on whether we could drop the old feature with v5 and offer a script to migrate the config (much like it was done with v4).

**Comment by acrisci** [comment]
I wouldn't mind a major version bump.

**Comment by stapelberg** [comment]
`assign` was introduced earlier than `for_window`, yes.

Since `assign` is effective a bit earlier than `for_window`, there might be very subtle differences in how applications behave with one or the other, but I have no evidence to back that up (or refute it).

As @acrisci already mentioned, we won’t be removing the `assign` directive for backward compatibility.

It might be feasible to internally convert `assign` statements into `for_window` statements and hence reduce code complexity. But I’m not sure the potential application breakage is worth the effort.

Removing `A_TO_OUTPUT` also sounds good to me. I’m closing this issue since I think we’ve discussed everything there is to discuss — pull requests welcome :).
