### ISSUE TITLE
[enhancement] Support moving windows to marked containers

### ISSUE THREAD

**Issue by carrotIndustries** [i3/i3#1643]
For now, i3 supports moving windows to workspaces. Using the for_window directive I can make the window of an X11 application always open on another workspace so it doesn't interfere with the layout of my development workspace. Unfortunately, this only works for multi-monitor setups.

By adding a command to move a container into a marked container window placing rules can be implemented by using the for_window command.
To illustrate use cases of this command:
This is how my dev workspace looks like
```
+-------------------+
|                   |
|Editor, inside     |
|tabbed container   |
|with Glade, other  |
|Terminals, etc     |
+-------------------+
+--------+ +--------+
|Term1   | |Term2   |
+--------+ +--------+
```` 
When starting my application from Term1, i3 places its window i the split container of Term1 and Term2, which obviously isn't where I want my application to pop up. Instead, it'd be more useful if I can tell i3 to put the application window in the big tabbed container above the terminals.

Another use case: You click on a link in your browser, a PDF download starts, your browser is configured to automatically launch a pdf viewer when the download has finished. Since the download takes some time, you switch to another workspace an do some other stuff. When the pdf viewer finally opens, you move it to the workspace where it's supposed to be, only to find out that the focused container on that workspace was the wrong one, so you end up shuffling the pdf viewer around to place where you want it. This situation also can be simplified by telling i3 to move all pdf viewer windows to the container containing the browser and pdf documents that opened immediately.

The syntax for this command could look like this:

```move [window|container] [to] container <mark>``` where mark is the one previously set using ```mark``` In case a leaf container has been marked, the parent container should be used.

**Comment by acrisci** [comment]
I like this idea because it is potentially very useful in scripts for layout manipulation.

In the past, we've gotten a lot of requests for grouping specific windows into a single container. People want to group all their chat conversations in various chat programs, or put all their browser instances in some tabbed container, and right now the only way to do that reliably is manually.

**Comment by Airblader** [comment]
Agreed. And that makes clear that #1637 should not be implemented.

**Comment by carrotIndustries** [comment]
Any ideas on #1517 in regard to this enhancement? The first use case I described could be solved by  #1517 as well. Both enhancements have unique use cases, but there are some overlapping ones.

**Comment by Airblader** [comment]
I would view the as separate issues and first implement the idea presented here independently of placeholders and see how that works out.

**Comment by Airblader** [comment]
I'll probably open a PR for this soon, I still have to add testcases and play around with some interesting scenarios such as making sure the urgent flag is moved as well. What I figured makes sense and how I implemented it:

* If the target container (the on with the mark) is an actual window, the source window will be inserted behind the target window (e.g., to the right of it inside a H-split)
* If the target container is just a container (e.g., a stacked container), the source window will be inserted  behind the window with the focus within the target container.

**Comment by Airblader** [comment]
@stapelberg Since this can move a container to another workspace, which is a fairly complex process, I wonder whether it'd be okay to first call `con_move_to_workspace` (only if necessary) and *then* insert it at the correct position within that workspace.

As is, that would cause two IPC `move` events to be sent. Alternatives:

* Duplicating a lot of the logic from `con_move_to_workspace` (I'm not so much a fan of this)
* Refactoring common parts (could be tricky)
* Suppressing the first move event with a bool flag

Opinions?

**Comment by Airblader** [comment]
Since moving containers across workspaces is a fairly complex process, I decided to rather refactor that process so it can be reused. One change to the above is that if the mark is held by a container with a window, the container will not be moved right behind the marked container, but right behind the focused container within the marked container's parent.

I think this should be okay. The more sensible usecase is marking the tabbed container rather than a single tab anyway.

This has the benefit of getting all the edgecase stuff such as urgency hints, fullscreen scenarios, dealing with floating windows, … Now I'll have to write some (read: a lot) of tests and hope there's nothing I have overlooked so far.

**Comment by Airblader** [comment]
I'm getting close to being done with this. I wonder whether we should put floating windows into tiling when they are moved to a mark? Right now they are left floating and just put onto the same workspace as the marked container, which is consistent with moving a container to a workspace.
