### ISSUE TITLE
[enhancement] Set mark on window when opening with exec

### ISSUE THREAD

**Issue by ma08** [i3/i3#1682]
This is to make it easier to [set mark](http://i3wm.org/docs/userguide.html#_vim_like_marks_mark_goto) on a window when starting an application.
The outcome will look something like
    `i3-msg 'workspace 2 mark ncm; exec urxvt -e ncmpcpp'`

I personally thing that this would be a useful feature. Setting up marks in the startup(config file) when opening applications will be a good addition.

I would love to work on this if you deem this to be a useful feature.

@Airblader has pointed out that it has nothing to do with i3-msg.
So all I want is implementing something like this
`exec --mark mymark /path/to/application`

**Comment by Airblader** [comment]
I don't get it. What's the new feature?

**Comment by ma08** [comment]
To add a mark to the window when starting it with i3-msg.

**Comment by Airblader** [comment]
> The outcome will look something like
> `i3-msg 'workspace 2 mark ncm; exec urxvt -e ncmpcpp`

Instead of "setting a mark on a window when opening it with i3-msg", do you maybe instead mean "setting a mark on a workspace which will be put on the next window that opens on that workspace"? If not, I'm afraid I don't understand how the quoted fits in.

Also note that i3-msg is just an example implementation for the IPC and not meant to be used for anything but the occasional, simple command. But from what I understand, this has nothing to do with i3-msg (?)

**Comment by ma08** [comment]
No, I just want to set a mark on a window (which is being opened by the exec).
I guess my snippet didn't make things clear. All I want is to set a mark on a window wich is being opened by exec.

**Comment by Airblader** [comment]
So I guess it'd be something like `exec --mark mymark /path/to/application`? I think I'd like that. I had problems with `exec /path/to/application, mark mymark` in the past.

However, it doesn't really have anything to do with i3-msg. :)

**Comment by ma08** [comment]
Yeah exactly that's what I want. I really am not up to terms with the i3 structure so I was a bit off :/ I will try to implement this week after going through the source and getting a better view of everythin. Do you have any suggestions on implementing it?

**Comment by Airblader** [comment]
My suggestion would be to wait for feedback by @stapelberg or @acrisci first. That is, unless you want this so badly that you'd use your patch even if it doesn't get merged.

For the implementation, you could refer to `--no-startup-id`. What you're gonna want to watch out for is making sure that both `exec --no-startup-id --mark foo` and `exec --mark foo --no-startup-id` work (i.e., order does not matter). For setting the mark, look at the implementation of the `mark` command. Lastly, don't forget to write a test. :)

**Comment by ma08** [comment]
Sure, I will wait for their feedback. I have finals going on anyway :/ . Thanks for your help :)

**Comment by acrisci** [comment]
I don't like this feature the way you've described it because it seems too tied to marks, which are not widely used. So then somebody could make the argument for a different command to be executed with an argument, making the convincing case that this command is more widely used than marks, and then suddenly we have to support every command with an argument to `exec`.

What I might like to see is a way to handle the general case of issuing commands to a window opened with `exec` in a more elegant way than from a `for_window` or ipc window::new event. The problem is that `exec` opens the window asynchronously, so any commands after it do not apply to the opened window.

However, this would need to be done in such a way that we don't have to rewrite the command parser. I think you would have to make the case that the complexity of the implementation does not outweigh the benefits of the feature.

**Comment by Airblader** [comment]
Mh, yeah, I guess the asynchronous thing also means that this wouldn't be easy to implement anyway.

**Comment by ma08** [comment]
Yeah I've anticipated the asynchronous nature to be a blocking point. I will start looking into how i3 works and see if I can come up with something acceptable. It would be great if someone with more experience/knowledge pitches something that can be worked upon :)

**Comment by stapelberg** [comment]
I agree with what @acrisci said, tying this feature to marks is not a good idea.

With regards to implementation, we already do something similar for placing application windows on the workspace on which they are started, and we use the startup id for that.

If we used that same feature and added a `--for-each-window` flag to `exec`, that could cover your use-case. You could use `exec --for-each-window "mark foobar" firefox`. Note that it has to be executed for each window the app starts (on which the app sets the corresponding startup id hint) because otherwise we’d be dictating policy, and that will not work with every app.

Before I can make a decision on whether this feature will be accepted into i3, can you (and/or others) outline your use-case, i.e. what you would be able to accomplish with the feature that you cannot currently do?

**Comment by acrisci** [comment]
I can see why you would need to execute the command for each window in cases such as an application that opens a splash screen before the main window.

**Comment by ma08** [comment]
@stapelberg  I will be describing why I want this feature by giving my use-case in detail.

I want  bindings to focus windows which I work with frequently. These include vim, ncmpcpp, pidgin etc.

For this I need to setup the bindings during the startup.  For most applications I can exploit the `title` and `class` attributes to set a binding to focus the desired application (not exactly a mark but solves my problem). I do that by
    bindsym $mod+Control+v [class="URxvt" title="VIM"] focus
    bindsym $mod+Control+b [class="Firefox" title="Vimperator"] focus
This works well for most applications as they have definite class and title attributes. But for ncmpcpp(which runs in terminal),  the class is set as `URxvt` and the title is `urxvt`. I have multiple windows for ncmpcpp - one for library, one for visualizer and another for playlist. As all of them have same class and title attributes I can't set a binding to focus a particular ncmpcpp window without using marks.

Right now my only option to tackle these kind of windows is set up bindings to focus a particular mark and after startup I need to manually set up the marks for each of these windows as we can't put marks at startup.

That's why I need exec to support the marks to allow me to setup marks for windows which don't have definite class and title attributes.

**Comment by Airblader** [comment]
@ma08 For that you could use start the windows via `urxvt -name ncmpcpp-library`, no? Then you can match it on the `instance`.

**Comment by ma08** [comment]
@Airblader  oops. I should have known that. That solves all my problems I guess.

Currently we have solved this problem by using urxvt's name option. If there is an application (which runs outside the terminal)  which changes it's title frequently, and if I need to have a binding to focus on that, the problem still stands. Not a problem one I have right now, but it would be nice to solve it preemptively :)

**Comment by stapelberg** [comment]
I think if there are applications which neither set their class, nor instance, nor title to something useful for matching, that problem should be fixed upstream (i.e. in the app) since it affects all window managers and plenty of features.

AIUI, the motivating use-case for this feature request has gone away, and I’m going to close it. In case a use-case comes up which requires this feature, please reopen and state it, and we can reconsider adding it to i3.

**Comment by ma08** [comment]
Fair enough. Thanks for all the help and discussion :)
