### ISSUE TITLE
[feature-request] Per-window decoration colors and dynamic color changing.

### ISSUE THREAD

**Issue by setzer22** [i3/i3#1879]
I'd like to propose a new feature which I think can have some uses in aesthetic desktop customisation with i3. 

The feature consists of allowing the user to define the color of an individual window's decorations with a command. The windows would still get the default color from the one defined in the i3 config file.

I think this is a good idea because it allows for more flexibility and customisation. To give some examples, users would be able to highlight important windows in a different fashion for easily spotting or have each workspace with a different background and according window colors.

As for the implementation details, the first thing that comes to mind is that every window would have to carry some new color data. I'm not familiar with how much data a window node stores, but I don't think the extra color information wouldn't be much of an overhead. It would be either the size of a bunch of integers or a pointer.

Finally, I'd like to say that despite this is labelled as a feature request I'm willing to implement this feature myself, but I'd like to know whether a feature like this could get merged with i3 first.

**Comment by Airblader** [comment]
Note that windows which become "important" should set the urgency flag, which already is a customizable color in i3.

Other than that I'd like this change, but I can really only think of this as an eyecandy kind of thing which usually isn't our focus.

**Comment by teto** [comment]
IMO it's more then eye candy and brings ergonomic benefit: in a stack layout it is easy to read window titles but in tab layout, it can be hard to distinguish between the beginning and the end of a tab.
I've been enjoying the colortabs plugin on firefox or even the vivaldi webbrowser whose tab color takes the dominant color of the page (not sure but facebook is blue so :d ) and I dare say that looking at a color is faster than reading the title once there is a pattern to the color.
This may look is an unusual feature request and I would understand if this gets discarded but I think it requires consideration.
What could serve as a poc is to play with a pango font to color titles, thus people could see if it helps.

**Comment by setzer22** [comment]
@teto The idea for dynamic color changing also came to me after seeing Vivaldi's tab adapting to page color feature. I think you're right that there's an ergonomic benefit to it.

@Airblader I think the urgent flag works more like a way to display notifications by bringing the user's attention at a given point, or at least most programs use it like that. What I was trying to say by highlighting important windows was having a permanent highlight that lets the user distinguish important windows. 

On the lines of the "Highlighting important windows" thing and as another example of why this might be useful apart from "eyecandy" purposes, let's imagine a user that has a multi-monitor setup with many terminals open in it —And I think this is not an unusual case in i3—. Some of those terminals are ssh sessions to other machines while others might be a tty in his own machine. Having a way to highlight with a different color the ssh sessions not only would allow for easy spotting and telling terminals apart from each other, but would also help avoiding some mistakes that executing a command on the wrong machine wolud create. For this case, a for_window rule involving the window title would suffice in most setups. 

So, I think there's some potential on this feature besides the aesthetic ones.

**Comment by stapelberg** [comment]
> Some of those terminals are ssh sessions to other machines while others might be a tty in his own machine. Having a way to highlight with a different color the ssh sessions not only would allow for easy spotting and telling terminals apart from each other,

Personally, I just have the hostname in the window title and a differently colored prompt for the hosts. That way, you have a visual cue that is closer to where you are actually looking at (prompt).

Regardless of this specific use-case, I’m on the fence about this suggestion.

I see that using different colors can in general improve ergonomics, but I’m doubtful as to whether this feature is generic enough to make sense to put into i3.

Could you maybe create a few mock-up screenshots with example use-cases, so that we get a better feeling of this feature?

**Comment by setzer22** [comment]
I've made a couple of screenshots as a proof of concept, even though I'm quite bad at colors...

First I used basic i3 with nearly default config, in this screenshot you can see how windows 3 and 6 are ssh sessions to a remote machine and are colored in green and remaining windows 1, 2, 4, 5, and 6 are highlighted in yellow, while having different colors for focused, active and inactive. I think it makes remote windows quite distinguishable, even when they are in tabs. The easy tabs distinguishing is an improvement over what @stapelberg just said, because you can't identify a hidden tab window for it's contents, and the other only way of identifying it is by reading the title. I don't think it's subjective that is faster to identify a color than to read a window title where all tabs have the same color.

![i3_screenshot_yes_colors](https://cloud.githubusercontent.com/assets/7241990/9601630/29c47cd8-50a3-11e5-9b69-774f66fdfcef.png)

Now, with a more "eye-candy" setup, and with some configuration (that goes on the user) I experimented with what would happen if the window borders adapted to window content in a typical browsing workspace. As you can see it's surprisingly easy to spot the "Facebook" tab, or at least it's for me, and IMO (even though it's quite subjective) there's an aesthetic benefit to it. 

I don't think there's room for a generic implementation of this "adapting color to window contents"  feature, but each user can make small configurations with rules to adapt to his own setup.

PD: Don't hate me for wasting my precious screen space with those gaps :P 

![i3_screenshot2_yes_colors](https://cloud.githubusercontent.com/assets/7241990/9601638/33103ee4-50a3-11e5-937d-fe0d7b6c2adf.png)

If you need more, I'll think of more useful cases and make some more fake screenshots. I understand this feature might not please everybody, but if unused it will not affect the user in any way. Also, i3 already allows the user to define some per-window "cosmetic" settings like the border width, so I don't feel like it would be incoherent to allow for this.

**Comment by Airblader** [comment]
I really like the adaption to the content, but agree that this is very unlikely to be adopted in i3. :) I defnitely do favor the idea of per-window border colors.

(I most certainly won't hate you for gaps *cough*)

**Comment by teto** [comment]
[quote]
I really like the adaption to the content, but agree that this is very unlikely to be adopted in i3. :+1: 
[/quote]
I am not even sure that's how vivaldi works, I mean facebook/google page is mostly blank but IIRC their tabs were blue. So maybe it is a preset or based on the favicon. Well that was more a joke than a real proposition :)

Apparently we agree that color can help (either in prompt or titlebars) so the next question might be "how to color in a helpful way."
For instance in your first screenshot, the color helps distinguishing between the titles but having every tab colored also perturb the reading (too much color for me :D ). My usage would be more like: by default leave windows as is and color just some specific tabs. 
For instance I open several (neo)vim instances (on a per project basis) in a stack of 8 windows. Finding the wanted vim instances takes some time even when setting titlestring. Having a color code could speed up that.
Once again, using pango fonts and the for_title directive to color differently the title could achieve the same ? (except if you hide titlebars)

**Comment by setzer22** [comment]
@teto I just was trying to show some possible uses, the default behaviour would be just as you stated, and any further setup is up to the user. By default all windows should obey to the main theme specified in i3-config, and then commands should be provided, something like "set_color client.focused #00ff00" (I'm not proposing any commands or syntax yet, just an examlpe) which can then be used either by i3-msg or whithin i3's config file with a for_window rule, hotkey or whatever.

It's true that using coloured fonts can sometimes achieve the same effect, but as you suggested this only works when the window title is displayed and not all i3 users like to display window's titles. 

Besides that, even if the font color would achieve the same effect as coloring the whole window titlebar I think being able to set the color for the whole border as well has a greater visual impact if that's what the user is looking for. And, because of per-window colors would also allow to set the text tile color alone, this would allow colored title text with any font not just pango fonts. 

I see this it as a more complete feature, than just colored titles with pango fonts, but overall it looks simple enough to be included in i3 to me.

**Comment by Airblader** [comment]
I've created a quick hack to make this work. If anyone wants to play around with it, either

* use [this branch](https://github.com/Airblader/i3-original/tree/feature-1879) or
* get the patch from [here](http://pastebin.com/D26TUEfF) and apply it on `next`.

(Fair warning: I've ran it on my machine, but you should still not necessarily count on i3 not crashing, even if I doubt it will)

It introduces the same syntax as for the config, but as a command (which isn't necessarily what we want to go for). So you can do somethig like

    i3-msg "client.focused #ff0000 #ff0000 #ff0000 #ff0000"

And yes, this means it'll only be applies to the currently focused window and only for its focused state.

The patch is pretty ugly in the essential part, so an actual solution would have to be done a bit cleaner. I think it also shows that tabbed and stacked containers need some thought.

**Comment by teto** [comment]
ingo you are crazy :D
It works here. with a binding and i3-input to input the color, one should
be able to take some nice screenshots.

**Comment by setzer22** [comment]
@Airblader I see what you mean by tabbed and stacked containers, the tab should be drawn not in the focused window's colors but in the colors of the window in each tab, right?

I'd really like to contribute on this, for now I've been taking a look on x.c and data.h in the original i3 to see how things work and the patch's changes.

Regarding that "suuuuuuper ugly" snippet, maybe this is a sign containers should be flagged as colored, and then this would allow for something like:

    client_colors* colors_source = con->is_colored ? con->colors : &config.client
    //The if-else-if chain is like before using colors_source instead of &config.client

Of course, to make this work, the default colors would need to be all copied once a container is marked as colored. Doesn't seem much of a problem, apart from the subtle change that if default colors were to be changed at runtime, the colored window wouldn't notice (I don't know if that's even possible though).

Oh, and by the way, to all the team, I've just found out i3 is not only good on the outside, but also on the inside. Very clear and well-documented code! :+1:

**Comment by Airblader** [comment]
> Did that "make install" install any files that a normal i3 installation wouldn't? 

It shouldn't (though it of course depends on the distribution's package). I use Arch repositories as well and I overwrite my installation like ten times a today, so you should be fine.

I'll comment on the rest later.

**Comment by setzer22** [comment]
@Airblader Good to know! Everything seemed fine but it's better to ask.

Also note that I edited my last post because I got confused.

**Comment by setzer22** [comment]
@Airblader I just pull-requested your feature-1879 branch with the changes I suggested. Maybe it was an overkill to fork your whole repo but I didn't know of any better way. 

The changes can be reviewed here: https://github.com/Airblader/i3-original/pull/1/files

**Comment by Airblader** [comment]
Before we actually implement this I think we should define the API and the exact behavior.

## API

Should we use the same syntax as for the configuration? Should it be possible to define only the border color or should the user always set all colors (as with the configuration)? Should we offer all colorclasses as well?

## Behavior

Consider the pictures below. In the stacking case, it seems odd that the red on the left edge is interrupted on top because of the bottom tab, doesn't it? And in the tabbed case, I think the red should be visible as a red line between the window and the tabs as well to make it feel like actual tabs. So the drawing would have to be improved here. I'm not sure how complicated this is, but I suspect it quite be quite substantial.

![screenshot-2015-09-02_21-52-02](https://cloud.githubusercontent.com/assets/2392216/9642573/2a28d1c2-51bd-11e5-973c-1c0856f3be0b.png)
![screenshot-2015-09-02_21-52-07](https://cloud.githubusercontent.com/assets/2392216/9642572/2a28c3b2-51bd-11e5-91a1-3307eda922b7.png)

**Comment by teto** [comment]
If I understand correctly your remark this is independant from the PR. It may have surprised me at first but I got used to it and this is not a problem for me since the focused titlebar is quite visible. For the implementer sake, I would say keep it simple.

I would vote for being able to set color.unfocused since I see colors as a way to identify unfocused windows faster. Being able to change focused/urgent/background colors would a contrario slow my reaction time.

**Comment by Airblader** [comment]
Actually, this is even worse than I anticipated: imagine a tabbed container with two windows. You set the first window to have a green border (both focused and unfocused) and the other one to have a blue border (both focused and unfocused). You focus the first window. Should the border around the entire thing now be green or blue?

Maybe one solution, which would, I think, also make the implementation drastically more simple, is that for stacked and tabbed containers we only color the tab marker, but not the border around the window. This would also be OK because tabbed and stacked containers always have a titlebar, even if you disable them.

As for the API, I think I agree that focused and unfocused are definitely required. Urgent and background are probably not needed (at least for now), the usecase seems very limited. We would still have to decide over focused_inactive.

I think I'd like it if the arguments for a colorclass (border, background, text, indicator) were all optional. To still know which one the user wants to set, we could allow passing "-" as an argument to mean "no change" (or something else, "-" is just an example). So all of these would be OK:

    client.focused #ff0000
    client.focused - #ff0000 - #ff0000

What do you guys think?

**Comment by teto** [comment]
In your example, I would vote for setting the border to the focused color of the focused window so green. Maybe I am missing the point, I don't see the problem here xD If the container loses focus, then set it to the color.unfocused of the last focused window of that container.

"focused_inactive" is the color used when another window gets urgent ? looks minor to me, could be ignored.

"we only color the tab marker" => that would be totally fine for me and enough to test the ergonomics part (maybe not the aesthetic one). If the need arises to draw borders as well, it may be enhanced after.

**Comment by Airblader** [comment]
I think I'd prefer going with only doing the tab itself and explore a PR for this and see if it can be extended afterwards.

What did you think about my API proposals? It'd be good to hear what @stapelberg says about that as well (the API alone is independent of what it'll look like).

**Comment by setzer22** [comment]
@teto I don't see any potential gain in disabling the feature for some color classes, e.g. allowing to only change the unfocused color. I agree on all your points, but I don't think we should limit the feature, the user should be free to use it as he/she sees fit. If it would introduce implementation difficulties I'd get it, but being as simple as a copy paste, I don't see why all color classes shouldn't be allowed.

@Airblader Your API looks fine to me. Using "-" to leave the color unspecified seems like a good idea. 

It also came to mind that the command could accept an optional window-id parameter, but now that I think about it I don't see much use for it. By setting the currently focused window and using a for_window rule most use cases are fully covered. I'm just mentioning it to see if anyone finds any legit use to this

[quote]Actually, this is even worse than I anticipated: imagine a tabbed container with two windows. You set the first window to have a green border (both focused and unfocused) and the other one to have a blue border (both focused and unfocused). You focus the first window. Should the border around the entire thing now be green or blue?[/quote]

I'd say the focused border has to be painted, that's the logical behaviour to me.

**Comment by stapelberg** [comment]
It appears to me that we’ve converged on just changing the title bar background color (and that seems most useful in tabbed containers) being the most useful part of this feature.

I think this is very similar to using e.g. `title_format <span background="#ff0000">%title</span>`

I’m inclined to say that we shouldn’t add another command and just use `title_format` with colors.

**Comment by marion06** [comment]
I would like to add one more argument to why this feature definetly should be added:
I am trying to save as much space as possible, so i set up 1px border. Since most my windows have dark background, i have set border to be green when window is selected. Below you can see emacs window, to the right, selected. (perhaps you should zoom the image to see it, since it is only 1px wide)
![2015-09-12 23 59 32_1920x1080](https://cloud.githubusercontent.com/assets/12964933/9834020/22237c20-59ab-11e5-8d09-a6c32bf1d6e9.png)
But some windows are inevitably light, like Qtorrent to the left. For some reason i could not change its style, not even with GTK themes, to be dark. As you can se below, green border around it's grey edges is barely visible. It's even worse around web browser with white backgrounded pages (which is most pages on the web).
![2015-09-12 23 59 36_1920x1080](https://cloud.githubusercontent.com/assets/12964933/9834042/5a0bac98-59ab-11e5-828d-ee5a87bce933.png)
I would like to be able to set different border color to those windows that are light, so that the border is more visible. And that is why this feature would come in very handy.
All the best !

**Comment by stapelberg** [comment]
> But some windows are inevitably light, like Qtorrent to the left. For some reason i could not change its style, not even with GTK themes, to be dark.

Qtorrent is likely built with Qt (looking at its name), so GTK themes won’t do anything. Try Qt themes? :)

> I would like to be able to set different border color to those windows that are light, so that the border is more visible.

Another option would be to use a 2px border, or a different border color that works well with light _and_ dark windows.

**Comment by Airblader** [comment]
As a user I still very much like the idea of window-specific colors (and I do mean including border). From a contributor perspective, I'm having issues with the syntax. It feels like the syntax for this should be simple which reusing the config syntax definitely isn't.

**Comment by stapelberg** [comment]
I’m not convinced the use-case is strong enough.

I think i3 already offers plenty of ways to customize how windows can be arranged/organized. Given that reasonable alternatives to this feature request are using colors and/or keywords with the existing `title_format` command, I think it boils down to a matter of personal preference.

To me, the cost of adding a new command does not outweigh the benefit it introduces here. See also https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/

**Comment by Hacksaurus** [comment]
I know this is a REALLY old issue, but I really want to able to change colors of borders dynamically... I do have a use-case that you might consider. I have another issue here: https://github.com/i3/i3/issues/2819 and you can see that whenever a new window is focused a border is added and then quickly removed, but every time it does this it sort of "resizes" the window, not making it so elegant... If I was able to have border color be able to be changed dynamically this wouldn't be much of a problem... I hope you reconsider this case!

**Comment by stapelberg** [comment]
Please refer to the `title_format` description in the userguide: https://i3wm.org/docs/userguide.html#pango_markup

The last example is:
```
# print window titles of firefox windows red
for_window [class="(?i)firefox"] title_format "<span foreground='red'>%title</span>"
```
Refer to the referenced [pango markup](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html) description to see all span attributes, including the background attribute.

**Comment by ison111** [comment]
I think this could be extremely useful for indicating more window modes than are currently easy to distinguish in i3.

For example I have a hard time noticing if a new window will go to the right of an existing container or be dropped down on top of it in tabbed mode. Because the only visual difference between a normal window and one that represents a tabbed container is a 1px border around the title bar.

This would be even more useful with the "pixel" border style which has no titlebars, because then a single window tabbed container is completely indistinguishable from a normal window.
Another issue with the "pixel" style which could be solved by more styling options is that it's possible to have a window that's accidentally become several containers deep and you'd never know it. Until you try to move the window around and notice that you have to move it 5 or 6 times before anything happens. So in addition to adding separate styles for tabbed mode it could also be very useful to add an option to set some style option for alerting the user when a single container is itself embedded in several single containers.
