### ISSUE TITLE
[enhancement] persistent workspaces

### ISSUE THREAD

**Issue by spudowiar** [i3/i3#1902]
I suggest adding two configuration options `close_workspaces_when_empty` and `close_workspaces_only_when_unbound`. `close_workspaces_when_empty` could be set to `false` in order to persist workspaces after the last client is closed and `close_workspaces_only_when_unbound`  would only close workspaces that are not bound to a key.

The patch is already written.

Thanks in advance.

**Comment by Airblader** [comment]
This has been requested in the path. We're not going to do this. The workspace concept of i3 is exactly to not keep workspaces open when they're empty. 

See https://faq.i3wm.org/question/1228/lock-workspace-to-permanent/

**Comment by DoTheEvo** [comment]
Still no change in mind, or at least taking pity on people who need it and recommend some hacky solution?

I can provide quite reasonable argumentation  if desired, why its extremely useful functionality on multimonitor setups with people who use mouse and are not keyboard navigation purist.

**Comment by Airblader** [comment]
> or at least taking pity on people who need it and recommend some hacky unofficial solution?

This is an open-source project; you can always patch this into the code yourself. In fact a patch circulates somewhere and @ghost also said he has a patch already.

> I can provide quite reasonable argumentation if desired, why it would be extremely useful functionality

You're welcome to argue for a feature and we will discuss those arguments, provided they bring something new to the table. We are always open to change our mind given good enough reasons; but there's more to consider than just usefulness of a feature.

> what issues would it fix, on multimonitor setups with people who use mouse and are not keyboard navigation purist

You can also discuss the problems you are having and we can see whether there isn't already a way to deal with those problems; more often than not this is the case.

**Comment by DoTheEvo** [comment]
>You're welcome to argue for a feature and we will discuss those arguments, provided they bring something new to the table.

All right. Lets do this.

in essence it boils down to two points

1. expected position and order of workspaces on the i3bar
2. ease of use, reducing the number of actions required in certain situations if using mostly mouse

----------

Example from my personal situation

- dual monitor setup, main large monitor, small one on the side
- 3 main workspaces that open on boot on the main monitor
     - 1 |browser
     - 2 |file manager
     - 3 |text editor
- I work on something in text editor, I have relevant stuff in the browser and I would like to move browser on the second monitor
- with a hotkey thats also binded to mouse side button I send the browser to the second monitor
`move container to output left`
- **this is where issues 1 starts**
- browser workspace collapses as I switch to my text editor workspace and browser workspace is left empty
- workspaces in the bar move one space the left, losing major benefit of being accustom to their order and position, expecting without reading that when I click second workspace its file manager, not something different
- Considering I could work like that for hours its quite inconvenience to have this sudden change in the bar. If you remember taskbars in windows 7 and alike, its as if someone would reorder your pinned stuff on some occasions
- its enough of an inconvenience that I rather open terminal in that workspace when I am leaving to keep the order as expected, but every time I do this I am cursing under my breath

-----------------

- **this is where issues 2 starts**
- I am done with the editor and want to get back my browser to the main screen to its native workspace
- if workspaces could be persistent this action would consist of clicking workspace I want to get to in the bar, moving mouse to the other monitor and sending the application with **the same hotkey** to the other monitor. Simple.
- current situation is bit different, its not a big problem if you are a heavy keyboard user with home row in your fingertips. You just send it with shift+win+1 where you need to. Opening new workspace in the process.  But since it can be a different workspace(virtual machine, image editor,...) it requires thinking and selecting correct number and always requires use of keyboard.
- clicking side button on mouse is bit easier than acrobatic win+shift+6 hotkey....
- even heavy keyboard users might appreciate not needing to deal with numbers if their main workspaces are pinned and can be cycled through

--------------

That write up illustrates my core problem, as I said the expected position and order of workspaces in the bar, and requirement to use the keyboard to open correct workspace that closed on me

--------

I tried to write as simple and to the point

it gets more complicated when I mention that on second monitor I have also workspaces open on boot with music player and notetaking application. While 80% of the time on the second monitor theres empty workspace with conky in override mode showing stats of my PC, weather and google calendar.

As its considered empty(conky is ignored) I can easily send there applications there without having to tile and share real estate. This of course gets ugly when I actually need to go to my music/note application, as that collapses my main empty conky workspace and we are back to being bothered by manually re-creating workspace when I am done with the notes for example.

**Comment by Airblader** [comment]
Sorry for the late response, I'm rather busy lately. Thanks for your detailed description!

> browser workspace collapses as I switch to my text editor workspace and browser workspace is left empty

I'm not sure I entirely understand. The command you mentioned will not collapse the browser workspace, it will still remain on the same output and be empty. We only destroy workspaces if they are empty _and_ they are not the active workspace on an output.

You can also move the entire workspace to the secondary output, by the way. In this case the primary output will indeed show a different workspace afterwards.

> workspaces in the bar move one space the left,

This situation should not change anything in the i3bar other than focus. If the secondary output was active before, it also had a workspace already, thus the workspaces are exactly as before and therefore the order hasn't changed.

> clicking side button on mouse is bit easier than acrobatic win+shift+6 hotkey....

In the average situation you will still need to to some acrobatics. The reason being: if on your primary output you are now in the editor workspace, you first need to focus the (persisten) browser workspace and then move the window from the secondary to the primary output. And, in fact, exactly this you could even do now already, just that the workspace wasn't persistent but is created again. So I'm not really seeing what problem persistent workspaces would be solving here. Yes, in this situation i3bar will change slightly because one workspace disappears in the meantime, but other than that I'm not seeing any real difference.

**Comment by DoTheEvo** [comment]
>We only destroy workspaces if they are empty and they are not the active workspace on an output

yes, and thats what I tried to describe clumsily. Workspace that had browser in it was left empty, and I switched to editor workspace. The empty browser workspace is gone the moment editor appears on my screen.

>You can also move the entire workspace to the secondary output, by the way. In this case the primary output will indeed show a different workspace afterwards.

Yes. I did try that some time ago and at first it really seemed like a perfect solution to some problems I described. But its really not.
Sending an application under your mouse cursor to another output is much more universal and useful than whole workspace.

I open calculator app thats floating. Do some calculations on the main monitor and then with results I want it still around while working on the main monitor, so I send it to secondary. And in this case I would be sending whole workspace.

Though I use workspaces as containers with single purpose(browser, file manager,..) I still frequently open terminals in whichever workspace I am, write something and then send it on another monitor awaiting finishing executions...

>This situation should not change anything in the i3bar other than focus. If the secondary output was active before, it also had a workspace already, thus the workspaces are exactly as before and therefore the order hasn't changed.

Trust me it does. I just described whole actions poorly I guess.

I tried again in few paragraphs above


>In the average situation you will still need to to some acrobatics. The reason being: if on your primary output you are now in the editor workspace, you first need to focus the (persistent) browser workspace and then move the window from the secondary to the primary output.

well, in my personal workflow if persistent workspaces option would exists, this action would consist of me absentmindedly left-clicking the empty persistent workspace with the mouse, moving the cursor to the other monitor, and clicking the side mouse button to send the application to its home workspaces.

It would be so easy and so universal.

No long finger reaching keyboard acrobatics 3 hotkeys combo, no thinking about correct number, it would be muscle memory within days.

What you are saying is true for heavy keyboard users which I think most of i3wm users are.

Since the main required action is sending focused application to X workspace it does not matter if it exists or not as it gets created in the process.

But that being said, even keyboard users would benefit if they would choose to.

Because the action still requires thinking and choosing of correct number. While with persistent workspaces the action could be reduced to universal hotkeys - cycling through opened workspaces until desirable ones are opened and then sending application to the other one.

Its kinda like difference between pressing repeatedly PgDown key to get somewhere in your file, instead of writing out command "go-to-line 72" which gets you precisely what you want but feels like it requires more of you. And if you navigate around your file a lot, writing out go-to \#precise_line_number becomes big annoying. Though its probably not that great example as you usually dont know line you want...

**Comment by Airblader** [comment]
> no thinking about correct number

> Because the action still requires thinking and choosing of correct number.

I would argue that in general users take one of two approaches to workspaces:
* They dedicate specific workspaces to specific programs (which is my personal approach). In this case it quickly becomes muscle memory to know which number to choose and there is no more thinking involved.
* They use workspaces freely as they go. In this case it doesn't really matter which workspace they choose anyway.

But that's just a side comment.

> cycling through opened workspaces until desirable ones are opened and then sending application to the other one.

To cycle through a fixed list of workspaces (rather than existing ones) is totally possible with i3 today; it just requires minimal scripting and lots of users have done this already. So there is, effectively, no new argument here.

The only other thing you mentioned is clicking on that workspace in the bar rather than cycling. But again, you don't really want persistent workspaces, but a fixed list of workspaces in your bar. In that case I suggest just using something other than i3bar (which follows the i3 concept of workspaces on-the-fly). If you display buttons for a fixed list of workspaces you can have a click on it open the appropriate workspace and you will have everything you need.

Actually persistent workspaces come with a rat tail of issues like a hard configuration of a list of workspaces, how to close workspaces afterall etc. From your description it seems like we don't need to look into this because those problems can actually be solved in a different way.

**Comment by DoTheEvo** [comment]
>They dedicate specific workspaces to specific programs (which is my personal approach). In this case it quickly becomes muscle memory to know which number to choose and there is no more thinking involved.

Well Ive been using i3 for several years, been dealing with this quite some time, and I still have to check where my fingers are going and what exactly I am doing. Though most annoying is the need to go for keyboard when I otherwise would not be using it.

>To cycle through a fixed list of workspaces (rather than existing ones) is totally possible with i3 today

Well thats not really the same, not at all I think. Should a user have to put there all workspaces and have the nonexisting ones popup as the cycling goes? Or should some of them be skipped despite being on screen, but not being in some fixed list?

>The only other thing you mentioned is clicking on that workspace in the bar rather than cycling. But again, you don't really want persistent workspaces, but a fixed list of workspaces in your bar. 

well, not entirely fixed as wanting 3 persistent workspaces does not mean I want all the possible numbers, or inability to spawn more...

>In that case I suggest just using something other than i3bar (which follows the i3 concept of workspaces on-the-fly). If you display buttons for a fixed list of workspaces you can have a click on it open the appropriate workspace and you will have everything you need.

Well, ok, but does it exists?

>Actually persistent workspaces come with a rat tail of issues like a hard configuration of a list of workspaces, how to close workspaces afterall etc

well, to give insultingly amateurish idea of it. Shouldnt it be just about relatively simple check on lose of focus, or whatever it is that triggers event for initiation of closing empty workspaces, against array of workspaces in the config or against an attribute?

we have stuff like this, so we obviously already have some "hard configuration of a list of workspaces"

* `workspace 1 output DVI-1`
* `workspace 2 output DVI-1`
* `workspace 3 output DVI-0`
* `set $WS1 1:| FRONT |`
* `set $WS2 2:| FILEMANAGER |`
* `set $WS3 3:| EDITOR |`

so why not

* `workspace 1 persistent yes`
or
* `persistent_workspaces = $WS1 $WS2 $WS3`

And as for "how to close workspaces afterall ", I dont think there should be any concern with it. Dont. When user sets `workspace_layout tabbed` theres also not concern how to do tilling in that case.

This feels like it should be on much much easier difficulty/maintainability scale than many other things that had been done in i3

**Comment by Airblader** [comment]
My proposed way forward is to implement this in i3-gaps where I'm a bit more willing to experiment with this. The feature request there exists already as well.

Please send a proper PR against i3-gaps, let's try it out there and after some experience we can choose from these options:

* Keep it in i3-gaps, but not in i3.
* Also move it into i3.
* Remove it from both because it turns out to cause problems

**Comment by DoTheEvo** [comment]
>Please send a proper PR against i3-gaps

well, problem is I dunno C or i3 to make an actual proper pull request

**Comment by Airblader** [comment]
I can wait. :-)

**Comment by Oglo12** [comment]
> This has been requested in the path. We're not going to do this. The workspace concept of i3 is exactly to not keep workspaces open when they're empty.
> 
> See https://faq.i3wm.org/question/1228/lock-workspace-to-permanent/

Can you really not add some opt-in way? Like an option the user has to add at the very least? I do find it annoying not having a neat row in a numbered order. It is also very confusing!

**Comment by Airblader** [comment]
#4311 will allow you to do this now.
