### ISSUE TITLE
[enhancement] New type of layout

### ISSUE THREAD

**Issue by jvalencia80** [i3/i3#1977]
I've been fiddling with the stacked layout, but as I told Airbladder, dynamically reducing my screen size is not practical. 

Stacked layout has the merit of showing all your windows titles in a small area, written like a paragraph, so it's very natural to look at.

The problem is, well, that it stacks and gets bigger and bigger.

So I'm proposing this new type of layout that keeps screen size constant while stacking the titlebars. 

![prototype](https://cloud.githubusercontent.com/assets/456311/10263175/62ced478-69db-11e5-8c9b-6b9755fda9b9.jpg)

Compare it with a normal stacked layout:

![stacked](https://cloud.githubusercontent.com/assets/456311/10263179/75e73622-69db-11e5-9327-dc6048a7abf8.jpg)

Large titles would be cropped like this:

* *source:* "i3 - improved tiling wm - Mozilla Firefox"
* *result:* "i3 - improved tiling wm - Moz..."

I think this layout is great for wider screens.

I don't expect this to be implemented since it's complicated, but I just wanted to register the idea for the future ;)

**Comment by icflournoy** [comment]
While I don't use the stacked layout that often, I do like your approach to having window titles live on the side. I personally use [Tree Style Tabs](https://addons.mozilla.org/en-us/firefox/addon/tree-style-tab/) for Firefox to achieve the same effect on a large center screen.

**Comment by Airblader** [comment]
> I don't expect this to be implemented since it's complicated

I don't think the implementation is that hard, certainly not a reason not to go for it. My concerns were others, mostly whether this is different enough from tabbed layout to justify a new layout and also the problem of truncated text.

Other issues include defining how much of the width should be taken up by the "tabs" and how to deal with the situation of running out of space for more tabs, though that is already an issue with stacked layout.

**Comment by jvalencia80** [comment]
Interesting, that firefox addon has 105.914 users, so it's not that bad!. The layout might work after all. I'm going to try it for a few days.

Airblader, now that I see it, it's more a "vertical tabbed" layout than other thing. The problem with normal tabbed layout is that for wider screens (or screen bigger than 22 inches) you have to look continuosly from edge to edge of your screen to see your open windows, while with the vertical tabs you only have to look at one edge to see them all.

Don't know if that alone is enough for a new layout though as you said.

**Comment by Airblader** [comment]
> Interesting, that firefox addon has 105.914 users, so it's not that bad!

Yeah, I know a lot of people who use this as well and it's the only reason I'm still a bit undecided about this (though @stapelberg will actually make the decision anyway). Though the question about the size still stands because I don't think we'd want to go for making it resizable.

> The layout might work after all. I'm going to try it for a few days.

Did you already implement this new layout? I figured your screenshot was just a mockup.

**Comment by jvalencia80** [comment]
> Did you already implement this new layout? I figured your screenshot was just a mockup.

No, it's just a mockup. I meant the firefox addon. Already trying it. The autohide option is interesting too.

**Comment by stapelberg** [comment]
I agree that your mockup uses the available screen space more efficiently in your situation (i.e. with your screen resolution).

I also share @Airblader’s concern about the width of the titles being something that would likely need to be configurable.

In general, I’m leaning towards the decision that this suggestion is too similar to the tabbed layouts we already have and hence not worth the addition.

**Comment by jvalencia80** [comment]
Yeah, I knew this was probably what would happen with the idea. Maybe one day it has enough user support for it.

Thanks guys and keep up the good work.

**Comment by teto** [comment]
As an easier workaround you could try hiding the stack after a timeout and
display it again on $mod press, like for i3bar though that may stay an out
of stree patch.

2015-10-05 12:58 GMT+02:00 Javier <notifications@github.com>:

**Comment by teto** [comment]
In my setup I only have Neovim and firefox that handles their tabs themselves. I managed to get vim splits work flawlessly with i3 bindings through neovim rpc system and now I am looking at ditching firefox tabs.
 I do like my tabs vertical and just wrote a quick hack to see how hard it would be to write
https://github.com/teto/i3/tree/vertical

As you can see on this screenshot https://transfer.sh/eum7O/2016-01-17-225010-1920x1080-scrot.png
I've 2 problems:
-the top border is not drawn.
-while taking the screenshot I realized the focus was not good (clicking on url bar would select the parent container it seems)
I wonder if these two can be fixed from within the render_con_sidestacked function or if I should modify others ? (to have a feeling if I could maintain this).

**Comment by MogeiWang** [comment]
This feature is so cool, please do consider to implement it. Thx

1. The stacking layout is very different with the tabbed layout in that, title bars are listed in different directions. For stacking layout, title bars are listed vertically; while for tabbed layout, title bars are listed horizontally. This simple fact implies that, very different results will be obtained by pressing `Mod-Shift-Left/Right` or `Mod-Shift-Up/Down`.
It is true that, the stacking layout can be regarded as a transposed tabbed layout, or vv. But such a fact does not really help, since English texts is printed horizontally in most applications.

1. This layout would be very helpful.
In fact, I hoped to have such a layout even in those days of using wmii.

1. I do not really care about the width of title bars, but it would be perfect if the width can be configured. 
Additionally, it is also acceptable if texts in title bars are printed vertically in the new layout, and each character is transposed.


Previously posted in sway issues 622.
