### ISSUE TITLE
enhancement: implement not focusing windows when _NET_WM_USER_TIME == 0

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#2064]
From http://standards.freedesktop.org/wm-spec/latest/ar01s05.html:

> The special value of zero on a newly mapped window can be used to request that the window not be initially focused when it is mapped.

Applications such as Chrome use this hint that way: https://code.google.com/p/chromium/codesearch#chromium/src/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc (line 1672)

**Comment by Airblader** [comment]
I'll prepare a PR for this. It should be fairly straight-forward and I can use a break from the i3 to cairo work. =D

**Comment by Airblader** [comment]
Out of curiosity, do you happen to know a usecase in Chrome where this will be used?

**Comment by stapelberg** [comment]
During a quick look within Chrome, I couldn’t find a code path which leads to a managed (!) window with `_NET_WM_USER_TIME == 0`.

However, it looks like konqueror uses `_NET_WM_USER_TIME == 0`:

https://sources.debian.net/src/kde-baseapps/4:15.08.2-1/konqueror/src/konqmainwindow.cpp/?hl=1417#L1417

**Comment by Airblader** [comment]
The Konqueror usecase seems like it wouldn't affect i3 very much either since the window is either tiled and hence doesn't overlap any other window, or it is floating and would then float above the tiled window anyway.

But the change is fairly simple anyway and it shouldn't hurt to support the spec correctly here.
