### ISSUE TITLE
[enhancement] Implicit variables 

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2130]
i3 is a pure X window manager, but currently makes no use of the xrdb. This forces users to duplicate configuration that you'd typically want to be consistent by having it in one place. 

I propose introducing implicit variables into the i3 config. To start off easy, I'd limit this to the definition of colors. When i3 reads the config file, it queries the color definitions from xrdb and creates variables `$color0` and so on implicitly. If the user defines this variables themselves, the specific configuration wins.

**Comment by stapelberg** [comment]
Can you give an example of what I’d put into my ~/.Xresources and what would happen in i3 please?

**Comment by Airblader** [comment]
The `~/.Xresources` contains

````
*color0: #000000
*color1: #111111
! And so on…
```

And in i3 I can simply do

````
client.focused $color0 $color1 $color0 $color1
```

without having to define these variables myself (they are defined implicitly). For that, i3 would query xrdb for something like `i3wm.color0`, which should return the defined color as it used a placeholder.

**Comment by Airblader** [comment]
Introducing a dependency to xrdb would also allow us to use the DPI from the `.Xresources`.

**Comment by stapelberg** [comment]
I’m wondering if we should use a variable prefix for this, e.g. `$xrdb:i3wm.color0`. That way, we don’t need to dictate how the variables should be called, and people are free to re-use the variables they’ve set up for other programs. I.e., one user might prefer using `$xrdb:xterm.color0`, others might prefer `$xrdb:i3wm.white`, etc.

Thoughts?

**Comment by Airblader** [comment]
I don't mind doing it that way, but to me it sounds like it sort of goes against the idea of xrdb which is that an application requests its own resources, not that of other applications. Wildcards are allowed on the configuration side (and only there) to make configuration valid for multiple applications in an easy way.

I think the usecase you describe is usually handled by "variables" within Xresources (`#define`).

**Comment by stapelberg** [comment]
I’m not that familiar with xrdb (only a casual user), so if you accurately described the spirit of xrdb, we clearly should follow that, especially when users can just use `#define` within Xresources :).

**Comment by Airblader** [comment]
@stapelberg This requires `X11/Xresources.h`. I can't seem to be able to find an XCB equivalent. Is this OK? Is libx11 a new dependency for us?

**Comment by stapelberg** [comment]
I think you’re right in that there isn’t an xcb equivalent:

In https://sources.debian.net/src/xcb-util-cursor/0.1.1-3/cursor/cursor.c/?hl=95#L44, we parse the RESOURCE_MANAGER property contents directly in an ad-hoc fashion.

cairo-xcb does the same: https://sources.debian.net/src/cairo/1.14.6-1/src/cairo-xcb-resources.c/?hl=232#L232

This seems like a good chance to write a library for xcb (like I wrote xcb-cursor a couple years ago), to be used by i3, cairo and others :). See http://cgit.freedesktop.org/xcb/util-cursor/log/ for context and an estimate as to how much work this would be/how creating a new xcb library looks like these days.

**Comment by Airblader** [comment]
I like the idea of writing an XCB library, but I don't think the approach from xcb-util-cursor or cairo-xcb is very good. The "power" of xrdb is the matching and wildcards which this mechanism doesn't allow. A proper library that supports the specification correctly would be better.

Either way, it means we need to have distros provide the library in their repositories, which potentially takes a long time (?)

**Comment by stapelberg** [comment]
> I like the idea of writing an XCB library, but I don't think the approach from xcb-util-cursor or cairo-xcb is very good. The "power" of xrdb is the matching and wildcards which this mechanism doesn't allow. A proper library that supports the specification correctly would be better.

Sorry, should’ve been clearer: I didn’t mean to imply that their approach is what should be done, rather I wanted to highlight that the lack of a proper library leads to people coming up with ad-hoc hacks like the two occurrences I referred to.

> Either way, it means we need to have distros provide the library in their repositories, which potentially takes a long time (?)

Certainly we’re talking about a couple of weeks to a small number of months here, yes. What I typically like to do is merge the commit which makes use of a new library shortly after a new i3 release, so that distribution packagers have time to make the library available before the next i3 release.

Note that these additional libraries are not released in sync with libxcb itself, so the time we’re talking about is only the time it takes to get the library into a release-able shape plus the time it takes for the distributions to package it and accept it into their archives. I think the latter can be as short as a week or two. For Debian, I can help.

You should also bring this up on the xcb-devel mailing list early on in the development phase, so that others have a chance to give advice.

**Comment by Airblader** [comment]
Alright, thanks. I haven't touched base with providing packages so far, except for the AUR in Arch, but that's of course not comparable. So that information is very helpful to me.

I'll make sure to bring this to mailing list attention once I actually start working on it.

**Comment by psychon** [comment]
I helped breaking Michael's xcb-cursor and I can also help breaking your library. ;-)
Myself, I have almost zero clue about Xrdb. I merged the code in cairo-xcb, because it did improve the situation, but at the time already felt like a library might be needed. Awesome currently uses Xlib just for this (I keep removing our use of Xlib and people keep coming up with new uses for it (cursors, input, Xrdb)...). I'd happily get rid of that as well. :-)
So, count me in!

**Comment by Airblader** [comment]
@psychon Awesome (no horribly old pun intended), thank you.

I've spent some time reading up on how the resource manager is supposed to work. Judging from the Debian code search, the majority of developers have little to wrong understanding of it. Seems like people rarely exhaust the powers of the database's options. :) My understanding (hopefully) is good enough now to start off with working on an algorithm, but first the project needs to be set up.

My bigger issue at the moment is not knowing how development on freedesktop works in terms of setting up the project. My C knowledge comes from working on i3, so I really only know make, but not autoconf. Time to learn something new, but help there would be appreciated. :) I've also posted about this on the xcb mailing list (which, I assume, is how you found here).

**Comment by psychon** [comment]
Well, just copy the autofoo-part (`configure.ac`, `Makefile.am`) from xcb-util-cursor to get started and then you only have to add the C parts. The `gperf`-parts of this (which you don't need) can easily be removed. I did the same for xcb-util-errors (http://lists.freedesktop.org/archives/xcb/2015-April/010264.html, a library to map numbers to the names of errors/requests/events that AFAIK no one uses (not even I use it)).
Setting up a project on fdo takes time, especially if you don't already have an account there. I'd propose to start working on github (and perhaps even keeping it there for now?). If this were to move to fdo, I guess the project would belong to the xcb group there which would shut you out from your own project. Perhaps the fdo admins have a better idea to solve this. How did @stapelberg do this?

(Sorry, but Christan S. doesn't ring a bell here)

**Comment by stapelberg** [comment]
In the beginning, I hosted the library on my own git server (would use GitHub these days), then applied for an account and moved it to fdo.

**Comment by Airblader** [comment]
@psychon (Storm, Maschinennahe Programmierung – he said that'd make you remember :) ) And thanks for all the hints. I'll try to get it started on Github and also apply for an account.

**Comment by psychon** [comment]
Ohhhhhh! Of course I know him! Say hi to him from me. I must have missed that name when looking through the list of Christians in the ARBI. :-)

**Comment by Airblader** [comment]
( @psychon He wants me to say "Hi", too, and add that you did convince him to eventually switch to Awesome ;) )

I've started https://github.com/Airblader/xcb-util-xrm now, but the actual implementation is missing still. The implementation won't be as extremely optimized as the Xrm* stuff, I'm sure, but I think that's OK since I doubt anyone is querying thousands of entries anyway. Typically you query one entry and use that value. We'll see how it performs in the end, though, since the algorithm is pretty complex.

**Comment by Airblader** [comment]
The library is soon going to come to a first release. Given that implementing this forces the various distributions to package it, should we maybe implement this with a compile flag for now that we remove in the next release? That gives them some time and is also easier for people building i3 from source.

**Comment by stapelberg** [comment]
In general, I dislike conditional compilation. In particular, I’d want to avoid releasing a version of i3 in which this feature is available or not depending on the libraries that were available at compile time. I think that’d lead to plenty of confusion.

I think the packaging for Debian and Arch could be done pretty quickly. Having the library available in Debian will also allow us to use it in our travis/autobuild setup, which would be good.

How about giving the package maintainers (see https://i3wm.org/downloads/ for links to the various distributions) a heads-up about the new library and then making i3 depend on the new library at an opportune moment? I.e., if the library gets picked up quickly, we can add the code before the next major release, otherwise we delay until right after?

**Comment by Airblader** [comment]
I wouldn't have made it dependent on the availability of the library on the user's system, but as a hard flag on whether to include this in the build or not. We could also add a note to the userguide in the meantime as well as add this information to `i3 --more-version`. We don't often depend on new libraries and even less so on *new* libraries, so I think this would be reasonable.

Giving the package maintainers a headsup is a good idea, but I think there are too many systems to catch them all. It also doesn't really deal with people who build i3 from source, which, afterall, benefits us as they often are people running `next` (and hence give us feedback before a release). We'd be forcing them to compile the library from source as well (rather than giving them the option to exclude this from their i3 build).

**Comment by psychon** [comment]
Random suggestion: Make awesome-git depend on this library before i3 does so. Awesome is bad at doing releases, so this doesn't cause that much trouble and I don't mind the random breakage (we are in bumpy times anyway). This won't cover many distros, I fear, but I bet that at least Arch would "automatically" pick up the library, just because awesome-git depends on it.

@Airblader I'd like to take a careful look at your library before the first stable release, if that's ok with you. I don't have much time in the near future, but feel free to give me a deadline for that, if you want.

**Comment by Airblader** [comment]
> I'd like to take a careful look at your library before the first stable release, if that's ok with you. I don't have much time in the near future, but feel free to give me a deadline for that, if you want.

I'd absolutely love for someone (or multiple people) to peer-review the library first. I don't have much of a timeline. I'll open an issue for this in the repository. I'll add @stapelberg as well in case he wants to review it at some point. I'll also inform the Xorg mailing list about the peer review.

**Comment by stapelberg** [comment]
> I wouldn't have made it dependent on the availability of the library on the user's system, but as a hard flag on whether to include this in the build or not.

That doesn’t change my take on it.

> We could also add a note to the userguide in the meantime as well as add this information to i3 --more-version.

I feel like that’s too much mental complexity for our users.

> Giving the package maintainers a headsup is a good idea, but I think there are too many systems to catch them all.

It’s good enough to make it a smooth ride for most of the systems, we can’t realistically cover all of them.

> It also doesn't really deal with people who build i3 from source, which, afterall, benefits us as they often are people running next (and hence give us feedback before a release).

People who compile software from source can also compile libraries from source. i3’s take on compiling from source has always been a firm “don’t do that, use your distro’s packages or our auto-built packages”.

My recommendation still is to ship the code without any conditionals.

**Comment by Airblader** [comment]
OK. :) Let's send out a heads up once the library is released.

**Comment by Airblader** [comment]
The library has now been released. I will contact the package maintainers soon and also work on a proposal for this feature.

**Comment by Airblader** [comment]
Working on a patch for this, I ran into a couple of things:

* Not having to define which resources to load is rather awkward because in the code we need to figure out the buffer size after all replacements. Currently we rely on parsing all `set` statements first, but without a `set` for resources, that isn't possible.
* During config validation, we have no connection and hence cannot get the resources. That's fine, per se, and I can just use empty string as the value – except that if I use a resource value in the configuration, the validation will throw an error.

I'm currently opting for a `set`-like directive along the lines of

    resource i3wm.color0 as $black default #000000

This has multiple benefits:

* I can actually use nice names for my variables (`color0` is really awkward to read).
* It makes the code easier. :-)
* I can define a fallback to use if the resource cannot be loaded, which also helps with the config validation problem.
