### ISSUE TITLE
[feature request] Disable focus wrapping

### ISSUE THREAD

**Issue by Praron** [i3/i3#2352]
I think, that i3 is just beautiful, but there's one small thing, that I need and I can't make it, it's a disabling of focus wrapping. That will allow half-blind control in some cases or when it's difficult to see current focus.

Related information: https://faq.i3wm.org/question/874/how-to-disable-focus-wrapping/

**Comment by stapelberg** [comment]
It’s been requested by 3 people in the last 4 years. I don’t think the low demand justifies the additional mental complexity (see also https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/).

I recommend to patch the source code if you feel strongly about this feature.

**Comment by CyberShadow** [comment]
I would very much like this too

**Comment by hencjo** [comment]
For the record, I'd love this feature as well. Idempotency over toggling.

**Comment by CyberShadow** [comment]
I don't think I've ever used focus wrapping intentionally, but I do remember times of momentary frustration when I vainly attempted so focus the left/right-most window by holding $mod + arrow key, or confusion when focus warped to a seemingly arbitrary window (because the wrapping is done against the container, not output). I must assume that the behaviour is useful to some users, but it's been nothing but an anti-feature to me.

@Airblader Would you be willing to carry a patch for an option to disable focus wrapping in i3-gaps?

**Comment by Airblader** [comment]
@stapelberg Are we sure about this decision? I do think there's a bit more demand for it than that (see these comments, but also other places). This feature does indeed make sense to me.

@CyberShadow Let's see whether we don't want to add this in i3 afterall; if not, I will consider it for i3-gaps based on how much of a patch it is (my main focus with i3-gaps right now is not so much adding features, but keeping it maintainable with upstream)

**Comment by Airblader** [comment]
I'll reopen for now and based on what @stapelberg thinks he can close again. :-)

**Comment by stapelberg** [comment]
Okay, let’s move this forward one step: if someone can suggest a PR and the change doesn’t turn out overly complicated, I’ll consider merging it.
