### ISSUE TITLE
“floating enable” on a single split window sometimes segfaults i3

### ISSUE THREAD

**Issue by shdown** [i3/i3#2421]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.12-85-g012de8c (2016-08-03, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-85-g012de8c (2016-08-03, branch "next") (pid 21815)
Loaded i3 config: /home/v/.config/i3/config (Last modified: Wed 10 Aug 2016 11:39:53 PM MSK, 41504 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5743114304094208.bz2

**What I did:**

Opened a non-floating window, switched layout to tabbed, split window vertically (or horizontally, it doesn’t matter), then toggled floating.

**What I saw:**

i3 stopped responsding and a black window appeared. I have already seen i3’s crash dialog, so pressed “r” and i3 restarted. This is probably a regression.

**What I expected instead:**
i3 not segfaulting.

**EDIT (2)**: well, sometimes it does not segfault -_-

**Comment by Airblader** [comment]
Can you generate a backtrace?

**Comment by shdown** [comment]
It turned out gdb couldn’t attach to the i3 process because of certain kernel hardening options, and for some reason i3 closes gdb’s stderr so nothing was written to ~/.xsession-errors.
Here it is: https://gist.github.com/shdown/71e26738da5962aef6310837c44b3a35

**Comment by AdamSLevy** [comment]
I also have experienced this problem exact problem except I cannot restart i3 with $mod+Shift+r or r. I have to go to another tty and login as root and kill it.

I am running 4.12 on Arch Linux.

**Comment by hwangcc23** [comment]
@Airblader @shdown
I also have experienced this problem, and got the backtrace from gdb.
Look like the segmentation fault is caused by an invalid con->parent.
I need a little time to study the code for this problem. I will debug the problem in the weekend if I have time.

Backtrace from gdb:
>Program received signal SIGSEGV, Segmentation fault.
0x0000000000416372 in con_get_workspace (con=0x7ab9c0) at ../i3/src/con.c:375
375         while (result != NULL && result->type != CT_WORKSPACE)
(gdb) bt
#0  0x0000000000416372 in con_get_workspace (con=0x7ab9c0) at ../i3/src/con.c:375
#1  0x0000000000416103 in con_has_managed_window (con=0x7ab9c0) at ../i3/src/con.c:266
#2  0x000000000042b413 in x_push_changes (con=0x78d190) at ../i3/src/x.c:1132
#3  0x0000000l0004533e8 in tree_render () at ../i3/src/tree.c:504
#4  0x0000000000452b4f in tree_close_internal (con=0x7b67c0, kill_window=DONT_KILL_WINDOW, dont_kill_parent=false, force_set_focus=false)
    at ../i3/src/tree.c:314
#5  0x00000000004196f0 in con_on_remove_child (con=0x7b67c0) at ../i3/src/con.c:1801
#6  0x0000000000452eb7 in tree_close_internal (con=0x783840, kill_window=DONT_KILL_WINDOW, dont_kill_parent=false, force_set_focus=false)
    at ../i3/src/tree.c:364
#7  0x0000000000431516 in floating_enable (con=0x7ab9c0, automatic=false) at ../i3/src/floating.c:183
#8  0x0000000000431eed in toggle_floating_mode (con=0x7ab9c0, automatic=false) at ../i3/src/floating.c:379
#9  0x0000000000420d92 in cmd_floating (current_match=0x679a20 <current_match>, cmd_output=0x679aa0 <subcommand_output>, floating_mode=0x7ab8c0 "toggle")
    at ../i3/src/commands.c:1088
#10 0x000000000043e5ae in GENERATED_call (call_identifier=60, result=0x679aa0 <subcommand_output>) at include/GENERATED_command_call.h:486
#11 0x000000000043ee19 in next_state (token=0x675d70 <tokens_FLOATING+48>) at ../i3/src/commands_parser.c:187
#12 0x000000000043f2fb in parse_command (input=0x7b4fe0 "floating toggle", gen=0x0) at ../i3/src/commands_parser.c:308
#13 0x00000000004125f8 in run_binding (bind=0x784260, con=0x0) at ../i3/src/bindings.c:792
#14 0x000000000042bace in handle_key_press (event=0x7a01a0) at ../i3/src/key_press.c:33
#15 0x000000000044e6aa in handle_event (type=2, event=0x7a01a0) at ../i3/src/handlers.c:1420
#16 0x0000000000439533 in xcb_check_cb (loop=0x7ffff532f8e0, w=0x68c140, revents=32768) at ../i3/src/main.c:133
#17 0x00007ffff5125d73 in ev_invoke_pending () from /usr/lib/x86_64-linux-gnu/libev.so.4
#18 0x00007ffff51293de in ev_run () from /usr/lib/x86_64-linux-gnu/libev.so.4
#19 0x0000000000439418 in ev_loop (loop=0x7ffff532f8e0, flags=0) at /usr/include/ev.h:835
#20 0x000000000043d51d in main (argc=3, argv=0x7fffffffe0a8) at ../i3/src/main.c:913
(gdb) p result
$11 = (Con *) 0x3ff0000000000000
(gdb) p *con
$12 = {mapped = true, urgent = false, ignore_unmap = 0 '\000', frame = {id = 2097265, gc = 2097266, visual_type = 0x69199c, width = 1024, height = 725, 
    surface = 0x7abb90, cr = 0x7abfb0}, frame_buffer = {id = 2097268, gc = 2097305, visual_type = 0x69199c, width = 1024, height = 725, surface = 0x7b7f60, 
    cr = 0x7ac970}, pixmap_recreated = false, type = CT_CON, num = 0, parent = 0x783840, rect = {x = 0, y = 28, width = 1024, height = 725}, window_rect = {
    x = 2, y = 0, width = 1020, height = 723}, deco_rect = {x = 0, y = 0, width = 1024, height = 14}, geometry = {x = 0, y = 0, width = 578, height = 340}, 
  name = 0x0, title_format = 0x0, sticky_group = 0x0, marks_head = {tqh_first = 0x0, tqh_last = 0x7aba88}, mark_changed = false, percent = 0, 
  border_width = 0, current_border_width = 2, window = 0x7ab810, urgency_timer = 0x0, deco_render_params = 0x6a8250, floating_head = {tqh_first = 0x0, 
    tqh_last = 0x7abac8}, nodes_head = {tqh_first = 0x0, tqh_last = 0x7abad8}, focus_head = {tqh_first = 0x0, tqh_last = 0x7abae8}, swallow_head = {
    tqh_first = 0x0, tqh_last = 0x7abaf8}, fullscreen_mode = CF_NONE, sticky = false, layout = L_SPLITH, last_split_layout = L_DEFAULT, 
  workspace_layout = L_DEFAULT, border_style = BS_NORMAL, floating = FLOATING_USER_OFF, nodes = {tqe_next = 0x0, tqe_prev = 0x783958}, focused = {
    tqe_next = 0x0, tqe_prev = 0x783968}, all_cons = {tqe_next = 0x7b67c0, tqe_prev = 0x7a9d88}, floating_windows = {tqe_next = 0x0, tqe_prev = 0x0}, 
  on_remove_child = 0x4194f5 <con_on_remove_child>, scratchpad_state = SCRATCHPAD_NONE, old_id = 0, depth = 24, colormap = 2097264}
(gdb) p *(Con *)(con->parent)
$13 = {mapped = 120, urgent = 107, ignore_unmap = 168 '\250', frame = {id = 4104678264, gc = 32767, visual_type = 0x100000000004, width = 0, height = 0, 
    surface = 0xac, cr = 0x0}, frame_buffer = {id = 2097299, gc = 2097304, visual_type = 0x0, width = 24, height = 14, surface = 0x0, cr = 0x0}, 
  pixmap_recreated = 24, type = CT_CON, num = 0, parent = 0x3ff0000000000000, rect = {x = 0, y = 0, width = 0, height = 0}, window_rect = {x = 0, 
    y = 1072693248, width = 0, height = 0}, deco_rect = {x = 0, y = 0, width = 0, height = 1072693248}, geometry = {x = 0, y = 0, width = 0, height = 0}, 
  name = 0x3ff0000000000000 <error: Cannot access memory at address 0x3ff0000000000000>, title_format = 0x0, sticky_group = 0x0, marks_head = {
    tqh_first = 0x783908, tqh_last = 0x783908}, mark_changed = false, percent = 72, border_width = 0, current_border_width = 1081262080, 
  window = 0x4072c00000000000, urgency_timer = 0x0, deco_render_params = 0x0, floating_head = {tqh_first = 0x783948, tqh_last = 0x783948}, nodes_head = {
    tqh_first = 0x0, tqh_last = 0x783958}, focus_head = {tqh_first = 0x0, tqh_last = 0x783968}, swallow_head = {tqh_first = 0x0, tqh_last = 0x697ee0}, 
  fullscreen_mode = (unknown: 2097276), sticky = 136, layout = 37, last_split_layout = 1024, workspace_layout = 14, border_style = BS_NORMAL, 
  floating = FLOATING_USER_ON, nodes = {tqe_next = 0x10000, tqe_prev = 0x0}, focused = {tqe_next = 0x10000, tqe_prev = 0x0}, all_cons = {
    tqe_next = 0x10000, tqe_prev = 0x0}, floating_windows = {tqe_next = 0x0, tqe_prev = 0x7839e0}, on_remove_child = 0x7839e0, 
  scratchpad_state = SCRATCHPAD_NONE, old_id = 0, depth = 32, colormap = 0}
