### ISSUE TITLE
Feature Request: Disable title on parent container

### ISSUE THREAD

**Issue by jdamboeck** [i3/i3#2423]
It would be really great if there was a way to disable or configure the title and border of parent containers.

**Comment by Airblader** [comment]
Please be more specific by providing an example situation. Perhaps with a screenshot.

**Comment by jdamboeck** [comment]
I really just like to have a way to only show a border on parent containers instead of a big blob of text which only duplicates the window titles of the childs.

**Comment by Airblader** [comment]
Again, please be more specific about what exactly you are talking about. We already have a `border` command. The only place where we force decorations anyway is in the tabs of a tabbed or stacked layout.

So please provide a screenshot where you point out what exactly it is you want to hide.

**Comment by stapelberg** [comment]
I agree with @Airblader’s comment that more info would be helpful to make sure we 100% understand what it is you’re talking about.

Then again, given that i3 can already hide borders, I’ll just make the assumption that you have already tried that and what you mean are the window decorations which i3 forces for split containers.

We thought about this before and decided that we always want to force window decorations in split containers, so that it’s easier to understand what’s happening on your screen. Without these decorations, the mental effort of using i3 significantly increases, because you need to keep more state in your head.

If this is not what you meant, please let us know with a more specific description.

**Comment by desgua** [comment]
I think I have the same issue. And this is how to reproduce it (doesn't always "work" though, odds are bigger if I just turned the computer on):    
1. Turn off connection with internet;
2. Close all Chrome instances;
3. run `i3-msg workspace "test" & /opt/google/chrome/chrome --app="https://calendar.google.com" & /opt/google/chrome/chrome --app="https://www.google.com" & /opt/google/chrome/chrome --app="https://anything.google.com" & `

This is with the glitch: 
![screenshot-2020-04-20_07_47_45](https://user-images.githubusercontent.com/51060956/79744032-0bc38380-82dc-11ea-8233-aa73e8337476.png)
  

 
This is without the glitch: 
![screenshot-2020-04-20_07_55_23](https://user-images.githubusercontent.com/51060956/79744210-59d88700-82dc-11ea-9eee-53f319395e72.png)

**Comment by desgua** [comment]
Please consider reopening this issue. I will help in what I can to solve it :-)

**Comment by desgua** [comment]
One thing that may help find the culprit: if I let the computer wait a few seconds before opening the second instance of Chrome (like in `i3-msg workspace "test" & /opt/google/chrome/chrome --app="https://calendar.google.com" & sleep 3 && /opt/google/chrome/chrome --app="https://www.google.com" & /opt/google/chrome/chrome --app="https://anything.google.com" & `) the glitch doesn't occur.

**Comment by stapelberg** [comment]
@desgua I don’t think that’s the same issue. The title is being forced in your case because you have a tabbed split container in the mix. Please open a separate issue.

**Comment by desgua** [comment]
@stapelberg Thank you Michael, I just opened a new issue: https://github.com/i3/i3/issues/4030
