### ISSUE TITLE
[Feature request] Support setting title bar location

### ISSUE THREAD

**Issue by johnp** [i3/i3#2441]
It would be nice to have a `title_bar` command to set the location of the title bar.
Most useful would probably be `title_bar bottom`, but it'd be nice if `title_bar left`/`title_bar right` could also be supported.
Dynamic options, like placing the title bar at an outer edge (vertical/horizontal), could also be added. This would arguably be quite a bit more complicated, as one would have to add fallback options should no outer edge exist, or should there be two outer edges.

Dynamic options example:

`title_bar outer_edge_vertical outer_edge_horizontal bottom`

Explanation: Searches for a vertical outer edge (at screen top/at screen bottom) first, if none is found or it's ambiguous (read: container has both top and bottom outer edges), try to find an outer edge in the horizontal direction (screen left/right), if again none is found or it's ambiguous, place the title bar at the bottom.

But really, a basic `title_bar bottom` would IMHO already go a long way.

**Comment by stapelberg** [comment]
The motivating use-case seems to be switching browser tabs by flicking the mouse to the top of the screen and then clicking, which sounds like a reasonable motivation to me.

That said, having title bars at the bottom violates the order in which we usually read text: from left to right, from top to bottom. AFAIK, even in righ-to-left cultures, people still read from top to bottom.

Therefore, I’m not yet convinced whether having title bars at the bottom would be too strange to use, or whether one could get used to it.

Also, I’m not sure about user demand for this feature.

**Comment by johnp** [comment]
>  by flicking the mouse to the top of the screen and then clicking

Actually I stopped clicking tabs many years ago by setting the Tab Mix Plus option `extensions.tabmix.mouseOverSelectDelay` to ~20ms....

**Comment by Airblader** [comment]
> Edit: The only reason I still 'need' to have title bars for a browser is because it shows an overview as to what windows are open in stacked mode.

Can you elaborate on this? Windows will have a titlebar if they're in a stacked container, no matter whether the titlebar is disabled on them or not.

I don't see it as very useful that you (the user) change the position of tabs for _all_ windows just to deal better with _one_ application. Especially browsers give users quite a lot of options such as gestures or shortcuts to switch tabs, why not use those?

**Comment by johnp** [comment]
> Can you elaborate on this? Windows will have a titlebar if they're in a stacked container, no matter whether the titlebar is disabled on them or not.

Thank you, I wrote that edit without testing and actually didn't realize that. Still, once I have a stacked container, the title bar at the top makes tab switching inconsistent to other workspaces :/

> I don't see it as very useful that you (the user) change the position of tabs for all windows just to deal better with one application. Especially browsers give users quite a lot of options such as gestures or shortcuts to switch tabs, why not use those?

Assuming no Add-On exist that change a tab based on the extrapolation of a mouse move towards said tab (which would likely be a bad idea anyway), gestures and shortcuts can only tab trough tabs sequentially or have to use the number of the tab, which is not quickly obvious (short of memorizing ones' pinned tabs).


So, as a result of the helpful feedback to my feature frenzy, let's change the proposition: How about only being able to set the location of a stacked container title, aka `stacked_title bottom` or similar?

**Comment by Airblader** [comment]
It still sounds like an application issue rather than a window manager issue to me. Why is the solution not to bring this to the browser developers and/or writing such a plugin? Personally my opinion is that the complexity for implementing this in i3 is too much of a cost and even then it sounds like more of a workaround than a solution to me because it's awkward behavior (see what @stapelberg said.)

**Comment by johnp** [comment]
How would you do this on a browser level? The Window Manager is responsible for the (stacked) title bar.

To come at this from another angle, you could see the stacked title bar at the bottom as a taskbar.

The same question also popped up on reddit ~6 months ago: https://www.reddit.com/r/i3wm/comments/463mtj/window_titlebars_on_bottom/

Is drawing the title bar really implemented so complicated that one cannot easily allow an y-position of the lower left edge minus the bar height and anchoring the content at 0x0?

**Comment by Airblader** [comment]
> How would you do this on a browser level? The Window Manager is responsible for the (stacked) title bar.

Sorry, I meant that in reference to having a mechanism to switch tabs easily (tabs the browser implements on its own afterall.)

> Is drawing the title bar really implemented so complicated that one cannot easily allow an y-position of the lower left container edge minus the bar height and anchoring the content at 0x0/container top left?

There's a two step process of laying out the containers and doing the actual drawing. i3 is also different from other window managers in that it draws the titlebars on the parent container and not the window's frame window (the border, however, _is_ drawn on the frame window.) All of this does in fact make the process rather complex at the moment, yes. And then there's other things to consider – mouse bindings on the titlebar come to mind immediately, maybe other things as well.

All of that combined with the awkward, unnatural way of having titlebars and the fact that this is a complete one-application problem currently leans me towards rather not having this in i3. Also consider the case of nested split containers. The order of titlebars would actually be somewhat reversed (inner containers' titlebars being above outer containers' titlebars.)

At least as far as complexity of the implementation goes, however, it's of course always easier to talk about an actual pull request in case anybody feels up to the challenge of giving this a shot. The relevant parts are `src/render.c` for laying out the containers and `src/x.c` for the drawing.

**Comment by Airblader** [comment]
P.S.: Just to clarify, though, my main argument against the feature is the awkwardness of how it'd look and that it's a single-app issue, not a general one. Complexity should only be an argument once we know what the complexity actually is (i.e., when we have a pull request.) As always we reserve the right to reject a PR even if the feature itself has been accepted if we find that the change is too complex.

**Comment by Airblader** [comment]
By the way: why not have the browser tabs on the bottom instead? AFAIK firefox can do that (perhaps with a plugin), I'm pretty sure I've seen it before.

**Comment by johnp** [comment]
Thank you very much for your insight!
Fwiw, looking at the Sway code (though without much insight) it seemed to be rather straightforward...

Regarding looks: I said stacked layout, but actually meant tabbed (:confused:). I'll have a look at it in Gimp later.

Tabs on the bottom would only work if I'd place my i3bar at the the top, but thank you for the suggestion. I'll have a look around and see if I can find an Add-On (maybe Tree Stye Tab? heard much of it, but never tried it out actually).

**Comment by Airblader** [comment]
> Fwiw, looking at the Sway code (though without much insight) it seemed to be rather straightforward...

But sway != i3. :-)

> Regarding looks: I said stacked layout, but actually meant tabbed

Whatever the solution, it'll affect both stacked and tabbed anyway.

**Comment by johnp** [comment]
So, I've recently refactored py3status' `window_titles_async.py` to show all window titles of the focused windows parent, with support for click-events and colorization.
I still have to to figure out, how to use the constrained amount of space for more than a couple windows, while still providing the identifying details of the window title (stripping the rest).

In any way, I've found a solution to get the title bar to where I want it, but I am unable to get rid of the default tabbed/stacked title bar. `for_window [] border pixel 0` only removes the normal title bars.

So, how about a config option to disable the tabbed/stacked title bar?

**Comment by Airblader** [comment]
The very reason we force titlebars is because we don't want to allow not having them. They are the only visual clue that there is a tabbed / stacked container. Without them, it's entirely unclear (visually) that there is more than one window.

**Comment by johnp** [comment]
Unless some other tool, like py3status, displays them ;)
To be clear: I'm not advocating a change to the `border` command, but rather a strictly opt-in `tabbed_titlebar none` or something similar.

**Comment by Airblader** [comment]
py3status cannot display them, though. It's not so much about displaying the title, but about having a visual indication that windows are stacked here (which is fundamentally different from everything else in the realm of a tiling window manager).

Why not set the `title_format` for all windows to empty string and keep the titlebars on such containers as a simple colored indication of the layout? If you set the font to a 0px font (assuming that works) the titlebars will be at most 5px high.

In any case I think the usecase here is too specific to justify a separate directive, but that's @stapelberg's decision. It'd also be a fairly trivial local patch to disable titlebars if you want it for yourself.

**Comment by johnp** [comment]
Can confirm, this works. I'll have to play around with it on a couple devices, but in combination with the title script it looks good enough for my use case.
Thank you very much for your help and patience @Airblader!

**Comment by docelic** [comment]
My understanding is that this request is on hold or rejected because the argument is that it makes no sense to have window titles as the bottom.

I3's window titles are generic and plainly looking (a quality) and there is really no difference between i3's window title and what could be considered a program icon/text in a taskbar.

So having titles at the bottom of the screen would help think of it/use it as taskbar.

Note that, in stacking layout, if one has e.g. 10 windows open and is currently on the 3rd one, then it is already not possible to think of i3's "window titles" in the usual way (as being at the top of window), since the window title is 7 rows away from the actual window to which it belongs.

Consider this screenshot for example:
![titles](https://user-images.githubusercontent.com/112993/28799880-9948bb18-764a-11e7-89ac-e5135bdb2c8a.png)

Implementing this request, and possibly combined with #2747, would allow alternative use cases without modifying any internals or i3's philosophy for those who wouldn't want it.

Thanks

**Comment by Airblader** [comment]
> So having titles at the bottom of the screen would help think of it/use it as taskbar.

I think that's a wonderful reason for arguing *against* this feature. We want the titles to be titles, not further make it possible to abuse them for other things.

**Comment by Kommynct** [comment]
I prefer them on the bottom simply because it makes my content slightly easier to see, whereas i rarely need to see the title, while absolutely minute, it does help people with poor eyesight.

**Comment by jidanni** [comment]
I use `workspace_layout tabbed`.
I used to use icewm.
Its titlebar is at the bottom.
If 20 years ago I knew I would switch to i3wm,
then I would have asked them to allow moving it to the top.
So I wouldn't have to go nuts now trying to adapt.

**Comment by herkhinah** [comment]
There is another use case for setting the title bar location to the bottom. In my setup (my focus is more on the top of the display because that way I can sit more ergonomically) I want the most important information at the top of my screen and the noise like system bar and window titles at the bottom. Setting the title bar to the bottom would allow me to use my screen estate more efficiently, because the bottom of my screen is less valuable than the top of my screen.

**Comment by oku32** [comment]
I would personally like to see this because I often find myself using the tabbed layout, and these title bars make it much easier to quickly know which window I'm on, and any surrounding windows, without the mental overhead of remembering what I have open in a workspace, and the current state they're in.

The title bars are merely something I _might_ need to glance at, and so I'd rather be able to see more of the top of my screen at all times, rather than it being filled by something that's often less important. The same goes for my status bar and browser tabs, which I've opted to place at the bottom of the screen.

I don't have an application specific use-case for these, I'd rather avoid using my mouse to be honest, which is in reference to the aforementioned motivating use-case above with flicking the mouse to browser tabs.
