### ISSUE TITLE
Option to have "workspace next" create a new workspace

### ISSUE THREAD

**Issue by vext01** [i3/i3#2449]
This is  not a bug, but more a feature request.

Would it be possible to have an option to have `workspace next` binding create a new workspace?

Failing that, could there be a separate binding to create a new workspace (if on the last non-empty workspace)?

(I'm using 4.12 on OpenBSD)

Thanks

**Comment by stapelberg** [comment]
This might just be a terminology issue, but one cannot explicitly create a workspace in i3. Workspaces are created on demand as you switch to them.

I think what you might be looking for is some logic with which to switch to the next (numbered) workspace, based on the current/existing workspaces. In that case, please see https://github.com/i3/i3/issues/2072. Otherwise, please clarify what you meant.

**Comment by vext01** [comment]
Let me give an example.

Suppose i have 2 workspaces in use and both have some windows. If im on workspace 1, and I press the keybinding for "workspace next", i3 switches to workspace 2 (nothing new there). Now if i press it again it would be nice for workspace3 to be created and switched to.

Does that help explain? What do you think?

**Comment by Airblader** [comment]
@acrisci has a script for that using the IPC. I can look it up later.

**Comment by Airblader** [comment]
Well it only sort of does what @vext01 wants, but is easy enough to change: https://github.com/acrisci/i3ipc-python/blob/master/examples/workspace-new.py

**Comment by vext01** [comment]
Thanks!
