### ISSUE TITLE
Add a 'last' output selector

### ISSUE THREAD

**Issue by flv0** [i3/i3#2606]
Feature request: In addition to current, add a 'last' output which would for example allow to make a workspace active on the current physical output by issuing 'workspace N ; move workspace to output last'.

**Comment by Airblader** [comment]
Personally I feel like the usecase you describe is well-suited for a script that just does this (which is easy enough to write).

**Comment by flv0** [comment]
The idea for the feature request stems from an irc discussion where on the one hand it was observed that 'move workspace to output current' seemingly has no reasonable use-case. Also, since I was already about to write that script, from a short research it seems there is no direct way of obtaining the current xrandr output via standart x11 tools, but needs to be inferrered from the current window extents and the screen layout/geometry. If there are any convenient mechanisms to find the current output which we missed I'd be very much interested since it would solve the problem at hand just fine. However I thought it might also be of general interest for moving windows/workspaces between screens by scripting means.

**Comment by Airblader** [comment]
> it was observed that 'move workspace to output current' seemingly has no reasonable use-case

Maybe not like that, but it does once you use it with command criteria. In fact, its the very usecase you're solving here as well:

    [workspace="^N$"] move workspace to output current

… just that you don't need to switch focus to the other output first. Now, one downside here is that the command will actually be executed for every window on that workspace (which doesn't hurt, though) and that it won't work if the workspace is empty (which definitely isn't nice).

> standart

Not to be *that* guy, but since this is just all too common: standar*d*. :-)

> If there are any convenient mechanisms to find the current output which we missed I'd be very much interested since it would solve the problem at hand just fine.

Just use the `GET_TREE` reply on the i3 IPC to get the output of the focused window. With something like i3ipc-python that's a oneliner. You won't get this from common X11 tooling because in X there is no such thing as a »focused output«.

> However I thought it might also be of general interest for moving windows/workspaces between screens by scripting means.

To me this usecase seems a bit limited, but more importantly it messes up the focus stack. I'd prefer a solution that doesn't require doing that.

**Comment by flv0** [comment]
Hey. Wasn't aware of all those IPC mechanisms i3 provides, yes parsing the tree (or the workspaces looking for focused) works just fine. For the fun of it I used a ruby script to determine the currently focused output:
```
#!/usr/bin/env ruby

require 'i3ipc'

i3 = I3Ipc::Connection.new

for workspace in i3.workspaces do
  if workspace.focused then
    puts workspace.output
  end
end

i3.close
```

And a short bash script which is bound to the hotkeys to move workspace N "here":
```
#!/usr/bin/env bash

output=$(i3-current-output)
i3-msg workspace $1
i3-msg move workspace to output $output
```

So thanks, all fine and dandy, closing this.

PS: the typo stems from my fuzzied muscle memory after having switched to the workman layout, I know it's actually spelt standard, but thanks for the pointer ;)
