### ISSUE TITLE
Feature request: key bindings IPC reply

### ISSUE THREAD

**Issue by zandrmartin** [i3/i3#2691]
I was thinking of adding an IPC reply to [Sway](https://github.com/SirCmpwn/sway) that would list all currently configured key bindings, but @SirCmpwn isn't big on breaking compatibility with the i3 IPC protocol. Is this something you guys would be interested in adding? I'm thinking `i3-msg -t get_bindings` or something to that effect. The reply could use (some of) the same key/value pairs as the binding event JSON.

**Comment by Airblader** [comment]
> but @SirCmpwn isn't big on breaking compatibility with the i3 IPC protocol

And how is this a breaking change? It's an additional IPC call.

Implementing a feature in i3 because you want it in sway is not a reason to implement something in i3. Presenting an actual usecase as for why you need this (in i3) would be a reason.

That said I'm fairly certain this has been requested before. We should find that ticket to see pro and contra arguments made back then.

**Comment by SirCmpwn** [comment]
>And how is this a breaking change? It's an additional IPC call.

My opinion is being misrepresented here. I don't consider it a breaking change, but I hesitate to pollute the IPC command namespace without talking about it with i3 first. Currently sway introduces one new IPC command, which is slated to be removed and implemented differently.

**Comment by Airblader** [comment]
I'm not generally opposed, but as I said above, I'd like to have good reasons to implement it. »sway won't do it if i3 doesn't« isn't a reason. :-)

**Comment by zandrmartin** [comment]
I apologize for the confusion, I misunderstood what @SirCmpwn was saying when I discussed it with him.

**Comment by SirCmpwn** [comment]
>I'm not generally opposed, but as I said above, I'd like to have good reasons to implement it. »sway won't do it if i3 doesn't« isn't a reason. :-)

Sure :)

**Comment by zandrmartin** [comment]
I searched through closed issues and didn't see anything but it's entirely possible I've missed something. Closest I found were issues about adding the `BINDING_MODES` reply.

I think the primary driver for wanting this is so I know which key bindings I've already assigned; the idea came to me when trying to figure out a new binding for a command and realizing the only way I could tell what I've already bound is looking through my config file. That's ok for me but I'm not aware of any way an IPC client would be able to get this information.

**Comment by Airblader** [comment]
> I think the primary driver for wanting this is so I know which key bindings I've already assigned

Why does an IPC client need to do this? We already print an error if a binding has been configured twice.

**Comment by zandrmartin** [comment]
I could imagine a case where a client wants to add a binding but needs to ensure it does not conflict with one already configured. Maybe I want to build a key binding cheat sheet generator app - it's way easier to deal with a JSON response than trying to write a config file parser, and the config file may not contain all the bindings if I've already added some through `i3-msg`.

**Comment by Airblader** [comment]
There's a lot of »maybe«s in there. Do you actually want to build something and if so, what? I'm not keen on adding features because maybe some day they could be useful to someone.

**Comment by SirCmpwn** [comment]
>There's a lot of »maybe«s in there. Do you actually want to build something and if so, what? I'm not keen on adding features because maybe some day they could be useful to someone.

Personally I'm okay with "maybe" use-cases. These seem like some interesting use-cases. If you build it, they will come.

**Comment by zandrmartin** [comment]
I don't currently want to build what I mentioned, no, but someone might. And it seems like it would be a nice complement to the `BINDING_MODES` reply.

Another possible use case: if I can get a list of key bindings, I can know what bindings might be interesting to watch for in the binding event reply.

**Comment by Airblader** [comment]
> Another possible use case: if I can get a list of key bindings, I can know what bindings might be interesting to watch for in the binding event reply.

I don't follow here. You get the binding event for all bindings, anyway. And if you use that event you probably know what you're looking for, anyway. Instead of looking through configured bindings for what to look for, just look for it in the events directly. I'm not sure why you'd need a list of bindings here.

And that's not really a usecase, anyway, because it's nothing practical. Nobody reads events for the sake of reading events – there's something they want to achieve with it.

> the config file may not contain all the bindings if I've already added some through i3-msg.

Bindings cannot be added through the IPC.

> I could imagine a case where a client wants to add a binding

Assuming you're talking about some kind of config helper tool, I think a reasonable tool in that area would want to display existing bindings and thus would have to parse the config anyway. Besides, the config contains much more than just bindings. And such a tool needs to understand the format of the config file anyway, even if just to write out the new binding.

My current summary is that we have a feature here with very limited use and with no one actually planning to use it (not even you). That seems like it violates one of i3's core values:

> Only add features which benefit many people, instead of going to great lengths to support rarely used workflows.

We try to keep i3 relatively simple instead of blowing it up with features. It just makes maintenance harder. If someone has specific plans to use this for something I'm happy to reconsider.

**Comment by zandrmartin** [comment]
Fair enough. Thanks for the consideration.
