### ISSUE TITLE
Feature Request: more hide_edge_borders options

### ISSUE THREAD

**Issue by squigglezworth** [i3/i3#2727]
`hide_edge_borders {top,bottom,left,right}` 
would be great, as well as a way to use hide_edge_borders smart on workspaces with a single root container, i.e., 1 window, or 1 stacked/tabbed container (however, with any number of windows/containers inside)

**Comment by Airblader** [comment]
What's the usecase for only having this for, say, the left border? That seems not very useful to me and as such I'm leaning towards rejecting this request. Can you explain why you would need this?

**Comment by squigglezworth** [comment]
I am actually struggling to come up with a use-case for per-side hide_edge_border, although I had one in mind yesterday when I made this :P
And I also just experimented and realized that hide_edge_borders smart actually does work with single-container workspaces too.

I'd appreciate keeping the issue open for now to see if anyone else has thoughts about the per-side setting (or if I can remember my own use-case)

**Comment by Airblader** [comment]
I don't think it's a good idea to have open issues for the sake of open issues because maybe one day someone might have an idea what it's useful for.

The issue still exists, even when closed, so if anyone (including you) has a usecase, let us know and we can discuss and reopen if necessary. Until then I'm going to close this.

**Comment by geyslan** [comment]
@Airblader 

A usecase here could concern to a specific window rather than to a generic option. For instance, I would like to force hiding only the top border of `Firefox` and `Chrome`, when they are on upper edge, even when it is not a single window.

`for_window [class="^Chromium"] border smarthide top`

This would avoid a wrong click on the border, when trying to click on tab. When the top border isn't attached to edge, it would draw the border normally.

**Comment by Airblader** [comment]
Would it really be a big deal to disable all borders for the window (in that case)? I still think this is extremely specific and thus yields very little use for the cost of implementing it, especially the mental complexity of it.

**Comment by geyslan** [comment]
> Would it really be a big deal to disable all borders for the window (in that case)?

Yes, if I'm using only one window. What would be similar to `hide_edge_borders smart` (in that case). However when I have more than one window, a borderless window seems badly attached (ugly) to the others.

Another problem of `border none` is that it's hard to know if it is focused. So hiding only a specific border would be a great help.

For instance, you don't figure out which one is focused (since firefox is border none).
![shot at 2017-09-09-15h47m14s](https://user-images.githubusercontent.com/3372117/30242913-421c2424-9576-11e7-8c9d-d0b716786717.jpg)

**Comment by geyslan** [comment]
@Airblader What do you think? Should I open a proper Feature Request?

**Comment by Airblader** [comment]
It seems like an extremely specific use-case tailored for one specific kind of application (and even there it doesn't strike me as that big of an improvement), thus I'm not really favoring this idea at the moment. @stapelberg How do you feel about this?

**Comment by stapelberg** [comment]
Agreed.
