### ISSUE TITLE
[enhancement] Support _NET_WM_WINDOW_OPACITY

### ISSUE THREAD

**Issue by dbdr** [i3/i3#2840]
**What I did:**

`xprop -root _NET_SUPPORTED | grep -o _NET_WM_WINDOW_OPACITY`

**What I saw:**

_NET_WM_WINDOW_OPACITY is not declared as supported. And indeed it is not listed in https://github.com/i3/i3/blob/14eea7fce571ed6b1592af382aa4440b87c62b56/include/atoms_NET_SUPPORTED.xmacro

However it does work, *provided a compositor like compton is running*. For instance this does change the window's opacity to about half:

`xprop -id <window id> -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY 2000000000`

The problem is that a program that checks if _NET_WM_WINDOW_OPACITY is supported will not get the correct answer and probably won't attempt to use it.

**What I expected instead:**

Ideally the response to _NET_SUPPORTED would include _NET_WM_WINDOW_OPACITY, but only if a compositor is used.

**Comment by Airblader** [comment]
How exactly are we as a non-compositing window manager supposed to support this atom? In other words, what behavior do you expect i3 to have for this atom?

**Comment by Airblader** [comment]
Also, it doesn't seem like `_NET_WM_WINDOW_OPACITY` is even part of the specification. Which makes sense, since it's a compositing concern, not a window management concern.

**Comment by Airblader** [comment]
In fact, to quote the specification (https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html):

> _NET_SUPPORTED
> 
> _NET_SUPPORTED, ATOM[]/32
> This property MUST be set by the Window Manager to indicate which hints it supports. For example: considering _NET_WM_STATE both this atom and all supported states e.g. _NET_WM_STATE_MODAL, _NET_WM_STATE_STICKY, would be listed. This assumes that backwards incompatible changes will not be made to the hints (without being renamed).

`_NET_WM_WINDOW_OPACITY` is not standardized, nor is it anything a (non-compositing) window manager does. No client should be checking `_NET_SUPPORTED` for it, IMHO.

I'll wait for a proper specification hinting that there's even anything i3 should be doing here, otherwise I'll close it.

**Comment by dbdr** [comment]
Thanks for your responses. Actually i3 would not need to do anything else, since as I mentioned the functionality itself works when for instance compton is running.

Currently transparent windows are broken under java and i3, because the way openjdk decides if transparency is supported (for X11) is by searching for _NET_WM_WINDOW_OPACITY in the _NET_SUPPORTED list. So something would need to change somewhere for this to start working:

1. is openjdk wrong in checking _NET_SUPPORTED? (It probably does that because it works with som WMs, of course that does not mean it is "correct") What other method should be used to determine if _NET_WM_WINDOW_OPACITY is supported? Or what other mechanism than _NET_WM_WINDOW_OPACITY should be used to set window transparency?

1. does i3 know that a compositor is running, and could it include _NET_WM_WINDOW_OPACITY in that case?

1. any other idea?

**Comment by Airblader** [comment]
> Actually i3 would not need to do anything else

The point of `_NET_SUPPORTED` is for the window manager to state which atom _it_ supports, not what some other client may or may not support. There _are_ compositing window managers for which it could make sense to list this atom (but again, this atom isn't even specified in any standard), but i3 is not one of them.

> is openjdk wrong in checking _NET_SUPPORTED?

Yes and no. Yes because the atom isn't standardized and yes because it doesn't consider the fact that compositors can be external under X11. No because for compositing window managers it does make sense.

> What other method should be used to determine if _NET_WM_WINDOW_OPACITY is supported?

I'm not sure whether there's a `_NET_SUPPORTED` equivalent for compositors. I don't know of one.

> does i3 know that a compositor is running

No, we do not.

i3 does not support opacity, thus i3 cannot set this atom in any way. In particular note that not only is i3 not a compositing window manager, but we officially do not even support running an external compositor with i3 (although it does typically work for the most part). For that reason I'm going to close this request.

> any other idea?

You could ask on the Xorg mailing list. Seeing how `_NET_WM_WINDOW_OPACITY` isn't standardized, I assume unless you find an actually standardized usecase, there's generally not going to be any reason to have such a mechanism.

**Comment by dbdr** [comment]
OK, thanks for your comments!

**Comment by acrisci** [comment]
I feel bad we can't support this so I wrote you a script to use as a workaround. Maybe it would work in an `exec_always` config directive.

```
xprop -root -f _NET_SUPPORTED 32a -set _NET_SUPPORTED "$(xprop -root | grep '^_NET_SUPPORTED(ATOM)' | sed 's/^.*= //' | tr -d ' '),_NET_WM_WINDOW_OPACITY"
```

It is unfortunate that we seem to be running up against the limits of the X11 specs we were provided by our legacy. This situation is obviously something they did not consider when writing the spec.

If the property were something like `_NET_NOT_UNSUPPORTED` then we could add it to the list. But in general, @Airblader is correct in his reasoning.

For instance, if the client somehow relied upon opacity support for the functioning of the application such that it would display things differently if a window could not be transparent, then having the atom declared to be supported would certainly be a mistake. That is the intention of `_NET_SUPPORTED` and is the case for most of the atoms I see in there.

You might argue that you couldn't imagine a case where that would cause a problem and a special exception to the spec could be made in this case and that would be a point of view I would consider, but it would definitely not an optimal outcome. Exceptions have to be made with care, and transparency is considered "eye candy" which is not a high priority for this project.

I would suggest brining this up with the openjdk people and see what they think. If you do, keep us informed about what they say about if there is anything we can do to support the feature.

**Comment by dbdr** [comment]
Thanks Tony. This makes me realize something: the JDK has a method isWindowTranslucencySupported which returns false for TRANSLUCENT if _NET_WM_WINDOW_OPACITY is not in _NET_SUPPORTED. This might be correct since there does not seem to be any other way to know if it is supported. However when the method setOpacity is called, it will fail with an exception in that case, making it impossible to set the opacity. Theoretically this could be changed to always set the _NET_WM_WINDOW_OPACITY property, not knowing if it will have an actual effect or not, which I suppose is what other X clients do.

**Comment by dbdr** [comment]
For reference, I reported the following proposal for the JDK:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8184718
