### ISSUE TITLE
i3-msg swap container with con_id <invalid_con_id> crashes i3

### ISSUE THREAD

**Issue by orestisf1993** [i3/i3#2895]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14-3-g5df53f5 (2017-09-04, branch "next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.14-3-g5df53f5 (2017-09-04, branch "next") (pid 844)
Loaded i3 config: /home/orestis/.config/i3/config (Last modified: Mon 04 Sep 2017 06:26:40 PM EEST, 2555 seconds ago)

The i3 binary you just called: /usr/local/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5726488619909120.bz2

**What I did:**
Open a window and
```
i3-msg swap container with con_id 1
```

**What I saw:**
i3 crashes

**What I expected instead:**
Nothing really I was just trying out the new command. It shouldn't crash though.

**Comment by Airblader** [comment]
I can reproduce this. The problem is that we just cast the argument to `(Con *)` which then fails. I did it this way because we do the same for match criteria parsing, but since there we first compare the result with a container that we know is actually a container, we never run into this issue.

@stapelberg Is there a better way of checking the sanity of the argument other than comparing it against all known containers?

**Comment by stapelberg** [comment]
> @stapelberg Is there a better way of checking the sanity of the argument other than comparing it against all known containers?

We don’t have any “magic ints” at the beginning of our structs (I think GObject does that), so the answer is no — we’ll need to compare against all known containers for the time being.
