### ISSUE TITLE
split + layout stacked / tabbed creates redundant containers

### ISSUE THREAD

**Issue by orestisfl** [i3/i3#3001]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14-128-gc08ef361 (2017-09-29, branch "next") © 2009 Michael Stapelberg and contributors
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5637036128075776.bz2

**What I did:**

1. fresh workspace
2. open window
3. layout stacked
4. open window
5. split v
6. layout stacked
7. repeat 5-6

**What I saw:**

![2017-09-30-042426_1680x1009](https://user-images.githubusercontent.com/5778622/31041003-555dc8ae-a597-11e7-9da4-69fb71b69aa3.png)

Repeating this too many times makes i3 unbearably slow and memory usage skyrockets.

**What I expected instead:**
Redundant stacked / tabbed containers should not be opened.

**Comment by Airblader** [comment]
IMHO this is the correct behavior. Why should we close this (valid) container that has been intentionally created? You _can_ move a window into each of those stacked containers (just do your steps, open a second window and `move up` a few times).

(Although, oddly, `move down` a single time immediately moves it all the way to the first window)

@stapelberg CC

**Comment by orestisf1993** [comment]
Hmm. I understand the behavior a bit better right now but the same thing (intentionally) doesn't happen for `layout splith && splitv`.

I think it's less confusing if we apply the same to stacked / tabbed containers instead of allowing this:
![out](https://user-images.githubusercontent.com/5778622/31044281-0584bc0a-a5d5-11e7-86f4-20072b0e7a76.png)

**Comment by roobre** [comment]
I'm suffering a similar issue on `Binary i3 version:  4.14.1`. When a new workspace is created in certain mode, and then I issue a layout change (for example, `layout toggle split` in tabbed container, or `layout tabbed` on a split container), a redundant container bar at top is created.

For example, if I create a new container with `workspace_layout split` (default), and then I issue `layout tabbed`, I get:

![deepin-screenshot j28535](https://user-images.githubusercontent.com/969721/32701405-013435a0-c7d5-11e7-84b9-48ae8c327849.png)

This behaviour is diferent to what i3 did before, where this redundant top bar was not shown.

Full version output:

```Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 5061)abort…)
Loaded i3 config: /home/roobre/.i3/config (Last modified: Sun 05 Nov 2017 04:22:58 PM CET, 610933 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

**Comment by orestisf1993** [comment]
The offending line for the slowdown is this `render_con`:
https://github.com/i3/i3/blob/6f11b6fa4a784e85a1b74cb7ff74058023ce30aa/src/render.c#L164-L170

**Comment by roobre** [comment]
I forgot to comment that on `i3 version 4.15-36-g670dfa0b (2018-03-19, branch "next")` I no longer suffer this issue. I'm not sure if this was fixed exactly on that version, but since I switched to the next branch it is gone. Glad to see it fixed, btw, it was really annoying. Great work!

**Comment by orestisf1993** [comment]
@roobre weird, I still get this behaviour.

**Comment by roobre** [comment]
@orestisf1993 What default `workspace_layout` are you using? I certainly do not get extra containers using `tabbed`, after switching to split with `layout toggle split`.

**Comment by orestisf1993** [comment]
@roobre With the default i3 config: open fresh workspace, $mod+w (layout tabbed), open windows

**Comment by mgarort** [comment]
First of all, I want to say thank you to the developers. i3 has really changed my workflow for the better and is my second favorite program ever, only beaten by Vim. So thanks!

Now, IMVHO, and putting aside the memory issue, I think this behaviour is not helpful. I arrived to this issue coming from [this Reddit question](https://www.reddit.com/r/i3wm/comments/9emfke/collapse_empty_containers/) and looking for a way to disable (or at least avoid) this behaviour of empty stacked containers. Everytime this has happened to me it has been by mistake and it was a small inconvenience that I had to get rid of. Furthermore, sometimes the resulting layout is not intuitive at all and I have to try a few times until I find out how to collapse the empty containers.

In my case, I think it mostly happens when I first do `layout tabbed` and later do `split toggle`. The only "solution" I can think of is to not create a keybinding for `split toggle`, but obviously this would be at the cost of not being able to toggle between new horizontal and vertical splits, so I haven't gone down this road yet.

**Comment by usersina** [comment]
This suddenly started happening for me when I uninstalled `terminator` and installed `termite`. At the same time, I suddenly started having [this issue](https://github.com/i3/i3/issues/3518) too.

```
Running i3 version: 4.20.1 (2021-11-03) (pid 11496)
Loaded i3 config:
  /home/sina/.config/i3/config (main) (last modified: Sun Jun 26 18:57:32 2022, 295 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
