### ISSUE TITLE
enhancement: Allow multiple keys as Metake

### ISSUE THREAD

**Issue by earizon** [i3/i3#3017]
Version: 4.12

Allow two keys (a combination of "two-of-three" -Windows, Alt, space-) to be used as $mod key. This automatically fixes keyboard shortcut collisions with many programs (most notably Windows accessing remote i3 desktops through VNC).

**Comment by earizon** [comment]
The tmux (https://github.com/tmux/tmux/wiki) approach also offers a simple solution to keyboard shortcuts collisions:
In tmux two shortcuts in order are needed:
- First press "Ctrl+b" to indicate a new command.
- Press the command key ('space' to toggle layout, 's' to show a list of sessions, ...)
It's slightly slower than a current i3 shortcuts but still very fast in practice.
(Also, I guess many tmux users will be the firsts to adopt i3 and vice-versa!)

**Comment by stapelberg** [comment]
Thanks for filing the request.

You can already change $mod to evaluate to e.g. Mod4+Mod1 (Windows+Alt).
Regarding the tmux suggestion, you can already define keyboard modes to achieve this effect.

Does that answer your question, or did I miss anything which would need to change on the i3 end?

**Comment by dragon788** [comment]
@stapelberg does evaluating both requiring pressing both as the prefix, or it will use one or the other?

@earizon My concern with mapping multiple keys to the global $mod and all shortcuts (built-in or otherwise) is that i3 appears to exclusively (correctly) capture the mappings if they are defined in it's config, ie if I map <kbd>Ctrl</kbd><kbd>,</kbd> in i3, I can't use that in Chrome to switch between conversations in Hangouts.

What I ended up doing is using <kbd>Win</kbd> aka <kbd>Super</kbd> for $mod, and any shortcuts I also want available with <kbd>Alt</kbd> I define $Mmod as the keycode for <kbd>Alt</kbd> and then simply duplicate the few shortcuts I need both options for with $mod and another line with $Mmod.

```
# i3 config file (v4)
set $mod Mod4
set $Mmod Mod1
set $Cmod Control

bindsym $mod+Shift+grave floating toggle

bindsym $Mmod+grave workspace back_and_forth
bindsym $Cmod+grave workspace back_and_forth

bindsym $mod+comma workspace prev
bindsym $mod+period workspace next
bindsym $Mmod+comma workspace prev
bindsym $Mmod+period workspace next
# Can't do this, it conflicts with Hangouts "prev/next" conversation
#bindsym $Cmod+comma workspace prev
#bindsym $Cmod+period workspace next
```

**Comment by dragon788** [comment]
I like the idea of being able to chord (which appears to be the original request) though I do also like being able to define the direct actions not requiring a prefix (all of which i3 and tmux do quite well). I'll have to test using multiple keys as the $mod, that sounds really useful in some cases (nested i3 in VMs but still being able to manipulate things on the host).

**Comment by stapelberg** [comment]
> @stapelberg does evaluating both requiring pressing both as the prefix, or it will use one or the other?

Both.

If you want either, duplicate your key bindings.

> i3 appears to exclusively (correctly) capture the mappings if they are defined in it's config

Yes, X11 provides no other way (that I’m aware of) to do this.

**Comment by Airblader** [comment]
It sounds like we can close this one. It has become stale and there was no clear result on whether or what to implement.
