### ISSUE TITLE
Feature Request: Monocle mode

### ISSUE THREAD

**Issue by glumanda99** [i3/i3#3121]
> Monocle is good for ensuring a window is kept maximized and focused.

I'm missing dwm's monocle layout in i3wm, where all windows are full size and sit on top of each other. You could then use the `focus up/down` command to cycle through them. It is basically like tabbed mode but without the title bar.

**Comment by Airblader** [comment]
> where all windows are full size and sit on top of each other.

We intentionally don't allow this because we believe that you should have some kind of visual feedback of what is going on.

>  It is basically like tabbed mode but without the title bar.

And specifically because the difference is so small, I don't think this justifies an entirely new layout.

Removing title bars on tabbed / stacked containers has been discussed in the past already, so I'm going to close this.

**Comment by Alkeryn** [comment]
Welp i think it should be there
no one would have to use it but there would be an option to use it
just use a bindsym to toggle monocle mod on the current workspace
really usefull when opening mpv from ranger or having multiple things that you want in fullscreen opened

Really i'm trying to switch from bspwm and monocle mode is a feature i really need

**Comment by glumanda99** [comment]
@Alkeryn One of the downside of monocle layout is, you gonna lose the orientation pretty fast.

**Comment by Alkeryn** [comment]
Welp generally i have a workspace in monocle and it never have more than 3 or 4 windows, i just it for media comptions
And even if i somehow get lost, l can use rofi to list windows

**Comment by astier** [comment]
Missing monocle-layout is the only deal-breaker for me currently. In some cases I just need to be able to maximize a window. Full-screen-mode is not a solution since it removes/hides elements of the program which I need.

**Comment by nlw0** [comment]
Being able to stack without the window titles would be great. I use xmonad but I'm looking to move to i3. Right now we are able to see a window maximized within the workspace, with the top bar, and no title. We can have tiled windows with no title. Then we have stacked and tabbed mode, which does the thing, but introduces window titles, and the change is basically if you want the title as tabs or as a list. Fullscreen mode is useful sometimes, but sometimes you don't want to miss the bar on top. I have a couple of situations where I enjoy having stacked windows that I can switch with "next", but they are all maximized, and the title is taking space I don't want to lose. One example is if I'm developing a gui program, I'm using the shell, but then I call the program from the shell, and I want the window to take over the workspace. I might like to go back to the terminal window, but first of all I want the app on top, maximized, no titles. I could move the terminal to another workspace, but I rather not, because I have other things running in other workspaces. I dedicate each workspace to some topic, these windows are from a same topic. It's just fine to have titles as default and stacked/tabbed mode without titles as an obscure feature, but I would definitely enjoy it.
