### ISSUE TITLE
Feature Request: Allow for iterating "for_window" if its specifier matches multiple window instances

### ISSUE THREAD

**Issue by yapith** [i3/i3#3124]
Output of `i3 --moreversion 2>&- || i3 --version`:
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 2322)
Loaded i3 config: /home/hyapit/.config/i3/config (Last modified: Wed 24 Jan 2018 01:33:11 PM PST, 332846 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per https://i3wm.org/docs/debugging.html:

PROBLEM STATEMENT:
As a user when I open multiple instances of firefox windows,

bindsym $mod+key [class="Firefox"] focus

only focuses on the last firefox window opened when key is pressed. I have to mark the first firefox window in order to navigate to it from across workspaces.

PROPOSAL:
Add a new directive for focus:
iterate
example: bindsym $mod+key [class="Firefox"] focus iterate
description: continuing pressing $mode+key focuses through all firefox windows open starting from the most recently focused to the least recently focused

The buffered stack of recently focused windows is only updated when the $mod key is released.

Alternatives: add a iterate_backward vs iterate_forward for flexibility, but I think this is for an edge-case.

Thanks!

**Comment by Airblader** [comment]
The title and body of this proposal seem to be describing different ideas, but either way this requires yet another stack state within i3. Given the two different proposals, the corresponding response would be:

1. `for_window` is not intended to keep state across messages and we are not looking to change that as it introduces a whole lot of complexity and is a clear breaking change.
2. `focus` is already a complex command and we keep track of the focus stack already. We've had different requests in the past requiring to keep additional stack state that we rejected because it would simply become too complex. This one would be even worse because now the focus command would have to be aware of the match it is applied to, so we're not looking to change this either.

Side note:

> only focuses on the last firefox window opened 

No, it focuses the last matched one. There's no guarantee which one that'll be (apart from implementation details), but `focus` is not a command that makes a whole lot of sense combined with a `for_window` that matches multiple windows (other than perhaps clearing urgency hints or something).
