### ISSUE TITLE
[Feature request] Layout to emulate the dwm default tilling behaivor

### ISSUE THREAD

**Issue by rafaelleru** [i3/i3#3173]
I was wondering if it would be possible to have a new layout with the same behaivor that dwm, this is a main window in the left and a stak of windows in the right, and be able to toggle the main window with the first window in the stack,

**Comment by Airblader** [comment]
Thanks for the issue. We're not really looking to implement such layouts because they're either extremely specific or require a lot of complexity for configuration.

You should be able to achieve this layout using the normal h/v splits, tabbed/stacked containers and utilizing the `swap` command and window marks with a bit of scripting.
