### ISSUE TITLE
Support detectable autorepeat

### ISSUE THREAD

**Issue by MaxNoe** [i3/i3#3306]
## I'm submitting a…

<pre>
[ ] Bug
[X] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I have the following in my `~/.config/i3/config`:
```
bindsym --release $mod+Shift+q kill
```

But the window closes as soon as I press the combination, not just on release.

## Expected Behavior

Close only when keys are released

## Reproduction Instructions

Define a kill binding with `--release` and close a window.

## Environment

<pre>
Running i3 version: 4.15 (2018-03-10) (pid 20806) abort…)
Loaded i3 config: /home/maxnoe/.config/i3/config (Last modified: Mi 06 Jun 2018 14:48:06 CEST, 192 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
- Linux Distribution & Version: Arch
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by orestisf1993** [comment]
Works fine for me. Can you attach a log?

**Comment by MaxNoe** [comment]
Maybe it's keyboard repetition of the `q` letter?

**Comment by orestisf1993** [comment]
This might be fixable: https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html#Detectable_Autorepeat

I made these changes but I still get the release events on my laptop:

```diff
diff --git a/src/main.c b/src/main.c
index de54dbce6..1480a62d3 100644
--- a/src/main.c
+++ b/src/main.c
@@ -653,8 +653,8 @@ int main(int argc, char *argv[]) {
             xcb_xkb_per_client_flags(
                 conn,
                 XCB_XKB_ID_USE_CORE_KBD,
-                XCB_XKB_PER_CLIENT_FLAG_GRABS_USE_XKB_STATE | XCB_XKB_PER_CLIENT_FLAG_LOOKUP_STATE_WHEN_GRABBED,
-                XCB_XKB_PER_CLIENT_FLAG_GRABS_USE_XKB_STATE | XCB_XKB_PER_CLIENT_FLAG_LOOKUP_STATE_WHEN_GRABBED,
+                XCB_XKB_PER_CLIENT_FLAG_GRABS_USE_XKB_STATE | XCB_XKB_PER_CLIENT_FLAG_LOOKUP_STATE_WHEN_GRABBED | XCB_XKB_PER_CLIENT_FLAG_DETECTABLE_AUTO_REPEAT,
+                XCB_XKB_PER_CLIENT_FLAG_GRABS_USE_XKB_STATE | XCB_XKB_PER_CLIENT_FLAG_LOOKUP_STATE_WHEN_GRABBED | XCB_XKB_PER_CLIENT_FLAG_DETECTABLE_AUTO_REPEAT,
                 0 /* uint32_t ctrlsToChange */,
                 0 /* uint32_t autoCtrls */,
                 0 /* uint32_t autoCtrlsValues */),
@@ -667,6 +667,10 @@ int main(int argc, char *argv[]) {
             !(pcf_reply->value & XCB_XKB_PER_CLIENT_FLAG_LOOKUP_STATE_WHEN_GRABBED)) {
             ELOG("Could not set XCB_XKB_PER_CLIENT_FLAG_LOOKUP_STATE_WHEN_GRABBED\n");
         }
+        if (pcf_reply == NULL ||
+            !(pcf_reply->value & XCB_XKB_PER_CLIENT_FLAG_DETECTABLE_AUTO_REPEAT)) {
+            ELOG("Could not set XCB_XKB_PER_CLIENT_FLAG_DETECTABLE_AUTO_REPEAT\n");
+        }
         free(pcf_reply);
         xkb_base = extreply->first_event;
     }
```

@Airblader is this something we want?

**Comment by Airblader** [comment]
Why would we want something that doesn't appear to work? :-) Also, why not just reduce the key repeat?

I don't really see much of a benefit, but do see potential breakage. It'd be easier if this could be done on a per key grab basis so we could expose it as a flag on the binding, but it doesn't appear to be possible.

**Comment by orestisf1993** [comment]
I meant if I get it to work as explained in the documentation.

> Also, why not just reduce the key repeat?

I think it can only be changed globally. Key repeat is meaningful for text input but doesn't make much sense for i3's keybindings.

**Comment by MaxNoe** [comment]
> I think it can only be changed globally. Key repeat is meaningful for text input but doesn't make much sense for i3's keybindings.

This.

I want to have a rather high repetition for typing and moving arrow keys, but it happens quite regularly I close to windows at once because the repetition kicks in.

**Comment by Airblader** [comment]
> but it happens quite regularly I close two windows at once because the repetition kicks in.

How do you manage to not constantly type double letters and arrow keys, but close multiple applications?

I get the sentiment of why key repetition might be less desirable in a window manager, but it's also really only a problem when making your key repeat rate extremely high – which naturally means you need to be quick to release your keys anyway. With a slower repeat rate I can definitely see user relying on this for tabbing through windows etc. We'd be disrupting the behavior they are used to for something which – as it seems to me – is mostly about opinion. If we could somehow make this a configuration, I could get behind it, but if we have to decide on either one of the two, I'm leaning towards not breaking behavior here.

If possible we could think about making it a command line option to i3. It's not super pretty, but I think it might be useful enough to warrant such a solution. A (global) config directive would of course be preferable, but might be more tricky (off the top of my head I don't know in which order things happen right now).

**Comment by Airblader** [comment]
FYI, while it's not possible to modify the repeat rate per key, it *is* possible to turn off key repeat per key. This might also be an option (potentially).

**Comment by MaxNoe** [comment]
> How do you manage to not constantly type double letters and arrow keys, but close multiple applications?

I don't actually know, but maybe because typing and holding down three keys at once is quite different.

**Comment by orestisf1993** [comment]
Update: the patch works in a real xorg server but doesn't work in Xephyr.

Confirmed by awesomewm's relevant git commit message https://github.com/awesomeWM/awesome/commit/6f2424e90170be4acaa1d140f966ab6bb8a4d217

**Comment by fd0** [comment]
Thank you very much for adding this feature, it helps me a lot! The background story is as follows:

 * I'm using an ErgoDox keyboard (with Cherry MX Clear switches)
 * I've got a high repeat rate with a short delay (`xset r rate 180 60`)
 * I'm using [Alacritty](https://github.com/jwilm/alacritty) as my terminal emulator
 * I'm using `bindsym Mod4+Return exec alacritty` to start a terminal

Recently, I noticed that sometimes (roughly one third of all cases) two terminal windows were opened instead of one. This got me thinking: Is maybe the switch broken? After all, Enter is one of the most often used key for me.

So, yesterday I replaced the switch with a brand new one, and nothing happened, it was as bad as before.

Next step: poking around in [my version of the firmware](https://github.com/fd0/ergodox-tmk) for the keyboard. I found many small issues, rewrote the debouncing code (which was awful and blocked the whole keyboard for ~8ms when a key was pressed), increased the keyboard matrix scan rate from ~370Hz to ~950Hz and optimized a few things here and there.

But nothing helped. Then I used another external Dell USB keyboard I had lying around, and there it also happened! The same goes for my internal laptop keyboard... but only if used on a larger screen in the docking station instead of only the internal one.

This got me thinking, I went for a walk and I have a theory what's going on: on the larger screen (when docked) Alacritty started getting slower on startup, so the window is shown only after 200-400ms on my machine. This is larger than the initial delay I've configured for autorepeat (180ms). So it seems it's important for me to get visual feedback that my action ("start the terminal") was noticed by the machine, otherwise I seem to just keep the keys pressed. Which means for a run with a slower startup time for Alacritty, auto repeat kicks in and i3 obediently starts another instance of the terminal. So I end up with two terminals and much confusion.

I've just built i3 4.15 with 6f2424e90170be4acaa1d140f966ab6bb8a4d217 and added `--release` to the `bindsym`, and it works very well so far!
