### ISSUE TITLE
retain the cwd on exec

### ISSUE THREAD

**Issue by 0ax1** [i3/i3#3312]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

`exec` does not retain the current working dir of the focused window. The cwd is always set to `$home`.

## Desired Behavior

Applications can be launched retaining the cwd (e.g. ``bindsym .. exec "terminal --working-directory `pwd`"``). Existing solutions such as `xcwd` do not work all of the time and are somewhat brittle. Ideally, the new behavior would be like `#{pane_current_path}` in `tmux` (e.g. `bind .. split-window -h -c "#{pane_current_path}"`).

## Environment

<pre>
i3 version: 4.15.0.1
</pre>

**Comment by orestisf1993** [comment]
If solutions like xcwd do not work all of the time why would the implementation in i3 work? Why not correct xcwd if the problem is fixable? The problem with xcwd seems to be that if a process opens many windows then they all share the same working directory. A terminal with a client-server model (eg urxvtd) will have the same working directory for all terminals even though the child shell for each terminal window will have its own cwd.

**Comment by Airblader** [comment]
Yes, I asked @0ax1 to report the issue here for discussion. I'm open to implementing this assuming it can be done cleanly and offers improvements over external solutions.

The question is whether we can reliably get the working directory of a window. I'm not really looking to be parsing sysfs for this, to be honest, as this is Linux-specific. If we are to implement this here, we should have a platform-agnostic solution.

**Comment by 0ax1** [comment]
@Airblader Awesome, thanks for giving this a shot.

**Comment by Airblader** [comment]
The question is whether we have a proper way of finding out the cwd. I just read how xcwd does it and we're definitely not going to go down that route. And of course i3 wouldn't be doing anything better than xcwd here. 

Unless there's some protocol / specification that I'm not aware of I don't think there's much we can do here.

**Comment by orestisf1993** [comment]
Another issue would be that software don't necessarily change their cwd because they are "displaying" a folder. For example, thunar, even when you don't launch it as a daemon, doesn't seem to change its cwd when you navigate to a different folder.

**Comment by 0ax1** [comment]
If applications don't set the cwd properly then there's of course no chance of retrieving it. Though, I would consider that an edge case which is not worth dropping the feature for altogether. For the collection of CLI applications I use, I never ran into that issue. tmux always seems to get it right, including for applications like `vifm`. Maybe its worth having a look at their implementation:
- wrapper: https://github.com/tmux/tmux/blob/master/format.c#L534
- OS specific implementations: https://github.com/tmux/tmux/search?q=osdep_get_cwd&unscoped_q=osdep_get_cwd

**Comment by orestisf1993** [comment]
AFAIK, tmux deals with shell processes, it's trivial to find the cwd if you have a process id, eg /proc/<id>/cwd for Linux. Trying to find the process of a window is what xcwd does already.

**Comment by 0ax1** [comment]
Thanks for the clarifying comment. My assumption is that the idea of retaining the cwd to achieve composability of tools primarily makes sense in the context of CLI tools/shell processes. Defaulting to $home if the cwd can't be determined seems reasonable. Regarding shelling out the cwd retrieval to xcwd, it seems the tool needs to do work which i3 already knows from context such as getting the focused window. Further, I don't really see xcwd used in this context as composition of tools but to patch desired functionality into i3.

**Comment by Airblader** [comment]
I'd disagree with that. It provides functionality in a window manager independent way, meaning it works across different setups. Getting the focused window is really easy, that's exactly how X and the specs were designed.

If an external tool can do this just as well as i3 could, I don't see a good reason to not use the external tool for this particular feature. It's the same reason I built xedgewarp as am external tool :-)

**Comment by Airblader** [comment]
> So this means the way the cwd for the focused window is obtained is basically the same across all wms in context of X.

There's a few different ways of how you define the »currently focused window« in X, and depending on that different ways to get to it. But whatever you define as it, yes, there is a way to find out which window is focused in a window manager independent way (otherwise the X world would be a much, much worse place). 

> Out of interest, do you know if Wayland enables a robust solution to this problem?

I don't, but I think it's worth pointing out that this isn't really a display server / window management problem. The concept of a working directory is orthogonal to the concept of managing and displaying windows. It's just a concept UNIX-based systems seem to share (don't quote me on that). The typical way to go about this would be to standardize a way to get this information in a specification (much like EWMH and ICCCM) so that all window managers (and tools) can rely on it.

At least under X the process of adding something to a specification is so hopeless, though, that I wouldn't waste even a second even seriously considering it. Even if you did get it in, it'd probably be years if not decades before you'd have it supported in the wild. Unfortunately. We could do so many cool things if only standardization worked better. Wayland seems to be much more active here (again, though, don't quote me on it), but even Wayland is about a decade old now and still not widely adopted (though certainly moving faster than X these days).

**Comment by orestisf1993** [comment]
You might find an application-specific solution for what you want to do. For urxvt I use the following:

- https://github.com/orestisf1993/dotfiles/blob/8ea8c5cf5b0cc69c7444aff334688260a745654b/urxvt/.config/urxvt.xres#L27 which uses this extension https://github.com/myeisha/urxvt-fork-here
- This script https://github.com/orestisf1993/dotfiles/blob/b0dedb12c7466ef5ce41776e99d3a96fdc6c81d9/executables/bin/urxvtc-cwd.sh
- This binding https://github.com/orestisf1993/dotfiles/blob/8ea8c5cf5b0cc69c7444aff334688260a745654b/i3/.i3/include/99.bindsym.config#L5

**Comment by 0ax1** [comment]
> I think it's worth pointing out that this isn't really a display server / window management problem.

Coming from tmux, I simply assumed wms would also provide the feature, even if it is restricted to shell processes. Sometimes it is surprising a feature is 'missing' if it was previously crucial to your workflow.

> (don't quote me on that)

Nah, I won't .. ah too late.

> The typical way to go about this would be to standardize a way to get this information in a specification

It would be really nice if such standard would exist. Thanks for your thoughts on this.

@orestisf1993 Nice, I'll look into these. Further, I found out that the terminal I use also provides its own solution to the problem: https://github.com/jwilm/alacritty/blob/master/scripts/spawn-alacritty-cwd. I might go with that for the moment.

**Comment by rht** [comment]
Here is a specific solution for Kitty. Posting it here for visibility
```sh
#!/usr/bin/env sh

PID=$(pstree -p "$(xdotool getwindowfocus getwindowpid)" | rg -m 1 -o '\-zsh\(\d+\)' | rg -o '\d+')
exec kitty --directory "$(readlink /proc/$PID/cwd)"
```
`xcwd` doesn't work with i3+Kitty, because `xcwd` only gets the last child process of the current window. What I did here is to simply grep the first occurrence of the `zsh` process of the child of the window.
