### ISSUE TITLE
Respect resize requests for scratchpad windows

### ISSUE THREAD

**Issue by cdlscpmv** [i3/i3#3318]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When a window in i3's scratchpad tries to resize itself, the request is not honored by i3. Looking at the code, the behavior is expected. My question is why this might be necessary? And can the behavior possibly be changed either by directly removing the special treatment for scratchpad
windows, or by introducing a new setting to disable it?

## Expected Behavior

The request should be honored.

## Use case

Often times, when listeting to music, I put mpv in the scratchpad. mpv (using `--force-window-position`) tries to resize its window when switching between playlist entries to adjust to the current video's aspect ratio. Otherwise, when the window always has a fixed size, I get black
bars either on the sides or on the top and the bottom.

**Comment by Airblader** [comment]
Hi, thanks for filing this issue.

As you pointed out, this behavior is intentional. The rationale here is that the scratchpad isn't an accessible workspace, so essentially it's the closest to having minimized or unmapped windows (without actually unmapping them). Having things like resizing happen in this state is counter-intuitive and can just lead to confusing situations.

> directly removing the special treatment

This would go against the purpose of it, and also be a breaking change.

> introducing a new setting to disable it

While I understand your specific usecase, I think configuration for this would be a bit overkill. I would suggest you instead ensure the window reiszes when you get it back from the scratchpad (in particular since you'd want to change it for windows of a specific application only anyway).

Thanks for understanding!
