### ISSUE TITLE
Enhancehement: Render left and right borders of titles in stacked mode

### ISSUE THREAD

**Issue by aksel** [i3/i3#3412]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I'm using pixel borders.

Stacking vs tabbed mode renders the title borders of the focused container in different manners, and inconsistently with regards to child borders.

[These two images](https://imgur.com/a/LU5b5e7) show the differences. Tabbed render a border all around the title, whereas stacked stop at the child border.

[In this image](https://i.imgur.com/AiawCYd.png), I have increased the border to exaggerate the effect. You can see, in addition to the left and right borders of the stacked title missing, the lower horizontal border stops at the child border, with 1 pixel missing at the edges.

```
Current, tabbed: 

╔══════╗──────┬──────┐
║ tab1 ║ tab2 │ tab3 │
╠══════╝─────────────╖
║                    ║
╚════════════════════╝

Current, stacked:
┌────────────────────┐   ┌────────────────────┐
│ stack1             │   │ stack1             │
├────────────────────┤   ├════════════════════┤
│ stack2             │   │ stack 2 (focused)  │
├════════════════════┤   ├════════════════════┤
│ stack 3 (focused)  │   │ stack3             │
├════════════════════┤   ╓────────────────────╖
║                    ║   ║                    ║
║                    ║   ║                    ║
╚════════════════════╝   ╚════════════════════╝
```

## Expected Behavior
```
Desired, stacked:
┌────────────────────┐   ┌────────────────────┐
│ stack1             │   │ stack1             │
├────────────────────┤   ╔════════════════════╗
│ stack2             │   ║ stack 2 (focused)  ║
╔════════════════════╗   ╚════════════════════╝
║ stack 3 (focused)  ║   │ stack3             │
╠════════════════════╣   ╓────────────────────╖
║                    ║   ║                    ║
║                    ║   ║                    ║
╚════════════════════╝   ╚════════════════════╝
```

Borders should be rendered all around around the focused title.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 

Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 601)bort…)
Loaded i3 config: /home/aksel/.config/i3/config (Last modified: mán 17 sep 2018 22:25:17 CEST, 1641 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

Note, I'm using i3-gaps, but I don't think this issue is related to gaps.

<pre>
- Linux Distribution & Version: Arch Linux, 4.18.6
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

**Comment by Airblader** [comment]
Makes sense to me.

**Comment by xzfc** [comment]
# History

Inner vertical separators for tabbed layout was introduced in the ancient commit fa83b46dfa8c77130ed1225ac70aa6482967ea61 to make tabs easily distinguished.

Then in the ancient commit 79bd2aede5aba10d7841db717e60736c90ffe130 the outer borders for tabbed layout was added as a side-effect of fixing bug #894.
Stacked, vertical, and horizontal layouts don't have such borders.

## My proposal

Adding such borders to the stacking layout would require also adding it to all other layouts (otherwise they will still not be  consistent).
Personally I don't like this change because it will affect how almost every window border looks.

Maybe instead we should remove outer vertical borders from the tabbed layout, preserving internal separators?
This change is not so intrusive, but it makes outer borders of all layouts look consistent, and still serves the purpose of fa83b46dfa8c77130ed1225ac70aa6482967ea61.

## Mockups

* [ Current state ]( http://dump.bitcheese.net/files/pymyvel/0-current.png )
* [ Add border to stacking ]( http://dump.bitcheese.net/files/vezypaz/1-stacked.png )
* [ Add border to all layouts ]( http://dump.bitcheese.net/files/dyguwun/2-all.png )
* [ Remove outer border from tabbed (my proposal) ]( http://dump.bitcheese.net/files/higenaw/3-without-outer-tabbed.png )

**Comment by Airblader** [comment]
@stapelberg Do you have a preference here? I can see an argument for either way.

**Comment by stapelberg** [comment]
No preference from my end.

**Comment by xzfc** [comment]
Well, I rethought it now and would prefer it too.

**Comment by Airblader** [comment]
@xzfc Would you like to update your PR then?

**Comment by xzfc** [comment]
@Airblader Updated.

**Comment by Airblader** [comment]
Merged!
