### ISSUE TITLE
Show window titles only when mod key is pressed (tab mode)

### ISSUE THREAD

**Issue by usernamenumber** [i3/i3#3468]
Note: this is not a duplicate of #1391 because I'm not advocating for complete removal of titles, I just only want them to take up space when relevant i.e. when I press the mod key. Essentially I want the titles in tab mode to behave the way the menu bar does when 'alt' is pressed. 

## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
In tab mode, the top of the screen is always taken up with tab titles

## Desired Behavior
By default that space is used for window content, until the meta key is pressed, at which point the titles appear. 

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 1567)
Loaded i3 config: /home/ANT.AMAZON.COM/smibrd/.i3/config (Last modified: Thu 18 Oct 2018 11:45:59 PM EDT, 218556 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
- Linux Distribution & Version: Ubuntu 16
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

**Comment by Airblader** [comment]
Thanks for filing the issue, but the main concern stated in the referenced issue still stands here as well: the loss of visual information about the structure. 

Another downside here is that any mod key press (including when wanting to resize or even do something inside the application itself) would cause a visual change and the window to resize.

This I think we have to reject this as well. Thanks for understanding!

**Comment by usernamenumber** [comment]
It's your call, but something to consider? What if you simply overlaid the tab titles over the top of the windows without re-sizing them? The information isn't being lost so much as only shown when it actually helps to do so.

**Comment by Airblader** [comment]
The point of the visual cue is to know that there is a tabbed container. To use the shortcut, you'd already have to know that it is one, which defeats the purpose of the visual cue.

**Comment by FabriceCh** [comment]
I too would be interested in such a behavior, maybe in a form of setting we can set. Like "smart titles on|off", defaults to off. 

For the loss of visual cue, if the titles would appear when pressing mod and if they would show the same way they already are in tab/stack mode, then I think the visual cue would be enough (you would only have it when pressing mod). And because it would be a non-default settings I think the loss of visual cue is less important, the user choosing such a setting would know what to expect and understand it will impact the visual cue.
 
Just wanted to show my interest in this, I don't think you should completely reject the feature.

**Comment by jeyj0** [comment]
I am also totally in favor of this. The visual cue is not as important if this feature is opt-in, IMO. 
I'd also want it to overlay the title-bars, not display them the "normal" way (which would cause a redraw).
I don't see how this feature would impact any users other than those who want to opt-in, if it was "hidden" behind an option.

**Comment by NICHTJ3** [comment]
I would also appreciate this feature as it the tab bar fills in a lot of the available window space. there are other ways to know what you applications you have open if that is a concern

**Comment by niraj-khatiwada** [comment]
> Thanks for filing the issue, but the main concern stated in the referenced issue still stands here as well: the loss of visual information about the structure.
> 
> Another downside here is that any mod key press (including when wanting to resize or even do something inside the application itself) would cause a visual change and the window to resize.
> 
> This I think we have to reject this as well. Thanks for understanding!

If this was the case for tabbed layout, then why does i3 support toggle mode for bar when mod key is pressed/released? It also causes loss of visual information about the workspace. 
And, just like the bar which is absolutely positioned on top of windows, the toggling the tab bar won't cause cause any layout shift since it'll be absolutely positioned. I thought this was definitely possible but here we are.
