### ISSUE TITLE
Introduce a command to delete a container but not its children

### ISSUE THREAD

**Issue by ilikeheaps** [i3/i3#3500]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior
You could bind command that would remove a container but move all its children to its parent (with as little changes to perceived layout as possible: e.g. removing inner H from H[W1 H[W2 W3]] shouldn't change the placement of windows -- I'm not sure how that example interacts with tree_flatten though).

## Motivation
Moving windows to sides to delete a stack container seems roundabout. Also with current implementation of tree_flatten you sometimes have chains of containers and you'd have to move each child out of the chain individually to get rid of the chain.

## Other
I've got a draft of solution that kinda works (WIP, messes up the order and sizes of containers) which I'll make a PR for if this issue is accepted.

**Comment by Airblader** [comment]
Can't this be implemented trivially as an IPC script? Get children of the focused container and move them (wherever you want)?

**Comment by ilikeheaps** [comment]
I actually don't know, first thing I tried was C code because I was investigating `tree_flatten` at the same time. I suppose I could do it through IPC indeed. One point for including it in the base code is that I use these functions in `tree_flatten` rework (but that's only if I get it to acceptable state) - from there it's just a matter of making a little wrapper. I guess I'll try IPC route anyway in case my flatten rework isn't accepted.

**Comment by Airblader** [comment]
Can we try to implement this using the IPC for now? If that turns out to be impossible, we could revisit. At the moment I'm not convinced that this is worth adding a new command yet.

**Comment by ilikeheaps** [comment]
Alright, if this is too niche functionality to be included in base i3, this issue can be closed. It just felt to me that this is an operation basic enough that one would expect it out of the box.

**Comment by CarloWood** [comment]
> Alright, if this is too niche functionality to be included in base i3, this issue can be closed. It just felt to me that this is an operation basic enough that one would expect it out of the box.

I switched from plasma to i3 today - and the first really annoying bug that I ran into, the very same day, is that implicit containers can pollute your tree without even being visible. I quickly end up with -say- three windows next to each other, looking like a single H-container with three windows, but actually being something different (which you can't see until you try things).

I went looking for the obvious command to get rid of invisible implicit containers down the tree (ie, select window X, press $mod-f and have the parent and everything it contains be "flattened", meaning that containers with a single child are removed in a way that the layout on the screen isn't changed). But all I find are (many) posts of other people with the same request who then get beaten down by the maintainers as "won't implement because ...". Seems to me there not just a lot of demand for this, but I also understand why nobody else dares to request it again ;).
