### ISSUE TITLE
Allow drag stacked/tabbed cons by its title

### ISSUE THREAD

**Issue by xzfc** [i3/i3#3555]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

* Can't drag title to resize in the following layout: `V[w T[w w]]`.
* Can't drag to move floating tabbed con without using floating_modifier.

More detailed, it is not currently allowed to drag con by its title in some cases:
* Vertical resize tiled con by dragging its title:
  * leaf container or container with single child: allowed
  * vsplit: allowed
  * hsplit: **disallowed**
  * tabbed or stacked: **disallowed**
* Move floating con by dragging its title:
  * hsplit or vsplit: allowed
  * tabbed or stacked: **disallowed**

The reason why is that both of the following actions are bound to a mouse button, and i3 needs to distinguish them:
* activate con
* initiate moving/resizing drag

## My proposal

1. Allow dragging an active title regardless of the con type.
   When an user clicked on an active title, they're clearly want to drag the con since it's already activated.

2. Allow dragging an inactive title, but use drag threshold.
   This is the same way as GUI toolkits handle drags. For example see how Firefox or Chromium handles dragging tab.

## Implementation

I'm going to implement this in #3545 or in separate PR, but just want to make sure it'll be accepted.

i3 version 4.16

**Comment by Airblader** [comment]
> Can't drag title to resize in the following layout: `V[w T[w w]]`.

At first glance I can't think of a reason not to allow it; I'm guessing it doesn't work at the moment due to the fact that left clicks are used for focusing a tab, but resize is right click anyway.

> Can't drag to move floating tabbed con without using floating_modifier.

We don't actually intentionally support floating such containers in the first place, thus I wouldn't want to add complexity to make this work.

> Vertical resize tiled con by dragging its title: […] hsplit: disallowed

Yeah, can't think of a reason right now why that shouldn't work. It feels like the expected behavior that it would work.

---

Your first proposal sounds fine, I'm also inclined to accept the second one as it improves usability, but for that one in particular I wouldn't mind some more opinions like from @orestisf1993 and maybe @stapelberg.

**Comment by stapelberg** [comment]
> Your first proposal sounds fine, I'm also inclined to accept the second one as it improves usability, but for that one in particular I wouldn't mind some more opinions like from @orestisf1993 and maybe @stapelberg.

You’re referring to “Allow dragging an inactive title, but use drag threshold.”, yes? That seems fine to me.

**Comment by Airblader** [comment]
Yes, that's what I meant. Great, tagging it accepted then.
