### ISSUE TITLE
Graphical output in i3bar

### ISSUE THREAD

**Issue by aioobe** [i3/i3#3578]
## I'm submitting a…
<pre>
[x] Feature Request
</pre>

## Current Behavior
i3bar is only capable of displaying text. Unicode icon "characters" only get you so far.

## Desired Behavior

I'd love to be able to show custom graphics. Primarily to be able to have something like the [gnome shell system monitor applet](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet).

I think one would even be able to stick with the text based interface and use base64 encoded png files. We're talking <few pixels> × <few pixels> images anyway.

Please let me know if this is something doable

**Comment by Airblader** [comment]
I don't think we'd want to extend the protocol much to make this work, but the idea of sending some base64 encoded stream is at least interesting. I'd be somewhat concerned wiith the performance of this, though, and things like text width prediction would have to be changed etc.

I'm currently not decided on this; my initial response would be to reject this since it doesn't really fit the look&feel of i3 that stays away from graphics. We can certainly keep the issue open for now, though.

There certainly are much more advanced and feature-rich bar applications out there where this would fit much, much better (if they can't already do it anyway – I haven't followed polybar in a while).

**Comment by anarcat** [comment]
couldn't this be a matter of "simply" allowing some metrics to be graphed using a simple timed histogram? the way i use this feature in (say) taffybar right now is with the cpu metric: there's a square box that gets filled from left to right over a 30 second window. 100% is a full bar, 0% is nothing. it looks like this:

![image](https://user-images.githubusercontent.com/796623/71224318-969b5f80-22a3-11ea-8527-2ad6b104af25.png)

here CPU usage just starting rising in the last few seconds, but was generally quiet in the last 30 seconds. memory usage has been steady in the last 30 seconds. in taffybar you can pick the length of time you wish for the graph as well.

any metric could be plotted like this, and i wouldn't make the caller plot the metrics. it's just a way to display output...

would that make sense?

**Comment by Airblader** [comment]
No, because it isn't as easy as it sounds and we'd quickly have to add a dozen or so options (min, max, time frame, colors, ...). It'd also be a significant shift as i3bar would suddenly have to actually keep track of data over time. It'd be even more difficult because we can receive an update at any point in time and therefore actual bucketing would be involved etc etc etc.

**Comment by orestisfl** [comment]
Closing because of extra complexity and the existence of third-party alternatives

> We are generally happy with the current feature set of i3 and instead focus on maintenance such as stability and fixing bugs. New features will rarely be considered if they require additional configuration and/or commands, or if they add significant complexity (either through the exposed configuration or mental complexity) to the project.

https://github.com/i3/i3/blob/next/.github/CONTRIBUTING.md

**Comment by anarcat** [comment]
thanks for the response and support in any case! :)
