### ISSUE TITLE
How to fork i3bar?

### ISSUE THREAD

**Issue by kgilmer** [i3/i3#3626]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
i3bar is directly integrated into the core i3 source tree.  There is obviously separation between the two systems, however the i3bar does reference code from the root tree (for example, configuration code).

## Desired Behavior
I am experimenting with features to i3bar unlikely to be desired by the greater community.  However I'd still like to be able to:
1. continue to track upstream changes from the i3 code repo easily
2. remove all non-i3bar files so that my builds and repo only has things necessary to compile i3bar
3. maintain runtime compatibility with i3bar (assuming I don't make breaking changes)

I can just go in and remove entries from the Makefile and so forth but am wondering if there is a specific approach that will let me realize these 3 goals.

**Comment by Airblader** [comment]
Hi,

I don't understand why you need to strip it at all. Just make your changes to a local fork of the repository. Since those changes only affect i3bar, the only potential for conflicts is in i3bar, everything else about i3 would always rebase without issues.

You could still decide to install only the patched i3bar and get i3 from upstream still, or you could install everything from the fork. I'd probably choose the latter anyway, but it's up to you; either way I don't really see an issue with that.

If you really do want to strip down the build to only i3bar you can of course change the build infrastructure locally, but to gain a couple of seconds of build speed you''d be subjecting yourself to a substantially bigger risk of conflicts during rebasing.

**Comment by kgilmer** [comment]
Thanks @Airblader, yes there's nothing wrong with the workflow that you propose, other than that I plan to package and distribute it via a PPA.  I would prefer the sources in this package to purely be for my forked i3bar, and obviously it would need a different name.  It may not get to that as my C skills are super rusty atm.  Cheers :+1:
