### ISSUE TITLE
'bindsym Caps_Lock' won't execute if a modifier is pressed

### ISSUE THREAD

**Issue by jvc2** [i3/i3#3662]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

The line `bindsym --release Caps_Lock exec notify-send "caps lock pressed"` will only send a notification when caps lock is pressed by itself, without any modifiers. I often mean to press $mod+Shift and press $mod+Caps_Lock by accident, which turns on caps lock without notifying. I can add the line `bindsym --release $mod+Caps_Lock exec {command}` but I would also need an additional line for every combination of modifiers that could be accidentally pressed such as Control+Caps_Lock, Shift+Caps_Lock, Control+Mod1+Caps_Lock, etc which is inconvenient.

## Desired Behavior

I want to execute a command whenever caps lock is pressed, regardless of whether any modifiers are pressed with it. There doesn't seem to be a way to do that with bindsym.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

<pre>
- Linux Distribution & Version: Arch 5.0.4-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): compton
</pre>

**Comment by Airblader** [comment]
Thanks for opening this issue. So to clarify: it's of course *intentional* that modifiers are respected. Your description reads more like a bug report, but I assume the requested feature here is some `--ignore-modifiers` flag, right?

Off the top of my head I'm not convinced the use-case is strong enough; I can't see such a flag being useful in other usages, and for your concrete problem you might as well just use

```
setxkbmap -option ctrl:nocaps
```

to disable the caps lock key. Personally I do this as well and then bind caps lock to something more useful.

**Comment by jvc2** [comment]
Yes, a flag like `--ignore-modifiers` is what I was requesting, sorry for not making that very clear. But the simpler alternative of having caps lock disabled hadn't crossed my mind, thanks for the suggestion.

**Comment by ui3o** [comment]
Sorry to ask, but what was the solution?

For me this does not work:
bindsym Caps_Lock --release --ignore-modifiers exec notify-send "caps lock pressed"

**Comment by Airblader** [comment]
No change was made in i3 for this.

**Comment by ui3o** [comment]
Thanks. Do you know when will it be released?

**Comment by Airblader** [comment]
Again, no change was made, so there is nothing to release. This feature has not been implemented.

**Comment by ui3o** [comment]
Thanks
