### ISSUE TITLE
Support custom height for i3bar

### ISSUE THREAD

**Issue by Airblader** [i3/i3#3721]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior

The i3bar config should support a `height` configuration that specifies the height of i3bar. This should work exactly as in i3-gaps (in fact, ideally we'd just migrate the feature from there).

*Edit:* As discussed, let's instead make this a `vertical_padding` kind of option rather than an exact height.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.16.1
</pre>

**Comment by stapelberg** [comment]
I’m not saying I’m against this, but can you explain a little more what the use case is? Currently, the height is derived from the font size. If the height is increased, does that influence the font size? If not, what is displayed in the extra space?

**Comment by Airblader** [comment]
I think originally I added the height because of the custom border widths on status blocks (see issue https://github.com/i3/i3/issues/3722) to avoid overlapping the borders and the text. I've also seen people use it simply to make their bars taller or thinner according to preference. All content is simply vertically centered within the bar. It has no effect on font size (that would defeat the purpose, we might as well change the font size then).

A possible alternative approach to `height` would be a user-defined vertical padding of the bar, that might more accurately reflect its idea and somewhat reduce the dependency between font size and height.

**Comment by stapelberg** [comment]
> A possible alternative approach to `height` would be a user-defined vertical padding of the bar, that might more accurately reflect its idea and somewhat reduce the dependency between font size and height.

I think I’d prefer this approach over the height approach.

**Comment by stapelberg** [comment]
Attempting backwards compatibility as you outlined seems fine to me.

**Comment by Airblader** [comment]
@stapelberg Another thought: ideally we could get package maintainers to merge i3-gaps packages into the i3 package, but in doing so if i3 has no `height`, it's a breaking change no matter what compat approach I take in i3-gaps for the time being. Hm…

**Comment by skontar** [comment]
Hi. This is my most favourite feature from gaps. It allows me to have reasonably big tray icons and workspace buttons with a smaller text and bit of padding everywhere.

I use something like:
```
    font pango: FontAwesome, Hack 11.5
    height 32
```
The result then is something like this:
![Screenshot_2019-06-18_10-58-14](https://user-images.githubusercontent.com/10827040/59668001-00816200-91b8-11e9-92ea-79eb02fc3292.png)

In normal i3 I could only get either:
```
    font pango: FontAwesome, Hack 11.5
```
![Screenshot_2019-06-18_11-00-38](https://user-images.githubusercontent.com/10827040/59668371-acc34880-91b8-11e9-9709-2ff27c4c4e22.png)

or
```
    font pango: FontAwesome, Hack 16
```
![Screenshot_2019-06-18_11-00-54](https://user-images.githubusercontent.com/10827040/59668386-b187fc80-91b8-11e9-99e0-b7de829bb92d.png)

Thanks for considering this feature!

**Comment by stapelberg** [comment]
> @stapelberg Another thought: ideally we could get package maintainers to merge i3-gaps packages into the i3 package, but in doing so if i3 has no `height`, it's a breaking change no matter what compat approach I take in i3-gaps for the time being. Hm…

Sorry, maybe I wasn’t clear enough: I was saying that compatibility within i3 (not i3-gaps) is okay with me, specifically so that i3-gaps users can easily switch over.

**Comment by cdlscpmv** [comment]
I think the option name should be left as `height`, because it allows for more granullarity over the bar height. If I understand this right, the `vertical_padding` option will always add an en equal amount of pixels above and below the text, which will always add an even number of pixels to the bar height.

**Comment by MartinodF** [comment]
I would also need this feature to switch from i3-gaps back to i3. The default bar is simply too small for me, impairing the legibility of its contents because of how near they are to the screen border (which is slightly beveled on my monitor). Moreover, as a matter of personal preference, it just looks better with a slight padding.

We can control the size of pretty much anything in i3 (such as window borders), I don't see why the status bar height shouldn't be configurable. I would be ok with both `height` and `vertical_padding`, though I have a slight preference for the latter since it allows for changing the font size without having to modify the height.

As mentioned in Airblader/i3#319, this should also respect the DPI scaling of the monitor. I understand the change is a simple one-liner, which @Airblader already detailed in the mentioned issue.

Thank you for the time you spend improving i3!

**Comment by ShimmerGlass** [comment]
Hello, I have an implementation for that in my fork (drafted in https://github.com/i3/i3/pull/4288) and wanted to clarify a few points. My change does 3 things :
1. Sets the height of the bar (I'm ok with changing this to `vertical_padding`, but see points below)
2. Sets an horizontal padding of `(bar_height - font_size) / 2)` as well, because it is weird (and ugly IMO) having space on top and bottom of the bar but the text squished on the right
3. Sets a min-width to workspace buttons equal to the bar height, to keep the buttons nice and square (especially for digits-only workspaces) as the bar gets bigger.

Point 3. is arguable, and I am ok dropping it altho the bar looks better with it IMO. I would argue however that point 2. should be included to keep the bar aesthetically pleasing with increased height.

This is why I settled with a `bar { height }` setting rather than `bar { vertical_padding }` at the time, because it does more than that.

Questions :
* How does i3-gaps implement this?
* Do you agree with points 2. and 3. ? Some? None of them?
* Considering a possible approval of points 2. and/or 3., we could rename the setting to just `padding`. What do you think?

**Comment by stapelberg** [comment]
Sorry for the late reply.

I think it might make sense to name this feature `padding` (not just the more narrowly scoped `vertical_padding`), and allow to configure left/right/top/bottom padding individually, or to the same value as a shorthand (`padding 2px` would mean 2px on all sides).

We should use the same order of left/right/top/bottom as CSS does for its margin/padding parameters. 

Ensuring numbered workspace buttons end up square sounds good to me, provided that named workspace buttons are not negatively affected.

**Comment by stapelberg** [comment]
I’ll take a stab at this as part of https://github.com/i3/i3/issues/3724 (merging i3-gaps)

**Comment by Airblader** [comment]
Is there any way we can do this in a way that existing i3-gaps configs stay valid? If not or if it's too much effort I think it'd be OK to omit it and just document how to migrate, but we usually try to avoid breakage between releases, and for users the switch will just be an update when distros replace the i3-gaps package.

**Comment by stapelberg** [comment]
> Is there any way we can do this in a way that existing i3-gaps configs stay valid?

Yes, that’s what I’m currently trying. Let’s see how it goes :)

**Comment by stapelberg** [comment]
> Ensuring numbered workspace buttons end up square sounds good to me, provided that named workspace buttons are not negatively affected.

Feel free to send a separate PR for this. But note that we already have `workspace_min_width`, which might be sufficient.
