### ISSUE TITLE
Idea: recent windows selector

### ISSUE THREAD

**Issue by fvigotti** [i3/i3#3850]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

An idea: I find very useful in intellij to navigate between recent files with a shortcut..
I often have 7/8 desktops with about ~10 windows each on two 4k monitors 32" with different tiling in each windows/desktop according to opened application at given time, 

**I would find very useful a shortcut which open a popup that let me chose (with arrow keys) between  the recent used 10 windows ( windows where I've been for at least 30" in order of recent usage )** once the window is chosen , just bring me to that windows ( without changing monitor associated with it), just move mouse focus on correct monitor then open the correct desktop and show the window according to the current tiling setup without changing it.

**Comment by Airblader** [comment]
i3 does not keep a list of recently focused windows, and such a list can easily be maintained outside of it. I think this is a use-case better suited for external software (since it's also a WM-independent problem). There already are a bunch of tools like this, for example dmenu or rofi.

I don't think we'll want to add this directly to i3 since it just seems unnecessary. Thanks for understanding. :-)

**Comment by fvigotti** [comment]
Sure I understand :) I just didn't know where to submith such feature, maybe some developer of "external software" scrape your issue list for ideas and here it is :) Have a nice day!

**Comment by orestisfl** [comment]
Also see https://github.com/sagb/alttab

**Comment by Airblader** [comment]
@fvigotti This is such a common task that there already is plenty of software, as I mentioned rofi and @orestisfl's suggestion.
