### ISSUE TITLE
"Undecorate maximized windows" on Ubuntu MATE breaks borders

### ISSUE THREAD

**Issue by maciejmotyka** [i3/i3#3853]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When using i3 with MATE desktop on Ubuntu 19.10, if "Undecorate maximized windows" in `MATE Tweak` (corresponds to `/org/mate/maximus/undecorate` in `dconf`) is turned on, borders in tiling mode are not drawn. Setting `for_window [class=".*"] border pixel 1` resolves it, but only partially and only for existing windows.

## Desired Behavior

It could be mentioned in "Known issues" or in some other adequate place in documentation. If not, please close and hopefully this issue saves someone's time.

## Environment

<pre>
i3 version: 4.17.1
</pre>

<pre>
- Linux Distribution & Version: Ubuntu MATE 19.10
- Are you using a compositor (e.g., xcompmgr or compton): No
</pre>

**Comment by Airblader** [comment]
I'm not sure I understand the issue — undecorate means exactly that. If this is about "maximized" versus "tiling" I believe this should be reported to MATE (?)

**Comment by xzfc** [comment]
If I recall correctly, maximus is a utility daemon that automatically makes all windows maximized by default. It is intended to be used with floating window managers, and probably it makes no sense to use maximus with i3.

**Comment by maciejmotyka** [comment]
> I'm not sure I understand the issue — undecorate means exactly that. If this is about "maximized" versus "tiling" I believe this should be reported to MATE (?)

I will report it to MATE. My intention behind reporting it here was to help potential Ubuntu users, who want to use i3 as their WM and might happen to have this option enabled. It took me quite some time to track it down.

> If I recall correctly, maximus is a utility daemon that automatically makes all windows maximized by default. It is intended to be used with floating window managers, and probably it makes no sense to use maximus with i3.

Agree, but not every user will make connection between misbehaving borders with maximus, so it's worth documenting this imho.

**Comment by Airblader** [comment]
I get the intention, but documenting every incompatibility or limitation with any other 
 third party software as a "known issue" isn't really feasible, either. Having this documented as an issue on Github probably already has more visibility for users looking for an answer than a section in the man page ever would. :-) 

In fact this isn't even an "issue" on our side at all, IMHO. i3 does not claim to support maximization (on protocol level). It sounds a bit like some piece of software assumes that maximizing a window will be successful rather than waiting for the response from the window manager.

**Comment by maciejmotyka** [comment]
Fair enough.
