### ISSUE TITLE
Stacks that look like tabs

### ISSUE THREAD

**Issue by Al-Caveman** [i3/i3#3857]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Stacks are piles of stupid little windows, stacked vertically, that we can navigate them ONLY vertically.

Tabs are piles of less stupid little windows, stacked horizontally, that we can navigate them ONLY horizontally.

## Desired Behavior
For the love of sinless kittens that are dying every time a pixel is wasted.  For the love of green grass and the singing birds. Give us this option:

* Option to navigate tabs by vertical movement (i.e. stacks that look like tabs).

This is my compromise as my request here #3738 got ignored.  So, I hope that you will at least accept this simpler compromise.

I think it is easy to add this feature (vertically-nagivated tabs), and it is easy to achieve backwards compatibility of current configs.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1
</pre>

**Comment by Airblader** [comment]
What's the actual benefit of this proposal? It just replaces one visually intuitive ky binding with another, visually non-intuitive binding. I'm not sure I see what this would gain.

**Comment by Al-Caveman** [comment]
Which one do you use most?

* Stacks.
* Tabs.
* Others (please specify).

And why?

**Comment by Airblader** [comment]
Apart from normal splits I personally use exclusively stacked containers which are related (browser, terminals, email) and give them a lot of space. The reason I don't use tabs is because of long titles and because I don't mind the space loss. I personally also rarely ever nest such containers. 

But my personal preference isn't the issue. I'm ok with it not benefitting me personally, you're the one proposing it so I'd like to know what you hole to gain from it. :-)

**Comment by Airblader** [comment]
For the record, the other issue has not been closed or denied — we just aren't happy with the approach yet. The last proposal you made there simply hasn't been responded to yet.

I prefer your latest proposal over there over this proposal here. It's cleaner and more flexible. The only question is whether the added complexity is justified.

**Comment by Al-Caveman** [comment]
About "because of long tiles", I don't see how is "long tiles" a "because".  Do you mean, you like long title bars because it allows for more title texts to be visible thanks to the title bars being longer with stacks than tabs, hence allowing for more title texts?

If that's the case, then I think it's a good point, but IMO what would be even better is having variable-length tabs (instead of constantly using full-width title bars (aka stacks)).  Once a tabs line gets full, a new tabs row can appear underneath it.  This variable-length tabs could have parameters that allow us to choose how much to squeeze too-long title bars.

----

About you preferring the latest proposal in #3738.  I agree.  If latest in #3738 is solved, I would not care about this solution in this feature request.  I just proposed this as I felt that the other is ignored.

**Comment by Airblader** [comment]
> Do you mean, you like long title bars because it allows for more title texts to be visible thanks to the title bars being longer with stacks than tabs, hence allowing for more title texts?

Yes. Many people prefer i3 to save screen estate, and that's fine. But i3 is good at many other things and I myself have a lot of screen estate and keep workspaces simple. I prefer legibility. :-)

> what would be even better is having variable-length tabs (instead of constantly using full-width title bars (aka stacks)). Once a tabs line gets full, a new tabs row can appear underneath it.

I agree that that sounds useful, but it would require a whole new layout I believe. I'm fairly sure we have another issue where this has been discussed.

> I just proposed this as I felt that the other is ignored.

I apologize for that, it's not my (or our) intention to give that impression, but often real life gets in the way of things and we're a pretty small team. :-) 

I'll opt to close this issue, partially since we prefer the other solution but also because it solves the same problem so we can consider it part of the other issue anyway.

**Comment by Al-Caveman** [comment]
Thanks.  

Meanwhile, I am using this simple patch in case anyone is interested.  It solves the problem in this closed issue (tabs are now navigated vertically).

    diff --git a/src/con.c b/src/con.c
    index 4d1c6167..47763b6d 100644
    --- a/src/con.c
    +++ b/src/con.c
    @@ -1450,7 +1450,7 @@ orientation_t con_orientation(Con *con) {
             case L_SPLITH:
             /* tabbed containers behave like they are in vertical orientation */
             case L_TABBED:
    -            return HORIZ;
    +            return VERT;
     
             case L_DEFAULT:
                 ELOG("Someone called con_orientation() on a con with L_DEFAULT, this is a bug in the code.\n");

**Comment by Al-Caveman** [comment]
Turns out the final solution was easy.  I no longer use that dirty patch above.  Instead, I am now using the patch in the PR #3859.
