### ISSUE TITLE
Feature request: Configurable workspace namespacing

### ISSUE THREAD

**Issue by kennylevinsen** [i3/i3#3885]
## Problem description

Over in the sway issue tracker, these has been some discussion as to how deal with workspace navigation on arbitrary and dynamic monitor setups.

The i3 workspace model we use in sway works very well for single monitor setups, and with a bit of organization from the users' side, reasonably well for static dual monitor setups. However, friction that is hard to get around occurs when the monitor setup is more dynamic, especially at 3 or more monitors. To give a real-world example, my laptop is used both on its own and in different docks, leading to 1, 2 or 3 monitors active, with monitor 1 (laptop) either on both left and right.

At two static monitors, numbered workspaces can be managed either by simply distributing workspaces (e.g. `1`,`3`,`5` and `2`,`4`,`6`), or by using dedicated keybindings and workspace names for each monitor (e.g. `1-1`,`1-2`,`1-3` and `2-1`,`2-2`,`2-3` using `workspace X on output Y`).

The former has the issue that it gets cumbersome to deal with the modulo if your monitors change, and the order might differ if different monitors used imply different layouts (specifically, answering "what is the name of the next workspace on the monitor in front of me" requires looking around and doing *math*!). The latter, on the other hand, gets troublesome due to needing increasing numbers dedicated keybindings, and it also requires looking around to establish with keybinding the monitor in front of you follows.

## Proposed solution

A draft PR has been made against sway, which implements a simple config option: `workspace_namespace`, which can be set to `global` or `output`.

Ignoring minor signature changes, this change is at its core 4 lines: A toggle as to whether workspace lookups should be global (default, what both sway and i3 does right now) or output-only.

The end-result is that, if `output` namespacing is enabled, workspaces become local to an output, giving a behavior similar to awesomewm, in that every output gets a workspace "1" by default, and navigating workspace will always either go to or create the workspace on the given output, completely ignorant as to what workspaces exist elsewhere.

By default, or if `global` namespacing is explicitly set, then everything works as it does today.

Now, the reason this is mentioned here is that sway tries to retain i3 compatibility. For this, we need to know if the i3 community is interested in receiving this feature as well. Something similar to this feature has been discussed on the i3 issue tracker some years back, and questions seem occasionally asked around the internet. Seeing that a draft implementation is now available for sway, I believe it will be easier to discuss such feature now than it was in the past.

On the sway side, the PR is here https://github.com/swaywm/sway/pull/4846, and the issue is https://github.com/swaywm/sway/issues/4771. Note that they are closed due to i3 compatibility, so if i3 is interested, we can reopen them.

The template filled out below:

## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Workspaces are always global. Navigating workspaces on dynamic monitor setups can become difficult.

## Desired Behavior

Provide a way to make it easier to navigate workspaces on a monitor, regardless of monitor configuration.

**Comment by Airblader** [comment]
The solution is simple, but I think it is *too* simple. I can't see a scenario where users wouldn't eventually also need a way to target specific outputs in commands etc., significantly increasing the complexity of this feature. It probably needs some more thought, too, it feels like there should be more issues with this to consider.

I'm not categorically against this, but the proposed solution IMHO doesn't work for us.

**Comment by kennylevinsen** [comment]
Thanks for the feedback! Much appreciated.

Commands related to workspaces already have the ability to target specific outputs. The only hole I could find was in `move [container|window] to workspace ...` (and the equivalent `assign` operation), which instead would require bringing up the target workspace on the target output, and then issuing a `move [container|window] to output ...`. Adding an optional `output` argument would be simple, though.

If instead you meant that specific output targeting might bubble into something else, could you perhaps elaborate? This would make it easier to take into design considerations. Note that one of the key "quality of life" improvements for those needing this feature is indeed that it makes output actions explicit.

An alternative approach that I had in mind was to optionally have `<workspace>` arguments automatically prefixed with the output name. For example, if the feature was enabled, running `workspace current:1` might navigate you to `eDP-1:1`. Workspaces remain global and behave like normal in all other aspects. This implementation is more complicated, but nothing too complicated.

**Comment by Airblader** [comment]
> The only hole I could find was in […]

That was the one I mainly had in mind right now.

> Adding an optional output argument would be simple, though.

Proving my point that the additional feature creep can already be expected. :-)

> An alternative approach that I had in mind was to optionally have <workspace> arguments automatically prefixed with the output name.

Not sure I understand what automatic prefixing would do given that i3 doesn't understand output name prefixes in workspace names. Is this maybe something specific to sway? Or is supporting this part of the alternative proposal?

---

Thinking about this more I'm seeing a few more issues that make me lean towards not going with such a feature:

1. You can create broken setups by enabling the flag, creating multiple workspaces with the same name (on different outputs – since that is what this feature is about), disabling the flag and reloading your config.
2. Do specs even allow multiple desktops with the same name? I'm thinking of something like `_NET_DESKTOP_NAMES`. Even if allowed, this will easily be very confusing for tooling such as workspace switchers etc.

All of this makes me wonder if users aren't better served with an intermediate script that takes care of prefixing workspace names with the output name (or something else).

**Comment by kennylevinsen** [comment]
> Proving my point that the additional feature creep can already be expected. :-)

With only a single found place where extension is mostly optional, I'd consider that statement debatable. :)

> Not sure I understand what automatic prefixing would do given that i3 doesn't understand output name prefixes in workspace names. Is this maybe something specific to sway? Or is supporting this part of the alternative proposal?

The idea here is that the prefixes are added, but not interpreted under navigation. Let's say that prefixing is enabled, and will replace `current:` in workspace names with the output name. If you run `workspace current:2` on DP-1, it expands to `workspace DP-1:2`, which will not clash with workspace 2 names from other outputs. You are still free to directly address workspaces from other outputs if you'd like, just like you're free to create arbitrarily named workspaces.

This requires handling in initial workspace naming, and whether something should be done for prefixed workspaces when they are moved to other outputs should be decided upon.

This is of course less elegant, as most/all workspaces now have their respective output in their name.

> Thinking about this more I'm seeing a few more issues that make me lean towards not going with such a feature:
> 
> 1. You can create broken setups by enabling the flag, creating multiple workspaces with the same name (on different outputs – since that is what this feature is about), disabling the flag and reloading your config.
>
> 2. Do specs even allow multiple desktops with the same name? I'm thinking of something like `_NET_DESKTOP_NAMES`. Even if allowed, this will easily be very confusing for tooling such as workspace switchers etc.

None of these are issues under the prefix approach, which now seem increasingly more appropriate, even if not as "pretty" due to exposing output names everywhere.

As for the original approach:

1. Good point. A workspace name collision check would need to be added.
2. This is unique to i3, and I'd have to look into it to figure out if that would be an issue.

> All of this makes me wonder if users aren't better served with an intermediate script that takes care of prefixing workspace names with the output name (or something else).

This is a fair point. While the original designcould not be implemented externally, the prefix approach can technically be made that way.

Doing so would require 3 parts:
1. A script that replaces *all* user normal workspace reference, looking up the current output for prefixing.
2. A script that is run on startup that enumerates all outputs, and navigates to prefixed workspace 1 on every one of them.
3. Optionally a IPC daemon that handles when a workspace is moved to another output, renaming these workspaces to match their new home and ease navigation.

This could certainly work, but basically reimplements all workspace interaction outside i3/sway, which I find to be a bit of a shame. Even so, it could at least be used as an experiment.

**Comment by zsugabubus** [comment]
> All of this makes me wonder if users aren't better served with an intermediate script that takes care of prefixing workspace names with the output name (or something else).

Sorry for not being too constructive but I would like to mention the exact same thing: On the Sway thread I proposed two three-liner script that solves the issue.

"global or output" seems an all or nothing choice for me. Why to make such a rigid decision when it could be achieved with a few lines of code? Scripting is the freedom and it's more than enough if i3/Sway just provides the basic building blocks for it. 

I would also like to note that one can use marks for making long jumps. It's quick and you can even associate a program with a letter for easy remembering. With the proposed "output" workspace addressing you first have to navigate to the desired output then the desired the workspace. It's at least 3-4 keystrokes at best.

> A script that replaces all user normal workspace reference, looking up the current output for prefixing.

_All_ is just not a such big hit as it seems.

> A script that is run on startup that enumerates all outputs, and navigates to prefixed workspace 1 on every one of them.

It's absolutely not needed: Say you have a startup opened workspace "7" on the second display. You switch to "2-1" and "7" will disappear because it's not used. (But it can be also done with a three-liner.)

> Optionally a IPC daemon that handles when a workspace is moved to another output, renaming these workspaces to match their new home and ease navigation.

That isn't even solved with the proposed "output" addressing. What to do when name collisions occur?

**Comment by Airblader** [comment]
> This is of course less elegant, as most/all workspaces now have their respective output in their name.

This could be solved with an option similar to strip_workspace_numbers (for i3bar, anyway). 

In general the prefix approach seems more robust to me.

> This could certainly work, but basically reimplements all workspace interaction outside i3/sway, which I find to be a bit of a shame. Even so, it could at least be used as an experiment.

A benefit is that due to compatibility you'd immediately have a working solution for both i3 and sway. :-) 

For the record, I'm still undecided on this either way, but I think a script would give us a better feeling for this (without commitment) as well as potentially show weaknesses in the approach. We also generally tend to relay features which can be implemented as scripts to scripts if the feature otherwise implies a significant change (be it in code or how i3 works). 

---

@zsugabubus Being opposed is not "not constructive", I appreciate additional opinions regardless of whether they are in favor or not, so thank you :-)

At least for the moment I tend to agree that a script would be good for everyone as it gives a timely solution and can help in getting a better understanding of this.

**Comment by kennylevinsen** [comment]
@Airblader Thank you for your feedback. Much appreciated. :)

I'll make a "fully-featured" external implementation for experimentation, including the proposed workspace renaming on move. I believe I will hit some things that I cannot solve externally without disproportionate efforts, but we can take it from there.

I'll close this issue for now and return with more data at some undefined point in the future. :)

**Comment by Airblader** [comment]
@kennylevinsen I'd be happy to leave this issue open (if you prefer)

**Comment by kennylevinsen** [comment]
Sure, let's keep it open for now then. Might help keep the discussion in one place.

**Comment by Hyask** [comment]
> @kennylevinsen 
> I'll make a "fully-featured" external implementation for experimentation, including the proposed workspace renaming on move. I believe I will hit some things that I cannot solve externally without disproportionate efforts, but we can take it from there.

Do you still have that external implementation somewhere? I'd be happy to provide some feedback on this matter, from a simple user pov.

**Comment by orestisfl** [comment]
This sounds like something that is possible w/ IPC + #3818, am I correct?

**Comment by Hyask** [comment]
I've made a working prototype that I've used daily with sway for a few weeks now: https://git.hya.sk/skia/swaysome  
I've no idea if it works with i3, but feel free to hack with it!

**Comment by orestisfl** [comment]
Thanks! Since the functionality can be implemented externally I am closing in favor of #3818 (if needed for better naming on i3bar).
