### ISSUE TITLE
Feature Request: Add a command to call setenv inside the i3 process

### ISSUE THREAD

**Issue by Muffindrake** [i3/i3#3899]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

It's presently not possible to set environment variables in i3 so that they are inherited by new window processes. You have to fully restart X11 with the new environment that you wish to use and then start i3, which kinda kills your session. Or you can use gdb to call put/setenv inside the i3 process, but that's a bit of a heavy-handed approach.

## Desired Behavior

An i3 command should be available that lets you call the POSIX function `setenv` inside i3. Possibly also `unsetenv`.

## Environment

<pre>
i3 version: 4.17.1
</pre>

<pre>
- Linux Distribution & Version: Gentoo Linux 
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

**Comment by Airblader** [comment]
> You have to fully restart X11

This isn't true; you have to restart i3, not X11. If you run something like `exec i3` you're replacing the process and the X server closes if i3 ends, but this isn't mandatory but part of the setup.

As for the feature request, you haven't presented a reason for where this is useful – and I don't really see one. We don't support environment variables to be used in the config in any way, and for commands executed through i3 you can set the environment variables from the command rather than modifying i3's environment. Ultimately also offering specialized commands to do things unrelated to i3 but rather the underlying system seem like the wrong solution to the problem, so I don't think we'll want to add this to i3.

If you have further questions or points please do feel free to ask / answer.
