### ISSUE TITLE
enhancement: rename master branch to stable

### ISSUE THREAD

**Issue by stapelberg** [i3/i3#4127]
“master” is a hurtful word to some readers, so we should avoid it.

In addition, `stable` is also more descriptive for what the branch contains: the most recent stable release, plus any commits already cherry-picked for the next stable release.

This should be a simple change. Not much more than a few scripts will need updating. The default branch for our repository is already `next`, so not many downstream users will care.

**Comment by orestisfl** [comment]
I don't consider "master" a hurtful world, when not accompanied by "slave".

That said, I agree that "stable" is a much better term.

**Comment by Airblader** [comment]
I'll take the unpopular opinion here and say that I disagree. Has anyone actually reported to us that they feel offended by the branch name (and why)? 

I don't see this change truly benefitting anyone. I fully support the BLM movement, but "master" is a normal English word, it's the default git branch, and it's well established. Not the word hurts, its historic connotation does, and I cannot imagine we transmit any reference to US slavery anywhere in this project. I don't see a good reason to shun this word off the face of the planet when it has a diverse set of meanings and applications, like mastering a skill, grandmaster, world master, being an academic degree, ...

This creates unnecessary work for any package maintainer who builds from git. That won't be many people, but my guess is it's more than have come across i3 and felt offended by the branch name.

That said, I'm not looking to argue, it's also not really worth it, and if you want to follow through with such a change it's obviously your right to do so.

Side note: while it is true that stable could be seem as more descriptive, we very likely wouldn't be making this change for that reason alone.

**Comment by stapelberg** [comment]
> Has anyone actually reported to us that they feel offended by the branch name (and why)?

Plenty of people have reported this, but not directly to me or the i3 project that I know of. This doesn’t mean we can’t be proactive.

Similarly, if I hear that changing colors in a certain way helps vision-impaired people to read documentation, I can proactively change the i3 colors without having to wait for anyone to complain to me directly :)

> it's the default git branch

…and that actually directly stems from a master/slave occurrence: https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html

---

As you mention, this is not really worth discussing. Even if the benefit is purely symbolic, and a number of people get annoyed because they have to change one word in their build files, I think it’s worth doing.

**Comment by orestisfl** [comment]
Another technical argument in favor of the rename is that, as mentioned, "master" is the default branch used for development. However, since we use it as a "stable" branch, people can make mistakes because they are used to using "master" as the development branch. For example, running `git rebase origin/master` instead of `git rebase origin/next` might lead to non-obvious problems for someone who is not used to our naming scheme.

I don't agree with the argument that master refers to "master/slave" because of bitkeeper's naming scheme. The analogy does not work with git's workflow.

**Comment by szabadulas** [comment]
Wow, it is the zombie apocalypse, and I am the last man not infected by the zombie brain virus. 

Oh, wait, no, it’s getting to me… AGHHH… *“Stable” is unacceptable. It is a place where horses are kept in captivity. I am deeply offended.* …

… No, no, no, I must fight it … *“git” is disrespectful to people of* … I must fight it… *GIMP is ableist* … must fight … *science is violence* … must fi… *words offend me* … must … *reality offends me* … I mus … *I am offended* … I … *KOWTOW TO ME!*

**Comment by Airblader** [comment]
@ariand While I also disagree with the necessity or usefulness of this, let's please still try to be respectful about it. Thanks!

**Comment by szabadulas** [comment]
Respect is earned, nobody is entitled to it. I hate to see freedom disappear from what was once called *free software* because a bunch of totalitarians posing as the champions of justice have so much psychological power over others that even software developers are forced to self-censor the very words they use. If losing whatever little freedom the people of this earth still have is not a big deal to you folks — well, I cannot respect it, but I also cannot do anything about it, so I will leave you alone.

**Comment by orestisfl** [comment]
@ariand This is ridiculous on so many levels. Nobody's freedom is disappearing because of master -> stable.

Free software is not about users dictating their preferences to developers. You still have the option to fork i3 and rename the branches however you like.

**Comment by Airblader** [comment]
Let's please not have this discussion here. @stapelberg is the owner of this project and has a final say. This is clearly documented in our governance model.
