### ISSUE TITLE
Allow for including configuration partials

### ISSUE THREAD

**Issue by moritzheiber** [i3/i3#4192]
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Currently, i3 only "knows" about a single configuration file it reads at runtime and processes as a whole. It does allow for modifications coming from [`Xresources`](https://i3wm.org/docs/userguide.html#xresources), however, those are all included in the single, main configuration for it to read out once and then conclude its configuration phase at the end of it.

What the `Xresources` method is incapable of though is the modification of configuration *instructions* e.g. `for_window`, `assign` or similar objects. To change those you always have to go back and edit the configuration file and restart i3 afterwards (thankfully, i3 makes this process rather convenient!).

You cannot tell i3 to "look somewhere else" for other configuration instructions, it's a single file. Full stop.

## Desired Behavior

What I would love to have in i3 is the capability to **include other configuration partials**, or "snippets", which are then *merged* into a single, large configuration *tree*, interpreted and i3 then configured accordingly. Something along the lines of:

```
# /etc/i3/config
[...]
for_window [class=something] floating enable

include /home/user/.config/my_customizations
```
```
# .config/my_customizations
for_window [class=something] floating disable
```
If you're taking advise from popular configuration parsers it'll probably be along the lines of "last instructions wins" (e.g. whatever "overrides" the configuration in the tree last determines the behavior), but I'm not tied to it.

One could also ponder the ability to check for user-defined configurations automatically (e.g. in `~/.i3/config`) as i3 does it today, even when it's told to look somewhere else, but that might introduce more harm than good.

## What is the use case?

I'm a contributor for a i3-based Linux distribution called Regolith Linux, which is making it possible for folks to configure i3 to their liking to a certain extend, using `Xresources`. We are pretty far ahead with how many of the potential options you're able to change, however, for the more advanced customizations (e.g. `assign` or `for_window`) you have to follow [a process called "staging" for the configuration files](https://regolith-linux.org/docs/howto/stage-configs/#i3-config) in order to extend i3's functionality. This has the obvious disadvantage that it might potentially cause the staged configuration to become stale as soon as the system-wide i3 configuration file living in `/etc/regolith/i3/config` changes over time (e.g. we're fixing bugs, introducing new functionality etc.). This diversion not only causes pain for the users, as they have to manually keep track of how the global configuration changes over time, but it's also a pain in the butt for us contributors, since a lot of bug reports are essentially "staged" configurations that haven't been updated in a while.

The ability to partially override settings of i3 that aren't assignments static instructions, but actually provide instructions on your own would complement the already existing flexibility in the configuration system and allow for folks to rely on sane defaults from the get-go.

## Environment

This applies to all environments i3 is running in.

**Comment by rpigott** [comment]
FWIW, sway implements this and the feature is widely used by sway users.

Some ways this feature have affected sway:

1. The default sway config contains `include /etc/sway/config.d/*`. As this inclusion suggests, the `sway` package in Arch Linux, for example, ships distro-specific configuration in `/etc/sway/config.d/50-system-user.conf`. Other distros or user built packages may include specific configuration as well, like how OP suggests, and in my experience it works out well.

2. It simplifies configuration management between multiple machines. Sway has an increased need for this considering it is also responsible for input and output device configuration, but it's not hard to imagine different bar preference on different machines, different keybinds on different keyboards, or different gap sizes on your larger monitor in the case of forks (soon-to-be-merged?) like i3-gaps. Adding "includes" allows one single config to manage common configurations and custom configs to be kept separate. Because sway also allows for word expansion `man 3 wordexp` in the include statement, it enables a single version control repository to manage all machine local configuration and for the "main" config to include the correct one, for example by hostname match.

Just as sway has benefited from i3 by copying i3's proven design, i3 can benefit from sway in this case by copying this useful feature.

There is at least one notable issue related to this feature that should be discussed: Should the I3IPC "get_config" command substitute included content, or return "include" lines as is? Prior discussion in swaywm/sway#5559

To accommodate 3rd party clients that retrieve keybindings from configs, which I believe are the primary users of this query, I think i3 should either substitute included content or consider a new ipc based method to get key bindings.

**Comment by stapelberg** [comment]
This feature request was last discussed and declined in https://github.com/i3/i3/issues/1197#issuecomment-195646042

If you think we should revisit this, can you please go through the points raised in the previous discussion and write down clear answers for how to handle those nuances?

**Comment by rpigott** [comment]
imo:

> One thing that hasn’t been discussed is how a nested directory structure and symbolic links would be handled.

Every unique real path can be included at most once. The main config path is also already included, and will not be included again. This allows no circular includes. Including two symlinks with the same target only includes the content once. Most i3 configuration is either idempotent or singular (same bindsym twice is an error) so this behavior makes the most sense for i3.

This means that i3 will maintain a list of the real paths of files it has included that is discarded and rebuilt on reload.

> Also, error handling becomes more complex: should a single unreadable file lead to i3 not starting up or not?

Likewise, included pf the same file twice and includes of nonexistent or unreadable (no permission) files are silently ignored. Optionally, i3 could print a low priority log message about it. Including a readable file with invalid syntax or other config error is an error, and i3 or i3 nagbar should identify the file with the source of the error in the error message. i3 should be permissive in these cases so that users can re-use their personal config on many machines with lines like `include host1.conf`, `include host2.conf` that will always succeed while including those files if they exist.

**Comment by stapelberg** [comment]
> Every unique real path can be included at most once.

So you’re suggesting evaluating symlinks fully, like https://golang.org/pkg/path/filepath/#EvalSymlinks, yes? Do you happen to know how to do that properly in C?

One alternative (?) might be to check if the files are the same (i.e. same inode on the same file system).

> Likewise, included pf the same file twice and includes of nonexistent or unreadable (no permission) files are silently ignored.

No, this is not a good failure mode. If i3 can’t read your config, it must throw an error loudly. I think I’m okay with adding an explicit flag (e.g. `include --ignore_errors`) to cover the use-case you mentioned, but by default it must error.

**Comment by rpigott** [comment]
> Do you happen to know how to do that properly in C?

I would use https://man7.org/linux/man-pages/man3/realpath.3.html

> No, this is not a good failure mode. If i3 can’t read your config, it must throw an error loudly.

Okay, but I still think double include should remain idempotent without error. Maybe a "skipping already included config" line.

**Comment by moritzheiber** [comment]
Thank you everyone for chiming in here, I appreciate it!

I don't have nothing much to add to what's been said already, except maybe that I would consider what I described as a potential value-add as a "solved problem" from a technical perspective (i.e. other applications are doing this, it works for them, it's a pattern that has shown to provide value).

**Comment by ghost** [comment]
@moritzheiber, Don't bother, it seems no one cares!

**Comment by ghost** [comment]
I agree that we need ``include`` for external config files. Having one large config file really hard to work on. Especially if you have tons of customizations. Also this would allow us to keep our configs seperated by functions. Like ``modes`` or ``bars`` having there own config files :-) To i3 team, please consider implementing this in the future versions.

**Comment by stapelberg** [comment]
Pull request #4420 sent!

If you want to try it out, feedback would be appreciated.

**Comment by ghost** [comment]
@stapelberg EPIC! Feature addition to i3 :-) I hope it works with specific config files too not just directory wildcards.

Also variables should work smarter. For example, if a variable is defined in main ``~/.config/i3/config`` it should be reusable in included configs without having to re-define the same variable in each config file. Unless, it is overriden in this included config file.

For example:
```
# Main Config (~/.config/i3/config)
set $mod Mod4
include ~/.config/i3/misc
```
```
# Included Config (~/.config/i3/misc)
# $mod variable from main "config" should also work in "misc" config by default.
# unless this same variable is overriden in this file with something like; set $modifier Mod4
bindsym $mod+t exec terminal
```

**Comment by Airblader** [comment]
@tuxy If you look at the changes to the userguide in that PR you'll find the answer to both of your questions :-)

**Comment by ghost** [comment]
@Airblader Where? Can you provide a link?

EDIT: Is this the link?  https://github.com/stapelberg/i3/commit/ec798dc54bab4ab1ba7138f174fe5717f8e85f42

**Comment by Airblader** [comment]
https://github.com/i3/i3/pull/4420/files#diff-5f2381f5ec1edab4edc339a099a3f91c24ca1656d0e1dc8f848444f9750df6e8 

Jump to -> userguide

**Comment by ghost** [comment]
@Airblader THANK YOU! Yeah this is exactly the feature I wanted ^_^ I think this was the only thing that I have missed in i3 since I started using it. Thank you to everyone who made this happen!

**Comment by stapelberg** [comment]
Over on pull request #4420 we have been discussing some nuances of the `include` directive.

Here is what the proposed addition to the userguide currently looks like:

![include](https://user-images.githubusercontent.com/55506/118378647-74f7f200-b5d5-11eb-8a96-49d75d5d977a.jpg)

In particular, I wonder whether the override semantics and variable semantics are fine in practice, or present deal-breakers for anyone. 

If you have any feedback (and/or ideally would be willing to give the new code a shot to see whether it works out), please let us know!

**Comment by ghost** [comment]
@stapelberg, Guide looks good and thank you for accepting this feature. Override of variables can be introduced later if you want and think that it wont break anything else. But for the first revision of this feature even this is enought.

EDIT-1: One thing I did not see in this userguide is main config file. What is the main config file name that needs to be used or we can use any name? I think its a good idea to keep ``~/.config/i3/config`` as the main config file, to not break anything. ``include`` feature should be optional for those who want to use it. It's also a good idea to allow usage of global variables in main config to be reused in included configs [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle. But also allow seperate variables in included configs, if same variable is used in both main config and included config, it should just show an error and tell people to use one or the other. But if this breaks too many things, than at least allowing seperate variables per config is good enought.

EDIT-2: About command substitution (backticks), in bash there is also something like this ``$(command)`` it can be useful to have this too in include. For instances when you want wrap your path in quotes like this ``include "~/.config/i3/$(hostname).conf"`` it is also a bit more user friendly/readable.

EDIT-3: Looks like in userguide global/local variables already work like asked in EDIT-1 (I think, will have to try it in v4.20 once out.) And also overriding keybindings and other functions is not needed. Because any config should follow "KISS" and "DRY" principles. Any idea when v4.20 will be out? Sometime in 2021 will be great :)

**Comment by stapelberg** [comment]
> One thing I did not see in this userguide is main config file.

The config file location is documented at https://manpages.debian.org/buster/i3-wm/i3.1.en.html#FILES and will not change.

> But also allow seperate variables in included configs, if same variable is used in both main config and included config, it should just show an error and tell people to use one or the other.

I’m not planning to introduce a separate variable space per config file.

> EDIT-3: Looks like in userguide global/local variables already work like asked in EDIT-1 (I think, will have to try it in v4.20 once out.) And also overriding keybindings and other functions is not needed. Because any config should follow "KISS" and "DRY" principles. Any idea when v4.20 will be out? Sometime in 2021 will be great :)

When v4.20 is out, it will be too late to change this behavior. My question was whether people can compile i3 from the pull request and try it out. I’m interested in early feedback before the next release.

**Comment by ghost** [comment]
@stapelberg good to know that ``~/.config/i3/config`` main config wont change. Even if variables can just be in main config that good enought. As for compiling 4.20 and testing, unfortunatly I can't. I have a production environment and unstable/testing is not an option. But I will try stable version when its out. If anyone else that can test it this will be great. Thank you for taking your time to implement this correctly.

**Comment by stapelberg** [comment]
Perhaps @moritzheiber and/or @RPigott could chime in or give the proposed code a spin?

**Comment by Airblader** [comment]
We could also ask users on Reddit to test this. It's a pretty popular request especially in those kinds of communities, so I'm fairly sure we'd find some people there.

I can also prepare an i3-gaps branch as some may want to try it but are using i3-gaps.

**Comment by stapelberg** [comment]
> We could also ask users on Reddit to test this. It's a pretty popular request especially in those kinds of communities, so I'm fairly sure we'd find some people there.

That’s a great idea! Can you post on Reddit please?

**Comment by kgilmer** [comment]
I'm not sure if Moritz is around right now to do testing, but I'll do some testing with Regolith in the coming week or next (in the final lap of a release at the moment).

**Comment by Airblader** [comment]
> That’s a great idea! Can you post on Reddit please?

[Done](https://www.reddit.com/r/i3wm/comments/ndtbcf/looking_for_testers_for_the_new_include_directive/)

**Comment by kgilmer** [comment]
## Testing Status Report

### Environment

Fresh install of Ubuntu Hirsute running (pre-release) Regolith 1.6.

### Test Strategy

1. Compile i3-gaps `include` branch into `/usr/local`.  Modify Regolith session init script to call local build of i3 rather than the one shipped in the i3-gaps package
2. Make a small change to config, remove keybinding stanza for gnome control center and put in a seperate file `mgmt`.  Add include declaration in config file to (relatively) depend on new `mgmt` partial.
3. Log into a fresh session

### Observations
1. Keybinding to gnome control center continues to work, telling me that the partial has been loaded successfully
2. Unexpectedly upon startup, rather than starting with workspace 1 I see workspace 11. (see screenshot)
3. If I keep the `include` version of i3-gaps binary but revert to the (Regolith) default config, upon login I see workspace 1.  So it seems that loading workspace 11 by default is connected to the include expression or some side effect.
4. reverting back to stock i3-gaps bin w/ (Regolith) stock config file shows default workspace as 1

**_Config files are attached._**

![Screenshot from 2021-05-16 15-44-30](https://user-images.githubusercontent.com/49683/118415710-dadd8b80-b660-11eb-8ff0-6b2e60168eb0.png)
[config-files.tar.gz](https://github.com/i3/i3/files/6490220/config-files.tar.gz)

**Comment by stapelberg** [comment]
Thanks for the report, @kgilmer!

I have fixed the issue and added a test.

@Airblader might need to pull my `include` branch into the i3-gaps repository.
