### ISSUE TITLE
Option to restrict corners for floating mouse resize a la xmonad

### ISSUE THREAD

**Issue by djvs** [i3/i3#4286]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
Resizing is hard-coded (floating_resize) to resize in the direction of the quadrant of a window that's clicked on

## Desired Behavior

There should be a configuration option to specify "all" or a specific corner ("topright", "bottomleft" etc) to restrict resizing to.  Optionally, cursor could also be forced to jump to the location of the corner in question.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:

Binary i3 version:  4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors

Running version: < 4.2-200 
</pre>

<pre>
- Linux Distribution & Version:
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

Doesn't matter, but yes, xcompmgr

Literally just filing this to try to expedite my PR on "sway" where they expressed they wanted i3 to say this is "worth implementing":

https://github.com/swaywm/sway/pull/5897

But it would be great to have on i3 too.

**Comment by Airblader** [comment]
What would be the benefit of this? 

In general I have a bit of trouble with people requesting features from i3 they aren't even going to use (because they don't use i3). We're not going to add things just so that the sway project feels comfortable adding them.

**Comment by djvs** [comment]
Ergonomically, it's way better, much more predictable behavior if you're at the center of a window.  sway is basically a mirror of i3 in any case -  I notice the default behavior is jarring and hard to anticipate.  Very commonly in my (xmonad) workflow I'll do a rapid succession of left click move and right click resize to very quickly get a window where I want it, which takes easily 10x as long when the result can't be predicted without first observing which quadrant of the window the mouse is in...it's a good thing to have configurable if nothing else.

**Comment by djvs** [comment]
I don't think they even want you to add it though...more like they want you to say, "this sounds like a good idea!"  What can I do...

**Comment by Airblader** [comment]
My understanding of their response is that they will only implement this if we do, too, or at least accept it as a feature request. That's not something I'm willing to do just for sway to move ahead with it. I understand that this is likely frustrating, but it's not our decision what sway does or doesn't do. 

> much more predictable behavior if you're at the center of a window.

> There should be a configuration option to specify "all" or a specific corner ("topright", "bottomleft" etc) to restrict resizing to. 

Instead of (presumably) unpredictable cursor jumping you now have unpredictable behavior of whether the cursor does or does not jump. Unless I am misunderstanding something that's not a solution for that problem.

> it's a good thing to have configurable if nothing else.

https://faq.i3wm.org/question/778/why-is-patch-not-merged-and-made-optional/index.html

**Comment by djvs** [comment]
It's fully predictable with that - it's bottom right edge of the window, if you specified bottomright (can't imagine why someone would pick a different corner, but that's just me).  If you try the default behavior of xmonad you'll see what I'm talking about - the cursor simply jumps to the bottom-right corner of the window you mod-right-click'ed on, so while you have it pressed your cursor remains at that exact corner as you move it.  It's very intuitive and IIRC was why I picked xmonad over i3/dwm/awesome/etc. about a decade back.

**Comment by djvs** [comment]
I think "basic config of resize behavior with mouse in float" is well within the scope of concern for even the most minimal tiling WM.  Literally got to configuring sway this morning and it was within first 5-10 items to address.

**Comment by Airblader** [comment]
> I think "basic config of resize behavior with mouse in float" is well within the scope of concern for even the most minimal tiling WM.

I disagree, especially as you say floating and we're talking about a tiling window manager. In i3 specifically we keep floating support very minimal.

> can't imagine why someone would pick a different corner, but that's just me

If you find other choices useless, why suggest them as a feature?

Please note again that all of this is a moot point. I'm not going to accept a feature for sway. That is their call.

**Comment by Airblader** [comment]
From an older similar request there was a response from the sway team that is relevant for this discussion as well: https://github.com/i3/i3/issues/3774#issuecomment-522823068

If sway decides that  feature is beneficial enough to merge it, they can do so. If they by default just don't accept anything that i3 doesn't accept as well, regardless of whether they think it'd be useful, that is their choice to make, but it does not influence our decision making. 

We will not turn away great ideas that come along based on where they come from, but this doesn't strike me as such an idea. It's a fairly minor request at the expense of more configuration, in an area where we want to keep complexity lower than anywhere else even. Given that at its core this request isn't actually for i3 I'm going to close this, sorry.

**Comment by djvs** [comment]
OK, well for some reason i3 finds it appropriate to dictate that it's going to resize a window from whatever quadrant you click the window in, but an option to configure that is invasive.  Your call, whatever.

**Comment by emersion** [comment]
>We're not going to add things just so that the sway project feels comfortable adding them.

For the record, that's perfectly fine by me, and that's exactly why I ask people to request i3 to accept the feature. i3 has a good policy of trying to understand _why_ a feature request is deemed necessary and only accepting the feature if the maintenance costs are reasonable. I consider the window management features of Sway more-or-less "done", restricting the new features to i3's allows us to avoid feature creep and make sure Sway doesn't become too complicated.

Let me know if we're causing you trouble.

**Comment by Airblader** [comment]
It's a two-edged sword for me. There may be ideas that are so obviously useful that we could accept them regardless of what the context is, but that's probably a rare exception. Most features may or may not have some merit them, or justify their cost, and have to be evaluated.

I don't see a good reason for accepting this specific request¹ for i3 because it's not a feature request _for_ i3. Sway can't really use the same argument, because it _is_ a feature request for sway. But sway being in a maintenance mode of not accepting features other than for i3 compatibility _is_ an argument. Just a different one.

¹ I maybe want to stay away from saying that I _reject_ this feature. While that is indeed my initial feeling here as well, I'm mostly closing this as "invalid" because it's not an i3 feature request in the first place. A feature not even used by the person suggesting it feels like bloat out of the box to me.

This issue has gotten me thinking about a couple things last night which I think I will raise internally.

**Comment by Airblader** [comment]
To put this into a different light:

Sway started as a project aiming to have "i3 for Wayland". If we accept requests like this, we turn i3 into a "sway for X11", and that is not our goal. 

This feature request comes from the sway community, for the sway project.
