### ISSUE TITLE
Monitors crashing when launching Intellij IDEA or Teams only on i3wm

### ISSUE THREAD

**Issue by thomas-rooty** [i3/i3#5396]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When starting apps like Intellij IDEA or Microsoft Teams (note that both two have been installed using snap, and has a starting splash screen), sometimes (maybe 1 out of 5 times), my dual monitors are being disconnected, the setup is one laptop screen, connected using a USB-C Dock to two external monitors delivering the correct amount of power supply.
Managed using xrandr

Note also that I had this problem both on Manjaro and now on a fresh Ubuntu install

## Expected Behavior

Should not crash

## Reproduction Instructions

Connect a laptop using a Dock, and open Intellij IDEA or Teams and randomly it should crash

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.22
</pre>

<details><summary>[Config file](https://pastebin.com/rHkyi41w)</summary><pre>
</pre>
</details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/6196230807879680.bz2
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 22.04 Jammy
- Are you using a compositor (e.g., xcompmgr or compton): picom
</pre>

**Comment by orestisfl** [comment]
As the bot said in #5395, we only support the latest version. Since the log files in both issues is the same, I am going to assume you didn't reproduce with the latest version. Also, the logs you uploaded seem to be from the archived https://github.com/airblader/i3 repo. If you open a new issue with a new log file, please make sure that it is a minimal one that only contains the logs from when the problem appears.

In addition to that, i3 does not connect or disconnect monitors, it looks like this is not an i3-specific issue. Try to reproduce it with another wm like openbox.
